import test from 'node:test';
import assert from 'node:assert/strict';
import {initialInventory} from '../lib/os/inventory-model.ts';
import {prepareProductImport,applyProductImport} from '../lib/os/product-import.ts';
const headers=['name','sku','barcode','price','cost'];
test('product import creates and updates atomically without losing stock or identity',()=>{const source=structuredClone(initialInventory);const before=structuredClone(source);const rows=[headers,['Новое имя','SKU-100',source.products[0].barcode,'2 000,50','1000'],['Новый товар','NEW-1','000123','150','90']];const plan=prepareProductImport(rows,source);assert.deepEqual(plan.entries.map(entry=>entry.action),['update','create']);assert.deepEqual(plan.errors,[]);const next=applyProductImport(source,rows);assert.equal(next.products[0].price,2000.5);assert.equal(next.products[0].id,source.products[0].id);assert.deepEqual(next.products[0].stocks,source.products[0].stocks);assert.equal(next.products[0].category,source.products[0].category);assert.equal(next.products.at(-1).barcode,'000123');assert.deepEqual(next.products.at(-1).stocks,{main:0,reserve:0});assert.deepEqual(source,before)});
test('bad rows, repeated SKUs and barcode collisions reject the whole import',()=>{const rows=[headers,['Good','NEW','123','20','10'],['Bad','BAD','456','','10']];assert.equal(prepareProductImport(rows,initialInventory).errors[0].row,3);assert.throws(()=>applyProductImport(initialInventory,rows),/Строка 3/);assert.equal(prepareProductImport([headers,['A','NEW','123','1','0'],['B','NEW','456','1','0']],initialInventory).errors[0].row,3);assert.match(prepareProductImport([headers,['A','NEW',initialInventory.products[0].barcode,'1','0']],initialInventory).errors[0].message,/Штрихкод/)});
test('update mode is explicit and trash cannot be silently restored',()=>{const row=[headers,['A','SKU-100','','1','0']];assert.match(prepareProductImport(row,initialInventory,false).errors[0].message,/уже существует/);const state=structuredClone(initialInventory);state.products[0].deleted=true;assert.match(prepareProductImport(row,state).errors[0].message,/корзине/);assert.equal(prepareProductImport([['name','sku'],['A','NEW']],state).errors[0].row,1)});
test('omitted optional columns preserve previous values, blank prices do not become zero',()=>{const rows=[['name','sku','price'],['A','SKU-100','25']];const result=applyProductImport(initialInventory,rows).products[0];assert.equal(result.cost,initialInventory.products[0].cost);assert.equal(result.barcode,initialInventory.products[0].barcode);assert.equal(result.unit,initialInventory.products[0].unit);assert.throws(()=>applyProductImport(initialInventory,[['name','sku','price'],['A','NEW','']]),/цены/)});

test('legacy POS export headers and unit codes are accepted',()=>{const rows=[['SKU','Название','Категория','Штрихкод','Закупка','Продажа','Ед.','Остаток'],['LEGACY','Товар','Уход','000001','50','75','piece','99']];const product=applyProductImport(initialInventory,rows).products.at(-1);assert.equal(product.cost,50);assert.equal(product.price,75);assert.equal(product.unit,'шт.');assert.equal(product.barcode,'000001');assert.deepEqual(product.stocks,{main:0,reserve:0})});
