import test from 'node:test';
import assert from 'node:assert/strict';
import {initialEmployees,initialRoles,hasAccess,actionPermissions,saveEmployeeProfile,changeEmployeeStatus,employeeProfileForViewer} from '../lib/os/team.ts';
const actor={employeeId:'owner-user'},date='2026-10-07T10:00:00Z';
test('cashier can operate POS and read CRM but cannot edit clients, use analytics or inherit page overrides elsewhere',()=>{
 const cashier={...initialEmployees[1],role:'cashier'};
 assert.equal(hasAccess(cashier,initialRoles,'pos','finance'),true);
 assert.equal(hasAccess(cashier,initialRoles,'pos','create'),true);
 assert.equal(hasAccess(cashier,initialRoles,'crm'),true);
 assert.equal(hasAccess(cashier,initialRoles,'customers'),true);
 assert.equal(hasAccess(cashier,initialRoles,'crm','edit'),false);
 assert.equal(hasAccess(cashier,initialRoles,'customers','create'),false);
 assert.equal(hasAccess(cashier,initialRoles,'analytics'),false);
 assert.equal(hasAccess(cashier,initialRoles,'reports','create'),true);
 assert.equal(hasAccess(cashier,initialRoles,undefined,'password'),true);
 const missingPage={id:'custom',name:'Custom',pages:['help'],actions:['edit'],pageActions:{pos:['finance']}};
 assert.equal(hasAccess({...cashier,role:'custom'},[missingPage],'pos','finance'),false);
 const legacy={id:'manager',name:'Моя роль менеджера',pages:['crm'],actions:['edit']};
 assert.equal(hasAccess({...cashier,role:'manager'},[legacy],'pos','finance'),false);
 assert.deepEqual(actionPermissions({...cashier,role:'manager'},[legacy],'crm').edit,true);
 assert.deepEqual(legacy,{id:'manager',name:'Моя роль менеджера',pages:['crm'],actions:['edit']});
});
test('employee profile changes preserve account state and custom fields, record real history and redact compensation',()=>{
 const employees=initialEmployees.map(employee=>employee.id==='aiym'?{...employee,custom:'preserve',forcePasswordChange:true}:employee);
 const input={...employees[1],department:' Продажи ',kpi:'20 консультаций',salary:42000,payScheme:'Оклад + премия',contract:'Трудовой договор',duties:'Консультировать',hiringPurpose:'Помочь клиентам',mainObjective:'Качество обслуживания'};
 const next=saveEmployeeProfile(employees,initialRoles,input,actor,date),updated=next.find(employee=>employee.id===input.id);
 assert.equal(updated.salary,42000);
 assert.equal(updated.department,'Продажи');
 assert.equal(updated.custom,'preserve');
 assert.equal(updated.forcePasswordChange,true);
 assert.equal(updated.profileHistory.length,1);
 assert.match(updated.profileHistory[0].action,/оклад/);
 assert.doesNotMatch(updated.profileHistory[0].action,/42000/);
 const publicProfile=employeeProfileForViewer(updated,false);
 assert.equal(Object.hasOwn(publicProfile,'salary'),false);
 assert.equal(Object.hasOwn(publicProfile,'payScheme'),false);
 assert.equal(publicProfile.mainObjective,input.mainObjective);
 assert.equal(updated.salary,42000);
 assert.equal(employees[1].salary,undefined);
 const same=saveEmployeeProfile(next,initialRoles,updated,actor,date);
 assert.equal(same,next);
});
test('profile and lifecycle mutations require team rights; owner identity and terminated history remain protected',()=>{
 assert.throws(()=>saveEmployeeProfile(initialEmployees,initialRoles,initialEmployees[1],{employeeId:'aiym'},date),/запрещено/);
 assert.throws(()=>saveEmployeeProfile(initialEmployees,initialRoles,{...initialEmployees[1],salary:-1},actor,date),/неотрицательный/);
 const saved=saveEmployeeProfile(initialEmployees,initialRoles,{...initialEmployees[0],role:'cashier'},actor,date);
 assert.equal(saved[0].role,'owner');
 assert.throws(()=>changeEmployeeStatus(initialEmployees,'owner-user','Заблокирован',actor,date),/Нельзя/);
 const dismissed=changeEmployeeStatus(initialEmployees,'aiym','Уволен',actor,date);
 assert.equal(dismissed[1].status,'Уволен');
 assert.match(dismissed[1].profileHistory[0].action,/Уволен/);
 assert.throws(()=>changeEmployeeStatus(dismissed,'aiym','Активен',actor,date),/не восстанавливается/);
 assert.equal(initialEmployees[1].status,'Активен');
});
