import {test} from 'node:test';
import assert from 'node:assert/strict';
import {proposeWorkflowChange} from '../lib/os/workflow-assistant.ts';
const graph={nodes:[{id:'t',type:'agent',position:{x:0,y:0},data:{kind:'Trigger',label:'Старт',source:'Все'}},{id:'c',type:'agent',position:{x:300,y:0},data:{kind:'CRM',label:'CRM',action:'move',stage:'Первичный контакт'}}],edges:[{id:'tc',source:'t',target:'c'}]};
const stages=['Первичный контакт','Оплата'];let index=0;const id=()=>String(++index);
test('proposal leaves original untouched and generates valid connected additions',()=>{const original=structuredClone(graph);const result=proposeWorkflowChange(graph,'Проверь остатки и добавь подтверждение сотрудника',stages,id);assert.deepEqual(graph,original);assert.equal(result.graph.nodes.length,4);assert.equal(result.graph.edges.length,3);assert.equal(result.graph.nodes[2].data.tool,'get_inventory');assert.equal(result.graph.nodes[3].data.kind,'Human Approval')});
test('edits existing stage and message with exact requested values',()=>{const result=proposeWorkflowChange(graph,'Перенеси на этап Оплата. Сообщение: «Спасибо, {{имя}}!»',stages,id);assert.equal(result.graph.nodes[1].data.stage,'Оплата');assert.equal(result.graph.nodes[2].data.template,'Спасибо, {{имя}}!')});
test('unknown requests and ambiguous insertion fail without mutating graph',()=>{assert.throws(()=>proposeWorkflowChange(graph,'Настрой всю компанию',stages,id),/не понял/);const branched={nodes:[...graph.nodes,{id:'o',type:'agent',position:{x:0,y:100},data:{kind:'Output',label:'Конец'}}],edges:graph.edges};assert.throws(()=>proposeWorkflowChange(branched,'Проверь остатки',stages,id),/несколько концов/);assert.equal(branched.nodes.length,3)});
test('new scenario and delay normalize without silently executing',()=>{const result=proposeWorkflowChange(graph,'Создай сценарий с нуля только Telegram. Задержка 2 часа',stages,id);assert.equal(result.graph.nodes[0].data.source,'Telegram');assert.equal(result.graph.nodes[1].data.minutes,120);assert.equal(graph.nodes[0].data.source,'Все')});
