export type SettingField={key:string;label:string;type?:'text'|'number'|'textarea'|'select'|'toggle'|'time'|'choices'|'list';value:string|number|boolean;options?:string[];hint?:string;min?:number;max?:number};
export type SettingSection={name:string;description:string;fields:SettingField[]};
const text=(key:string,label:string,value='',hint?:string):SettingField=>({key,label,value,hint});
const toggle=(key:string,label:string,value=true,hint?:string):SettingField=>({key,label,value,type:'toggle',hint});
const select=(key:string,label:string,options:string[]):SettingField=>({key,label,value:options[0],type:'select',options});
const number=(key:string,label:string,value:number,min=0,max=1000000):SettingField=>({key,label,value,type:'number',min,max});
const list=(key:string,label:string,value:string,options:string[]):SettingField=>({key,label,value,type:'list',options});
const area=(key:string,label:string,value=''):SettingField=>({key,label,value,type:'textarea'});
export const settingsCatalog:SettingSection[]=[
 {name:'Компания',description:'Реквизиты, контакты и рабочее время бизнеса.',fields:[text('company','Название компании','DemiResults'),text('legal','Юридическое название'),text('tax','ИНН'),text('phone','Телефон','+996'),text('email','Рабочий email'),text('address','Адрес'),text('website','Сайт'),select('currency','Основная валюта',['KGS','USD','EUR','KZT','RUB']),select('timezone','Часовой пояс',['Asia/Bishkek','Asia/Almaty','Europe/Moscow','UTC']),select('language','Язык',['Русский','Кыргызча','English']),select('workdays','Рабочие дни',['Пн–Сб','Пн–Пт','Ежедневно']),{key:'open',label:'Начало работы',type:'time',value:'09:00'},{key:'close',label:'Конец работы',type:'time',value:'20:00'}]},
 {name:'Филиалы и склады',description:'Точки продаж, склады и правила распределения.',fields:[select('defaultBranch','Основной филиал',['Бишкек','Онлайн-магазин']),select('defaultWarehouse','Основной склад',['Основной склад','Резервный склад']),list('branches','Филиалы','Бишкек\nОнлайн-магазин',['Бишкек','Онлайн-магазин','Ош']),list('warehouses','Склады','Основной склад\nРезервный склад',['Основной склад','Резервный склад','Склад магазина']),toggle('crossBranch','Продажи между филиалами'),toggle('stockBranch','Показывать остатки всех филиалов'),toggle('reserveWarehouse','Автоматический выбор склада')]},
 {name:'CRM и воронки',description:'Сделки, источники, поля и автоматические правила.',fields:[area('stages','Этапы воронки','Неразобранное\nПервичный контакт\nКвалификация\nПредложение\nОплата'),area('repeatStages','Этапы повторных продаж','Новый интерес\nПодбор\nОплата'),{key:'customFields',label:'Пользовательские поля',type:'choices',value:'Тип кожи\nТелефон\nГород\nИсточник',options:['Тип кожи','Телефон','Город','Источник','Email','Адрес','Дата рождения','Компания']},select('assignment','Распределять лиды',['По очереди','По загрузке','Вручную']),number('leadSla','Ответить на лид за, минут',10,1,1440),toggle('duplicates','Предупреждать о дублях'),toggle('requiredPhone','Телефон обязателен'),toggle('dealHistory','Сохранять историю этапов'),toggle('autoDeal','Создавать сделку из нового диалога'),toggle('closedReadonly','Защищать закрытые сделки от изменений')]},
 {name:'Диалоги',description:'Назначение операторов, AI и качество обслуживания.',fields:[select('inboxMode','Режим ответа',['AI с подтверждением','AI автоматически','Только человек']),number('handoff','Передавать человеку через, минут',10,1,120),toggle('readReceipts','Отмечать сообщения прочитанными'),toggle('typing','Показывать статус набора'),toggle('voice','Голосовые сообщения'),toggle('attachments','Принимать вложения'),number('attachmentLimit','Максимальный размер вложения, МБ',20,1,100),toggle('stopOnHuman','Останавливать AI после ответа сотрудника'),area('greeting','Приветствие','Здравствуйте! Чем можем помочь?'),area('afterHours','Ответ вне рабочего времени','Мы ответим в ближайшее рабочее время.')]},
 {name:'Товары и остатки',description:'Каталог, себестоимость, резервы и складские ограничения.',fields:[select('costMethod','Расчёт себестоимости',['Средневзвешенный','FIFO']),text('skuPrefix','Префикс артикула','SKU-'),number('lowStock','Минимальный остаток',5),toggle('negativeStock','Разрешить отрицательный остаток',false),toggle('reserveOnOrder','Резервировать при создании заказа'),number('reserveHours','Срок резерва, часов',24,1,720),toggle('barcodeUnique','Уникальные штрихкоды'),toggle('batches','Учёт партий'),toggle('expiry','Сроки годности'),toggle('services','Услуги в каталоге'),select('units','Единица по умолчанию',['шт.','мл','г','кг']),toggle('confirmPost','Подтверждать проведение документов')]},
 {name:'Касса и продажи',description:'Чеки, оплаты, скидки и закрытие смен.',fields:[{key:'paymentMethods',label:'Способы оплаты',type:'choices',value:'Наличные\nКарта\nQR',options:['Наличные','Карта','QR','Банковский перевод','Рассрочка']},toggle('splitPayment','Разделённая оплата'),number('maxDiscount','Максимальная скидка кассира, %',10,0,100),toggle('shiftRequired','Открытая смена обязательна'),toggle('refundApproval','Подтверждение возвратов менеджером'),toggle('printReceipt','Предлагать печать чека'),text('receiptHeader','Заголовок чека','DemiResults'),area('receiptFooter','Текст внизу чека','Спасибо за покупку!'),number('taxRate','Ставка налога, %',0,0,100),toggle('cashDifference','Контролировать расхождение кассы')]},
 {name:'Команда и зарплаты',description:'KPI, начисления, графики и ответственность.',fields:[list('departments','Отделы','Продажи\nКонсультации\nОперации',['Продажи','Консультации','Операции','Маркетинг','Склад','Финансы']),number('baseSalary','Оклад по умолчанию, сом',25000),number('salesBonus','Бонус от продаж, %',3,0,100),number('salaryDay','День выплаты',5,1,31),toggle('kpiBonus','Учитывать выполнение KPI'),toggle('attendance','Учёт рабочего времени'),toggle('managerReview','Проверка начислений руководителем'),number('consultationBonus','Бонус за консультацию, сом',100),select('workingWeek','Рабочая неделя',['6/1','5/2','2/2','Индивидуальная'])]},
 {name:'Роли и права',description:'Настройки фронтенд-модели доступа; реальные права будет проверять сервер.',fields:[area('roles','Роли','Владелец\nАдминистратор\nМенеджер\nКассир\nКонсультант'),select('newRole','Роль нового сотрудника',['Менеджер','Кассир','Консультант']),toggle('seeFinance','Менеджер видит финансы',false),toggle('editPrices','Кассир может менять цены',false),toggle('deleteDeals','Удаление сделок менеджером',false),toggle('exportData','Экспорт данных сотрудниками',false),toggle('viewAllChats','Сотрудник видит все диалоги',false),toggle('inventoryPost','Менеджер проводит складские документы'),toggle('approvalMoney','Подтверждение финансовых действий AI'),toggle('auditChanges','Журнал изменения прав')]},
 {name:'AI и модели',description:'Провайдер, поведение, лимиты и человеческий контроль.',fields:[select('provider','Провайдер',['OpenAI','Gemini','DeepSeek','Свой endpoint']),select('model','Модель',['Chat Model','Claude','Codex','Gemini','DeepSeek','Своя модель']),number('temperature','Температура',0.4,0,2),number('tokens','Максимум токенов ответа',4096,128,65536),number('budget','Дневной бюджет, сом',500),number('retries','Повторы при ошибке',2,0,10),area('systemPrompt','Системные инструкции','Помогай клиенту, проверяй наличие и передавай сложные вопросы человеку.'),toggle('memory','Использовать память клиента'),toggle('knowledge','Использовать базу знаний'),toggle('citations','Ссылки на источники'),toggle('approval','Подтверждать действия с деньгами'),toggle('pii','Скрывать персональные данные в логах')]},
 {name:'Автоматизации',description:'События, расписания, повторные попытки и контроль.',fields:[number('workflowConcurrent','Одновременных запусков',5,1,100),number('workflowTimeout','Таймаут, секунд',300,10,3600),number('workflowRetries','Количество повторов',3,0,10),number('retryDelay','Пауза между повторами, секунд',30,1,3600),number('followupHours','Follow-up через, часов',24,1,720),toggle('quietHours','Учитывать тихие часы'),toggle('deduplicate','Защита от повторных событий'),toggle('executionLog','Сохранять каждый шаг'),toggle('failureNotify','Уведомлять об ошибках'),toggle('dryRun','Пробный запуск перед публикацией')]},
 {name:'База знаний',description:'Загрузка, индексация и актуальность документов.',fields:[select('searchMode','Режим поиска',['Гибридный','По ключевым словам','Семантический']),number('chunkSize','Размер фрагмента',800,100,4000),number('overlap','Перекрытие фрагментов',100,0,500),number('sources','Максимум источников в ответе',5,1,20),toggle('autoIndex','Индексировать после загрузки'),toggle('documentVersions','История версий'),toggle('sourceAccess','Учитывать права документа'),{key:'fileTypes',label:'Разрешённые форматы',type:'choices',value:'PDF\nDOCX\nTXT\nCSV',options:['PDF','DOCX','TXT','CSV','XLSX','PNG','JPG','MD']},number('documentSize','Лимит документа, МБ',25,1,100)]},
 {name:'Финансы',description:'Счета, категории и правила финансовой отчётности.',fields:[list('accounts','Счета','Касса\nБанк\nQR',['Касса','Банк','QR','Расчётный счёт']),list('expenseCategories','Категории расходов','Закупки\nАренда\nЗарплаты\nAI\nМаркетинг',['Закупки','Аренда','Зарплаты','AI','Маркетинг','Доставка','Налоги','Прочее']),select('accounting','Метод отчётности',['По оплате','По начислению']),toggle('includeRefunds','Учитывать возвраты'),toggle('approvalExpense','Подтверждение расходов'),number('expenseLimit','Расход без подтверждения, сом',1000),number('closingDay','День закрытия месяца',5,1,28)]},
 {name:'Маркетинг',description:'Атрибуция, кампании и согласие на сообщения.',fields:[select('attribution','Атрибуция',['Последний контакт','Первый контакт','Линейная']),number('attributionWindow','Окно атрибуции, дней',30,1,365),select('utmSource','Источник UTM по умолчанию',['instagram','telegram','whatsapp','google','facebook','website','offline']),toggle('consent','Проверять согласие на рассылку'),toggle('unsubscribe','Ссылка на отписку'),number('dailyMessages','Лимит рассылки в день',100,1,10000),number('frequency','Интервал между кампаниями, дней',7,1,90),toggle('campaignCosts','Учитывать расходы кампаний')]},
 {name:'Аналитика',description:'Периоды, цели, сравнение и метрики.',fields:[select('period','Период по умолчанию',['Последние 14 дней','Последние 7 дней','Этот месяц']),select('weekStart','Начало недели',['Понедельник','Воскресенье']),number('revenueGoal','План выручки, сом',1000000),number('conversionGoal','План конверсии, %',30,1,100),number('averageCheckGoal','План среднего чека, сом',5000),toggle('comparePrevious','Сравнивать с предыдущим периодом'),toggle('excludeTest','Исключать тестовые записи'),toggle('aiCosts','Показывать расходы AI'),toggle('autoReports','Автоматические отчёты')]},
 {name:'Уведомления',description:'Каналы, события и тихие часы.',fields:[toggle('notifyLead','Новый лид'),toggle('notifyAssigned','Назначенная задача'),toggle('notifyStock','Низкий остаток'),toggle('notifyPayment','Оплата и возврат'),toggle('notifyAI','AI требует подтверждения'),toggle('notifyServer','Проблемы сервера'),toggle('notifyEmail','Email',false),toggle('notifyTelegram','Telegram'),toggle('notifyBrowser','Внутри приложения'),{key:'quietStart',label:'Тихие часы с',type:'time',value:'22:00'},{key:'quietEnd',label:'Тихие часы до',type:'time',value:'09:00'},select('digest','Сводка',['Ежедневно','Еженедельно','Не отправлять'])]},
 {name:'Сервер и мониторинг',description:'Пороги предупреждений и параметры сбора метрик.',fields:[text('serverName','Название сервера','DemiResults production'),number('refreshSeconds','Обновлять каждые, секунд',30,5,600),number('cpuAlert','Порог CPU, %',80,1,100),number('ramAlert','Порог RAM, %',85,1,100),number('diskAlert','Порог диска, %',90,1,100),number('responseAlert','Порог ответа API, мс',1000,50,10000),number('logDays','Хранить логи, дней',30,1,365),toggle('watchdog','Watchdog'),toggle('backupAlerts','Оповещения о бэкапах'),toggle('sslAlerts','Следить за SSL'),select('backupSchedule','Расписание резервирования',['Ежедневно в 03:00','Каждые 6 часов','Каждые 12 часов','Еженедельно в воскресенье','Вручную'])]},
 {name:'API и разработчик',description:'Локальная конфигурация будущего API и событий.',fields:[text('apiBase','Адрес API','/api'),number('apiTimeout','Таймаут запросов, секунд',30,1,120),number('apiLimit','Запросов в минуту',120,1,10000),toggle('apiAudit','Журнал запросов'),toggle('webhookSignatures','Проверка подписей webhook'),toggle('sandbox','Тестовый режим'),list('allowedOrigins','Разрешённые адреса','http://localhost:5173',['http://localhost:5173','http://localhost:5174','http://localhost:5175']),{key:'eventTypes',label:'События webhook',type:'choices',value:'lead.created\norder.paid\nstock.low\nmessage.received',options:['lead.created','order.paid','stock.low','message.received']}]},
 {name:'Данные и приватность',description:'Сроки хранения, экспорт и локальная конфигурация.',fields:[number('historyDays','История диалогов, дней',365,1,3650),number('auditDays','Журнал действий, дней',180,1,3650),toggle('maskPhone','Маскировать телефоны'),toggle('maskEmail','Маскировать email'),toggle('exportConsent','Подтверждать экспорт'),toggle('anonymousAnalytics','Обезличенная аналитика',false),toggle('backupConfig','Резервировать настройки')]}
];
export const settingDefaults=Object.fromEntries(settingsCatalog.flatMap(s=>s.fields.map(f=>[f.key,f.value]))) as Record<string,string|number|boolean>;
