'use client';
import {useState,type PointerEvent} from 'react';
import {Modal} from '../../components/os/ui';
function toHSV(hex:string){const rgb=hex.match(/[a-f\d]{2}/gi)!.map(x=>parseInt(x,16)/255);const [r,g,b]=rgb;const max=Math.max(...rgb),min=Math.min(...rgb),d=max-min;let h=d===0?0:max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;h=(h*60+360)%360;return {h,s:max?d/max:0,v:max}}
export function hsvHex(h:number,s:number,v:number){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;const rgb=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('')}
export default function ColorPicker({value,label,onChange,close}:{value:string;label:string;onChange:(s:string)=>void;close:()=>void}){
 const [hsv,setHSV]=useState(()=>toHSV(value));const [hex,setHex]=useState(value);const color=hsvHex(hsv.h,hsv.s,hsv.v);const rgb=color.match(/[a-f\d]{2}/gi)!.map(x=>parseInt(x,16));
 const update=(next:typeof hsv)=>{setHSV(next);setHex(hsvHex(next.h,next.s,next.v))};
 const point=(e:PointerEvent<HTMLDivElement>)=>{if(e.type==='pointermove'&&e.buttons!==1)return;const r=e.currentTarget.getBoundingClientRect();update({...hsv,s:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v:1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))})};
 return <Modal title={'Выбрать цвет · '+label} close={close}><div className="color-square" role="slider" tabIndex={0} aria-label="Насыщенность и яркость" aria-valuenow={Math.round(hsv.s*100)} aria-valuemin={0} aria-valuemax={100} aria-valuetext={`Насыщенность ${Math.round(hsv.s*100)}%, яркость ${Math.round(hsv.v*100)}%`} style={{backgroundColor:`hsl(${hsv.h} 100% 50%)`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);point(e)}} onPointerMove={point} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();update({...hsv,s:Math.max(0,Math.min(1,hsv.s+(e.key==='ArrowRight'?.02:e.key==='ArrowLeft'?-.02:0))),v:Math.max(0,Math.min(1,hsv.v+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)))})}}}><span style={{left:hsv.s*100+'%',top:(1-hsv.v)*100+'%',background:color}}/></div><label>Цветовой тон<input aria-label="Цветовой тон" className="hue-range" type="range" min={0} max={359} value={hsv.h} onChange={e=>update({...hsv,h:Number(e.target.value)})}/></label><div className="color-values"><i style={{background:color}}/><label>HEX<input value={hex} maxLength={7} onChange={e=>{const v=e.target.value;setHex(v);if(/^#[a-f\d]{6}$/i.test(v))setHSV(toHSV(v))}} onBlur={()=>{if(!/^#[a-f\d]{6}$/i.test(hex))setHex(color)}}/></label><label>RGB<input readOnly value={rgb.join(', ')}/></label></div><div className="form-grid"><label>Насыщенность<input type="range" min={0} max={100} value={hsv.s*100} onChange={e=>update({...hsv,s:Number(e.target.value)/100})}/></label><label>Яркость<input type="range" min={0} max={100} value={hsv.v*100} onChange={e=>update({...hsv,v:Number(e.target.value)/100})}/></label></div><div className="modal-footer"><button onClick={close}>Отмена</button><button className="primary" onClick={()=>{onChange(/^#[a-f\d]{6}$/i.test(hex)?hex.toLowerCase():color);close()}}>Применить цвет</button></div></Modal>
}
