import type {Entity} from './data.ts';
import type {InventoryState,Sale} from './inventory-model.ts';
import type {Employee} from './team.ts';
import {isStockTrackedProduct} from './product-options.ts';
export type PlanningSource='crm'|'sales'|'inventory'|'tasks'|'employees';
export const planningSources:Record<PlanningSource,string>={crm:'CRM и клиенты',sales:'Продажи кассы',inventory:'Товары и остатки',tasks:'Задачи',employees:'Сотрудники'};
export type PlanningAccess=Record<PlanningSource,boolean>;
export type PlanningPlan={revenue:number;check:number;conversion:number;days:number;adBudget:number;repeatRate:number;itemsPerSale:number;dailyCapacity:number};
export const defaultPlanningPlan:PlanningPlan={revenue:1000000,check:5000,conversion:30,days:26,adBudget:60000,repeatRate:0,itemsPerSale:1,dailyCapacity:20};
export type PlanningPeriod={start:string;end:string;baselineDays:number;employeeIds:string[];productIds:string[]};
export function defaultPlanningPeriod(now=new Date()):PlanningPeriod{const end=new Date(now);end.setUTCDate(end.getUTCDate()+29);return {start:now.toISOString().slice(0,10),end:end.toISOString().slice(0,10),baselineDays:30,employeeIds:[],productIds:[]}}
export function normalizePlanningPlan(value:Partial<PlanningPlan>):PlanningPlan{return {...defaultPlanningPlan,...value}}
function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(message)}
function validDay(date:string){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date))&&new Date(date).toISOString().slice(0,10)===date}
export function validatePlanning(plan:PlanningPlan,period:PlanningPeriod){
 decomposeGoal(plan.revenue,plan.check,plan.conversion,plan.days);assert(validDay(period.start)&&validDay(period.end),'Укажите даты периода.');const calendarDays=Math.round((Date.parse(period.end)-Date.parse(period.start))/86400000)+1;assert(calendarDays>0&&calendarDays<=366,'Период должен длиться от 1 до 366 дней.');assert(plan.days<=calendarDays&&Number.isInteger(plan.days),'Рабочих дней не может быть больше дней в периоде.');assert([7,30,90].includes(period.baselineDays),'Выберите период сравнения.');assert(Number.isFinite(plan.adBudget)&&plan.adBudget>=0&&Number.isFinite(plan.repeatRate)&&plan.repeatRate>=0&&plan.repeatRate<100&&Number.isFinite(plan.itemsPerSale)&&plan.itemsPerSale>0&&Number.isFinite(plan.dailyCapacity)&&plan.dailyCapacity>0,'Проверьте бюджет, повторные покупки, товары в чеке и нагрузку.');return calendarDays;
}
export function planningBaseline(sales:Sale[],deals:Entity[],days=30,now=new Date()){
 const end=now.getTime(),start=end-days*86400000;
 const period=sales.filter(sale=>{const date=Date.parse(sale.date);return date>=start&&date<=end&&Number.isFinite(sale.total)&&Number.isFinite(sale.refunds)&&sale.total>sale.refunds});
 const revenue=period.reduce((sum,sale)=>sum+sale.total-sale.refunds,0),cohort=deals.filter(deal=>{const date=Date.parse(deal.createdAt||'');return date>=start&&date<=end});
 const cohortIds=new Set(cohort.map(deal=>deal.customerId||deal.id).filter(Boolean)),allBuyers=new Set(period.map(sale=>sale.customerId).filter(Boolean));
 const converted=[...cohortIds].filter(id=>{const firstLead=Math.min(...cohort.filter(deal=>(deal.customerId||deal.id)===id).map(deal=>Date.parse(deal.createdAt!)));return period.some(sale=>sale.customerId===id&&Date.parse(sale.date)>=firstLead)}).length;
 return {days,revenue,sales:period.length,averageCheck:period.length?revenue/period.length:0,leads:cohort.length,cohortCustomers:cohortIds.size,converted,customers:allBuyers.size,unlinkedSales:period.filter(sale=>!sale.customerId).length,conversion:cohortIds.size?converted/cohortIds.size*100:0};
}
export function decomposeGoal(goal:number,averageCheck:number,conversion:number,days:number){
 if(![goal,averageCheck,conversion,days].every(Number.isFinite)||goal<=0||averageCheck<=0||conversion<=0||conversion>100||days<=0||days>366)throw new Error('Проверьте выручку, средний чек, конверсию и число дней.');
 const sales=Math.ceil(goal/averageCheck),leads=Math.ceil(sales/(conversion/100));
 return {sales,leads,dailyLeads:Math.ceil(leads/days),dailyRevenue:goal/days};
}
export type PlanningData={sales:Sale[];deals:Entity[];inventory:InventoryState;tasks:Entity[];employees:Employee[]};
export function scopePlanningData(data:PlanningData,access:PlanningAccess):PlanningData{return {sales:access.sales?data.sales:[],deals:access.crm?data.deals:[],inventory:access.inventory?{...data.inventory,sales:[],shifts:[]}:{products:[],warehouses:[],documents:[],sales:[],shifts:[]},tasks:access.tasks?data.tasks:[],employees:access.employees?data.employees:[]}}
export function planningForecast(plan:PlanningPlan,period:PlanningPeriod,data:PlanningData,access:PlanningAccess,now=new Date()){
 const calendarDays=validatePlanning(plan,period),scoped=scopePlanningData(data,access),baseline=planningBaseline(scoped.sales,scoped.deals,period.baselineDays,now),volumes=decomposeGoal(plan.revenue,plan.check,plan.conversion,plan.days);
 const customers=Math.ceil(volumes.sales*(1-plan.repeatRate/100)),leads=Math.ceil(customers/(plan.conversion/100)),dailyLeads=Math.ceil(leads/plan.days),neededEmployees=Math.ceil(dailyLeads/plan.dailyCapacity);
 const employees=scoped.employees.filter(employee=>employee.status==='Активен'&&(!period.employeeIds.length||period.employeeIds.includes(employee.id)));
 const pace=access.sales&&baseline.sales?baseline.revenue/period.baselineDays*calendarDays:null,gap=pace===null?null:Math.max(0,plan.revenue-pace);
 const products=scoped.inventory.products.filter(product=>!product.deleted&&(!period.productIds.length||period.productIds.includes(product.id))),units=Math.ceil(volumes.sales*plan.itemsPerSale);
 const weighted=products.map(product=>{const sold=scoped.sales.filter(sale=>Date.parse(sale.date)>=now.getTime()-period.baselineDays*86400000&&Date.parse(sale.date)<=now.getTime()).flatMap(sale=>sale.items).filter(item=>item.productId===product.id).reduce((sum,item)=>sum+Math.max(0,item.quantity-item.returned),0);return {product,sold}}),soldTotal=weighted.reduce((sum,item)=>sum+item.sold,0);
 const rawAllocations=weighted.map(item=>units*(soldTotal?item.sold/soldTotal:1/Math.max(products.length,1))),allocations=rawAllocations.map(Math.floor);let left=units-allocations.reduce((sum,value)=>sum+value,0);rawAllocations.map((value,index)=>({index,fraction:value-Math.floor(value)})).sort((a,b)=>b.fraction-a.fraction).forEach(item=>{if(left>0){allocations[item.index]++;left--}});
 const productPlan=weighted.map(({product,sold},index)=>{const tracked=isStockTrackedProduct(product),stock=Object.values(product.stocks).reduce((sum,qty)=>sum+qty,0),required=allocations[index];return {id:product.id,name:product.name,sold,stock:tracked?stock:null,required,shortage:tracked?Math.max(0,required-stock):0}});
 const employeePlan=employees.map(employee=>({id:employee.id,name:employee.name,revenue:plan.revenue/employees.length,leads:Math.ceil(leads/employees.length),sales:Math.ceil(volumes.sales/employees.length)}));
 return {baseline,calendarDays,sales:volumes.sales,customers,leads,dailyLeads,dailyRevenue:plan.revenue/plan.days,units,neededEmployees,assignedEmployees:employees.length,pace,gap,growth:pace&&pace>0?plan.revenue/pace:null,productPlan,productBasis:soldTotal?'Фактическая доля проданных единиц за период':'Равные доли: продаж по выбранным товарам пока нет',employeePlan,cac:plan.adBudget/customers,assumptions:['Касса — источник фактической выручки; суммы CRM не прибавляются к чекам.','Возвраты вычтены из чеков исходной покупки; это оценка продаж, а не движение денег по дате возврата.','Плановые клиенты = продажи × (1 − доля повторных продаж). Конверсия относится к новым покупающим клиентам.','Прогноз темпа линейный по календарным дням; сезонность и будущие изменения спроса не учтены.','План сотрудников распределён поровну и округлён вверх для ориентира; штатная потребность основана на заданной нагрузке.']};
}
export type OpportunityStatus='Идея'|'В работе'|'Проверено'|'Отложено';
export type Opportunity={id:string;title:string;action:string;status:OpportunityStatus;category:'Продажи'|'Товары'|'Команда'|'Процессы';priority:'Высокий'|'Средний'|'Низкий';ownerId:string;due:string;metric:string;target:number|null;result:string;source:'manual'|'local-analysis';evidence:string;sources:PlanningSource[];createdAt:string;updatedAt:string};
export function normalizeOpportunities(rows:Partial<Opportunity>[]):Opportunity[]{return rows.filter(row=>typeof row.id==='string'&&typeof row.title==='string').map(row=>({id:row.id!,title:row.title!,action:row.action||'',status:row.status||'Идея',category:row.category||'Продажи',priority:row.priority||'Средний',ownerId:row.ownerId||'',due:row.due||'',metric:row.metric||'',target:typeof row.target==='number'?row.target:null,result:row.result||'',source:row.source||'manual',evidence:row.evidence||'',sources:Array.isArray(row.sources)?row.sources.filter(source=>source in planningSources):[],createdAt:row.createdAt||'',updatedAt:row.updatedAt||''}))}
export function saveOpportunity(rows:Opportunity[],input:Opportunity,canEdit:boolean,canCreate:boolean){const existing=rows.find(row=>row.id===input.id);assert(existing?canEdit:canCreate,'Изменение карты запрещено ролью.');assert(input.title.trim()&&input.action.trim(),'Укажите гипотезу и конкретное действие.');assert(input.title.length<=160&&input.action.length<=4000&&input.result.length<=4000,'Сократите текст возможности.');assert(['Идея','В работе','Проверено','Отложено'].includes(input.status)&&['Продажи','Товары','Команда','Процессы'].includes(input.category)&&['Высокий','Средний','Низкий'].includes(input.priority),'Выберите статус, категорию и приоритет.');assert(!input.due||validDay(input.due),'Проверьте срок.');assert(input.target===null||Number.isFinite(input.target)&&input.target>=0,'Цель показателя должна быть неотрицательной.');assert(input.sources.every(source=>source in planningSources),'Неизвестный источник.');const saved={...input,title:input.title.trim(),action:input.action.trim()};return existing?rows.map(row=>row.id===saved.id?saved:row):[...rows,saved]}
export function removeOpportunity(rows:Opportunity[],id:string,canRemove:boolean){assert(canRemove,'Удаление запрещено ролью.');return rows.filter(row=>row.id!==id)}
export type PlanningAgent={enabled:boolean;prompt:string;model:string;frequency:'manual'|'daily'|'weekly';time:string;weekday:number;sources:PlanningSource[];permissions:('read'|'propose')[]};
export const defaultPlanningAgent:PlanningAgent={enabled:true,prompt:'Найди измеримые возможности роста. Используй только доступные локальные источники. Покажи факты, допущения и одно проверяемое действие для каждой гипотезы.',model:'Локальные правила',frequency:'manual',time:'09:00',weekday:1,sources:['crm','sales','inventory','tasks','employees'],permissions:['read','propose']};
export function decodePlanningAgent(settings:Record<string,string>|undefined):PlanningAgent{
 if(!settings)return structuredClone(defaultPlanningAgent);
 const parse=(text:string|undefined,fallback:unknown)=>{try{return text?JSON.parse(text):fallback}catch{return fallback}};
 const rawSchedule=parse(settings.schedule,{}),schedule=rawSchedule&&typeof rawSchedule==='object'?rawSchedule as {time?:string;weekday?:number}:{};
 const rawSources=parse(settings.entities,defaultPlanningAgent.sources),rawPermissions=parse(settings.storePermissions,['read','propose']);
 return {enabled:settings.status!=='disabled',prompt:settings.prompt??defaultPlanningAgent.prompt,model:settings.model||'Локальные правила',frequency:['daily','weekly'].includes(settings.frequency)?settings.frequency as PlanningAgent['frequency']:'manual',time:typeof schedule.time==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(schedule.time)?schedule.time:'09:00',weekday:typeof schedule.weekday==='number'&&schedule.weekday>=1&&schedule.weekday<=7?schedule.weekday:1,sources:Array.isArray(rawSources)?rawSources.filter(source=>Object.hasOwn(planningSources,source)):[],permissions:Array.isArray(rawPermissions)?rawPermissions.filter(permission=>['read','propose'].includes(permission)):[]};
}
export function encodePlanningAgent(agent:PlanningAgent,canConfigure:boolean,access:PlanningAccess):Record<string,string>{assert(canConfigure,'Настройка агента запрещена ролью.');assert(agent.prompt.trim()&&agent.prompt.length<=12000,'Укажите инструкции до 12 000 символов.');assert(['Локальные правила','OpenAI','Claude','OpenCode','Custom'].includes(agent.model),'Выберите модель.');assert(['manual','daily','weekly'].includes(agent.frequency)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(agent.time)&&Number.isInteger(agent.weekday)&&agent.weekday>=1&&agent.weekday<=7,'Проверьте расписание.');assert(agent.sources.every(source=>access[source]),'Один из источников недоступен вашей роли.');assert(agent.permissions.every(permission=>['read','propose'].includes(permission)),'Неизвестное разрешение агента.');return {status:agent.enabled?'enabled':'disabled',prompt:agent.prompt.trim(),model:agent.model,frequency:agent.frequency,schedule:JSON.stringify({time:agent.time,weekday:agent.weekday}),entities:JSON.stringify([...new Set(agent.sources)]),storePermissions:JSON.stringify([...new Set(agent.permissions)]),approval:'on'}}
export function generatePlanningOpportunities(plan:PlanningPlan,period:PlanningPeriod,data:PlanningData,access:PlanningAccess,agent:PlanningAgent,canRun:boolean,now=new Date()):Opportunity[]{
 assert(canRun,'Запуск анализа запрещён ролью.');assert(agent.enabled&&agent.permissions.includes('read')&&agent.permissions.includes('propose'),'Включите агента и разрешите чтение с подготовкой предложений.');assert(agent.model==='Локальные правила','Внешняя модель не подключена. Выберите локальные правила для доступного анализа.');const allowed=Object.fromEntries(Object.keys(planningSources).map(key=>[key,access[key as PlanningSource]&&agent.sources.includes(key as PlanningSource)])) as PlanningAccess;assert(Object.values(allowed).some(Boolean),'Выберите доступный источник данных.');const scoped=scopePlanningData(data,allowed),forecast=planningForecast(plan,period,scoped,allowed,now),at=now.toISOString(),rows:Opportunity[]=[];
 const add=(id:string,title:string,action:string,category:Opportunity['category'],metric:string,target:number,evidence:string,sources:PlanningSource[],priority:Opportunity['priority']='Средний')=>rows.push({id:'analysis:'+id,title,action,status:'Идея',category,priority,ownerId:'',due:period.end,metric,target,result:'',source:'local-analysis',evidence,sources,createdAt:at,updatedAt:at});
 if(allowed.sales&&forecast.gap!==null&&forecast.gap>0)add('revenue-gap','Закрыть разрыв плана выручки','Согласовать отдельный план '+Math.ceil(forecast.gap/plan.check)+' дополнительных продаж. Проверить результат по оплаченным чекам после возвратов.','Продажи','Дополнительная выручка',Math.round(forecast.gap),'Текущий линейный темп: '+Math.round(forecast.pace!)+' сом; цель: '+plan.revenue+' сом.',['sales'],'Высокий');
 if(allowed.crm){const opened=scoped.deals.filter(deal=>!['Успешно','Неуспешно'].includes(deal.pipeline||deal.status));if(opened.length)add('open-deals','Разобрать открытые сделки','Назначить следующий контакт и ответственного для каждой открытой сделки. Сумма карточек — потенциал, не подтверждённая выручка.','Продажи','Сделок с следующим шагом',opened.length,opened.length+' открытых сделок на сумму '+opened.reduce((sum,deal)=>sum+deal.value,0)+' сом.',['crm'],'Высокий');}
 if(allowed.inventory){const short=forecast.productPlan.filter(product=>product.shortage>0);if(short.length)add('stock-plan','Проверить запас под план продаж','Сверить плановые количества с закупками. Не оформлять пополнение до проверки спроса и бюджета.','Товары','Товаров с проверенным запасом',short.length,short.length+' позиций не покрывают расчётный план; распределение: '+forecast.productBasis+'.',['inventory',...(allowed.sales?['sales' as const]:[])],'Высокий');}
 if(allowed.tasks){const late=scoped.tasks.filter(task=>task.status!=='Done'&&task.nextTaskAt&&task.nextTaskAt.slice(0,10)<at.slice(0,10));if(late.length)add('overdue-tasks','Устранить просроченные задачи','Разобрать сроки, назначить ответственных и договориться о новых датах.','Процессы','Закрытых просроченных задач',late.length,late.length+' незавершённых задач с истёкшим сроком.',['tasks'],'Высокий');}
 if(allowed.employees&&forecast.assignedEmployees<forecast.neededEmployees)add('team-capacity','Проверить пропускную способность команды','Сравнить реальную нагрузку с плановой. Сначала проверить перераспределение и автоматизацию, затем потребность в найме.','Команда','Сотрудников в расчёте',forecast.neededEmployees,'В плане '+forecast.assignedEmployees+' сотрудников; нужно '+forecast.neededEmployees+' при допущении '+plan.dailyCapacity+' лидов в день на человека.',['employees']);
 if(!rows.length)add('data-baseline','Собрать базу для проверки плана','Проверить полноту выбранных источников и повторить анализ после новых операций. Отсутствие найденных проблем не доказывает достижимость цели.','Процессы','Дней наблюдения',period.baselineDays,'По доступным источникам нет подтверждённых узких мест либо недостаточно записей.',Object.keys(allowed).filter(key=>allowed[key as PlanningSource]) as PlanningSource[]);
 return rows;
}
export function opportunityTask(tasks:Entity[],opportunity:Opportunity,owner:Pick<Employee,'id'|'name'>|undefined,due:string,id:string,canCreate:boolean,canEditPlan:boolean):Entity[]{assert(canCreate&&canEditPlan,'Создание задачи запрещено ролью.');assert(!tasks.some(task=>task.planId==='planning-opportunity:'+opportunity.id),'У этой возможности уже есть связанная задача.');assert(owner,'Выберите сотрудника.');assert(validDay(due),'Укажите срок задачи.');const task:Entity={id,name:opportunity.title,value:0,status:'To Do',channel:opportunity.priority,owner:owner.name,employeeId:owner.id,note:opportunity.action+(opportunity.metric?' Критерий: '+opportunity.metric+(opportunity.target===null?'':' — '+opportunity.target):''),planId:'planning-opportunity:'+opportunity.id,nextTaskAt:due};return [task,...tasks]}
