import type {SettingsDocument} from './settings-document.ts';
export type EngineerFinding={id:string;area:string;status:'attention'|'configured'|'unknown';title:string;detail:string;recommendation:string};
export type EngineerReport={id:string;createdAt:string;incident:string;findings:EngineerFinding[];scope:'local-config'};
export function diagnoseServerConfiguration(document:SettingsDocument,incident:string,id:string,now:string,access:{integrations?:boolean;systemAI?:boolean}={}):EngineerReport{
 if(incident.length>2000)throw new Error('Описание должно быть короче 2000 символов.');
 const engineer=document.system.engineer as {endpoint:string;project:string;branch:string;mode:string;backup:boolean;tests:boolean;rollback:boolean};
 const watchdog=document.system.watchdog as {enabled:boolean;interval:number;attempts:number;telegram:boolean};
 const ai=document.system.ai as {enabled:boolean;endpoint:string;model:string;provider:string};
 const findings:EngineerFinding[]=[
  {id:'telemetry',area:'Инфраструктура',status:'unknown',title:'Телеметрия сервера не подключена',detail:'Состояние API, PostgreSQL, очереди, диска, HTTPS и последних бэкапов не проверялось.',recommendation:'Подключить read-only health/logs/metrics через серверный шлюз. Демонстрационные графики не являются диагностикой VPS.'},
  {id:'gateway',area:'Исполнитель',status:engineer.endpoint.trim()?'configured':'attention',title:engineer.endpoint.trim()?'Адрес шлюза задан':'Адрес шлюза не задан',detail:engineer.endpoint.trim()?'Наличие адреса в настройках не подтверждает связь или авторизацию.':'В конфигурации Server AI отсутствует endpoint.',recommendation:'Указать шлюз в параметрах инженера. Проверка соединения, секреты и вызов исполнителя потребуют backend.'},
  {id:'safeguards',area:'Изменения сервера',status:engineer.backup&&engineer.tests&&engineer.rollback&&engineer.mode==='diagnose'?'configured':'attention',title:'Режим и проверки перед изменением',detail:'Режим: '+engineer.mode+'. Бэкап: '+(engineer.backup?'включён':'выключен')+', тесты: '+(engineer.tests?'включены':'выключены')+', откат: '+(engineer.rollback?'включён':'выключен')+'.',recommendation:'Использовать диагностику до подключения исполнителя; сохранять бэкап, проверки и план отката. Можно подготовить локальное предложение ниже.'},
  {id:'project',area:'Проект',status:engineer.project.trim()&&engineer.branch.trim()?'configured':'attention',title:'Цель исполнителя',detail:'Путь и ветка '+(engineer.project.trim()&&engineer.branch.trim()?'заданы локально; наличие репозитория не проверялось.':'заполнены не полностью.'),recommendation:'Проверить путь, ветку и ограниченные права исполнителя на сервере перед запуском.'},
  {id:'watchdog',area:'Watchdog',status:watchdog.enabled?'configured':'attention',title:watchdog.enabled?'Watchdog включён в настройках':'Watchdog выключен в настройках',detail:`Интервал ${watchdog.interval} с; порог ${watchdog.attempts}. Фоновые проверки и Telegram-оповещения не подключены.`,recommendation:'Сохранить нужные параметры; на сервере подключить scheduler и канал уведомлений.'},
  {id:'system-ai',area:'System AI',status:ai.enabled?'configured':'attention',title:ai.enabled?'System AI включён в конфигурации':'System AI выключен в конфигурации',detail:ai.provider+' · '+(ai.model?'идентификатор модели задан':'модель по умолчанию')+'. Доступность модели и API не проверялась.',recommendation:'Параметры модели задаются в Settings → System AI. Ключ передавать будущему серверному хранилищу секретов.'},
 ];
 if(!access.systemAI)findings.splice(findings.findIndex(finding=>finding.id==='system-ai'),1);
 const channels=document.integrations.channels as Record<string,{enabled:boolean;events:string[];values:Record<string,string>}>;
 for(const [name,channel] of Object.entries(access.integrations?channels:{}).filter(([,channel])=>channel.enabled))findings.push({id:'channel-'+name,area:'Интеграции',status:channel.events.length?'unknown':'attention',title:name+' · '+(channel.events.length?'доставка событий не проверена':'события не выбраны'),detail:channel.events.length?`Выбрано событий: ${channel.events.length}. Реальных логов доставки в этом отчёте нет.`:'Интеграция включена локально без списка событий.',recommendation:channel.events.length?'Проверить webhook, авторизацию и журнал доставки на backend.':'Выбрать события в интеграции и подключить серверный канал.'});
 return {id,createdAt:now,incident:incident.trim(),findings,scope:'local-config'};
}
