import {dashboardBlocks,defaultDashboardLayout} from './dashboard-layout.ts';
import {z} from 'zod';
import defaults from '../../settings.json' with {type:'json'};
import {settingsCatalog,type SettingField} from '../../features/settings/catalog.ts';
import {parseExtensionsState,extensionPermissions,type ExtensionPermission} from './extensions.ts';
import {liveAnalyticsConfigSchema} from './live-analytics.ts';
import {systemTools} from './system-tools.ts';
import {navigation} from './data.ts';
import {hasAccess,teamActions,type Employee,type TeamRole} from './team.ts';

export const settingsDocumentKey='life-settings-document-v1';
export const settingsBranches=['system','appearance','crm','business','ai','agents','integrations','permissions','store','mcp'] as const;
export type SettingsBranch=typeof settingsBranches[number];
export type SettingsDocument={schemaVersion:1}&Record<SettingsBranch,Record<string,unknown>>;
export type SettingsStorage=Pick<Storage,'getItem'|'setItem'|'removeItem'>;
export const settingsBranchLabels:Record<SettingsBranch,string>={system:'Система',appearance:'Внешний вид',crm:'CRM и диалоги',business:'Правила компании',ai:'ИИ и автоматизации',agents:'Агенты и сценарии',integrations:'Интеграции',permissions:'Роли и права',store:'Store и витрина',mcp:'MCP Business OS'};
export const settingsSectionPaths:Record<string,[SettingsBranch,string]>={'Компания':['business','company'],'Филиалы и склады':['business','locations'],'CRM и воронки':['crm','settings'],'Диалоги':['crm','conversations'],'Товары и остатки':['business','inventory'],'Касса и продажи':['business','checkout'],'Команда и зарплаты':['business','team'],'Роли и права':['permissions','policy'],'AI и модели':['ai','models'],'Автоматизации':['ai','automations'],'База знаний':['ai','knowledge'],'Финансы':['business','finance'],'Маркетинг':['business','marketing'],'Аналитика':['business','analytics'],'Уведомления':['system','notifications'],'Сервер и мониторинг':['system','server'],'API и разработчик':['system','developer'],'Данные и приватность':['system','privacy']};
export const settingsAliases:Record<string,[SettingsBranch,string]>={'dashboard-layout-v1':['appearance','dashboardLayout'],theme:['appearance','theme'],accent:['appearance','accent'],collapsed:['appearance','collapsed'],'appearance-v2':['appearance','preferences'],'notification-colors':['appearance','notificationColors'],'calendar-view':['appearance','calendarView'],'documents-view-v1':['appearance','documentView'],'analytics-active-board':['appearance','analyticsBoard'],'analytics-compare':['appearance','analyticsCompare'],'stage-config-v3':['crm','stages'],'stage-agent-policies-v1':['crm','stageAgentPolicies'],'reply-templates-v1':['crm','replyTemplates'],'bot-config-v2':['ai','bot'],'bot-policy-v1':['ai','policy'],'reply-assistant-prompt-v1':['ai','replyAssistantPrompt'],agents:['agents','definitions'],'agent-settings':['agents','settings'],nodes:['agents','nodes'],edges:['agents','edges'],'workflow-library-v1':['agents','library'],'workflow-published-v1':['agents','published'],'team-roles-v3':['permissions','roles'],'channel-config-v2':['integrations','channels'],'server-ai-v3':['system','engineer'],'server-watchdog-v2':['system','watchdog'],'system-ai-v1':['system','ai'],'analytics-boards-v2':['business','analyticsBoards'],'analytics-live-v1':['business','liveAnalytics'],'analytics-custom-metrics-v1':['business','customMetrics'],'os-config':['business','blueprint'],'storefront-v2':['store','catalog'],'billing-plan-v2':['store','billingPlan'],'extension-store-v1':['store','extensions'],'mcp-settings-v1':['mcp','connection']};
const specialAliases=['settings-deep-v2','workspace','inventory-company-v3'];
export function isSettingsAlias(key:string){return Object.hasOwn(settingsAliases,key)||specialAliases.includes(key)}
const text=z.string().max(100_000),short=z.string().max(300),id=short.min(1),number=z.number().finite(),strings=z.array(short).max(1000),color=z.string().regex(/^#[0-9a-f]{6}$/i);
const object=(shape:z.ZodRawShape)=>z.object(shape).strict();
const record=(schema:z.ZodTypeAny)=>z.record(id,schema);
const unique=<T extends {id:string}>(rows:T[])=>new Set(rows.map(row=>row.id)).size===rows.length;
const array=(schema:z.ZodTypeAny)=>z.array(schema).max(2000);
const optionalFields=(names:string[])=>Object.fromEntries(names.map(name=>[name,text.optional()]));
const primitive=z.union([text,number,z.boolean(),z.null()]);
const toolName=z.enum(systemTools.map(tool=>tool.name) as [string,...string[]]);
function catalogField(field:SettingField):z.ZodTypeAny{
 if(typeof field.value==='boolean')return z.boolean();
 if(typeof field.value==='number')return number.min(field.min??0).max(field.max??1_000_000);
 if(field.type==='time')return z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
 if(field.type==='select'&&field.options&&!['defaultBranch','defaultWarehouse','newRole'].includes(field.key))return z.enum(field.options as [string,...string[]]);
 return text;
}
const branchShapes=Object.fromEntries(settingsBranches.map(branch=>[branch,{}])) as Record<SettingsBranch,z.ZodRawShape>;
for(const section of settingsCatalog){const [branch,slot]=settingsSectionPaths[section.name];branchShapes[branch][slot]=object(Object.fromEntries(section.fields.filter(field=>!['stages','repeatStages','roles'].includes(field.key)).map(field=>[field.key,catalogField(field)])));}
branchShapes.business.company=(branchShapes.business.company as z.AnyZodObject).extend({director:text}).strict();
const palette=object(Object.fromEntries(['bg','panel','sidebar','hover','border','text','muted','accent'].map(key=>[key,color])));
Object.assign(branchShapes.appearance,{dashboardLayout:z.array(object({id:z.enum(Object.keys(dashboardBlocks) as [string,...string[]]),visible:z.boolean()})).length(6).refine(rows=>new Set(rows.map(row=>row.id)).size===6).default(defaultDashboardLayout),theme:z.enum(['Dark','Light','System']),accent:z.enum(['Blue','Violet','Purple','Emerald','Orange','Rose','Neutral']),collapsed:z.boolean(),preferences:object({custom:z.boolean(),palettes:object({dark:palette,light:palette}),density:z.enum(['comfortable','compact']),fontFamily:z.enum(['system','humanist','classic']).default('system'),fontSize:number.min(12).max(18),radius:number.min(0).max(18),motion:z.boolean(),lowPower:z.boolean()}),notificationColors:record(color),calendarView:z.enum(['Месяц','Неделя','Список']),documentView:z.enum(['list','grid']),analyticsBoard:short,analyticsCompare:z.boolean()});
const stage=object({id,name:id,color});
const agentPolicy=object({agentId:short,fallbackAgentId:short,urgentAgentId:short,unansweredAgentId:short,unansweredMinutes:number.min(1).max(1440)});
Object.assign(branchShapes.crm,{stages:object({sales:array(stage).refine(unique),repeat:array(stage).refine(unique)}),stageAgentPolicies:record(agentPolicy),replyTemplates:array(object({id,name:id,body:text})).refine(unique)});
const botRule=object({id,enabled:z.boolean(),event:z.enum(['message','first-contact']),field:z.enum(['request','status','channel','city']),operator:z.enum(['contains','equals','any']),value:text,action:z.enum(['template','handoff']),templateId:short,once:z.boolean()});
Object.assign(branchShapes.ai,{bot:object({prompt:text,storeMemory:text,clientMemory:text,model:short,provider:short,mode:short,stopWords:text,temperature:number.min(0).max(2),rate:number.min(0),manager:short,strictTraining:z.boolean().optional()}),policy:object({system:text,manager:text,rules:text,supervisor:text,routing:text,followup:text,supervisorEnabled:z.boolean(),reviewTemplates:z.boolean(),onReviewError:z.enum(['handoff','hold','draft']),onRisk:z.enum(['handoff','hold']),maxRewrites:number.int().min(0).max(10),mode:z.enum(['hybrid','templates','model']),rulesList:array(botRule).refine(unique)}),replyAssistantPrompt:text});
const nodeData=object({kind:z.enum(['Trigger','AI Agent','Sub Agent','Condition','Router','Database','HTTP/API','CRM','Inventory','Message','Human Approval','Delay','Code','Transform','Output']),...optionalFields(['label','source','action','stage','agentId','field','operator','template','templateId','channel','tool','query','code','url','body','mockResponse','format','prompt','model','provider','method','event','approver','message','path','execution','description','steps']),value:primitive.optional(),minutes:z.union([number,text]).optional(),temperature:number.optional(),tokens:number.optional(),disabled:z.boolean().optional(),mockEnabled:z.boolean().optional(),tools:strings.optional()});
const node=object({id,type:short.optional(),position:object({x:number,y:number}),data:nodeData,selected:z.boolean().optional(),dragging:z.boolean().optional(),width:number.optional(),height:number.optional(),measured:object({width:number.optional(),height:number.optional()}).optional()});
const edge=object({id,source:id,target:id,label:short.optional(),sourceHandle:short.nullable().optional(),targetHandle:short.nullable().optional(),type:short.optional(),animated:z.boolean().optional(),selected:z.boolean().optional()});
const agentSettings=object({...optionalFields(['prompt','model','provider','temperature','tokens','budget','retries','approval','description','name','schedule','frequency','status','endpoint','storePermissions']),tools:z.union([text,strings]).optional(),entities:z.union([text,strings]).optional()});
Object.assign(branchShapes.agents,{definitions:array(object({id,name:id,value:number,status:short,channel:short,owner:short,note:text})).refine(unique),settings:record(agentSettings),nodes:array(node).refine(unique),edges:array(edge).refine(unique),library:array(object({id,name:id,date:short,nodes:array(node).refine(unique),edges:array(edge).refine(unique)})).refine(unique),published:object({signature:text,date:short}).nullable()});
const pageName=z.string().refine(value=>navigation.some(row=>row[1]===value),'Неизвестная страница'),action=z.enum(Object.keys(teamActions) as [keyof typeof teamActions,...(keyof typeof teamActions)[]]);
branchShapes.permissions.roles=array(object({id,name:id,pages:z.array(pageName),actions:z.array(action),pageActions:z.record(pageName,z.array(action)).optional()})).refine(unique);
const channelValues=object(optionalFields(['instance','apiUrl','mediaUrl','phone','username','chat','admin','account','page','app','domain','client','pipeline','greeting','position','calendar','sheet','business','pixel','provider','merchant','project','model','url','header','events','hours','hoursStart','hoursEnd','manager','fallback','autoCreate','autoReply','stopOnHuman','route','timezone','owner','routing','retry']));
branchShapes.integrations.channels=record(object({enabled:z.boolean(),values:channelValues,events:strings,updated:short}));
Object.assign(branchShapes.system,{engineer:object({provider:short,model:short,endpoint:text,project:text,branch:short,mode:z.enum(['diagnose','approve','emergency']),backup:z.boolean(),rollback:z.boolean(),tests:z.boolean(),limits:number.int().min(1).max(100)}),watchdog:object({enabled:z.boolean(),interval:number.min(5).max(3600),attempts:number.int().min(0).max(20),telegram:z.boolean()}),ai:object({provider:z.enum(['Codex','Claude','Antigravity','OpenCode','Custom']),model:short,endpoint:text,enabled:z.boolean(),approval:z.boolean(),instructions:text,tools:z.array(toolName)})});
Object.assign(branchShapes.business,{blueprint:object({business:text.optional(),profile:object({industry:short,team:short,channels:strings}).optional(),modules:strings.optional(),createdAt:short.optional()}),analyticsBoards:record(strings),liveAnalytics:liveAnalyticsConfigSchema.default({}),customMetrics:array(object({id,name:id,operation:z.enum(['count','sum','average','share']),field:z.enum(['revenue','profit','cost','spend','aiCost','messages','responseMinutes','rating']),group:z.enum(['none','date','channel','employee','product']),status:short,channel:short,employee:short,owner:short,format:z.enum(['number','money','percent','minutes'])})).refine(unique)});
const extensions=z.unknown().transform((value,ctx)=>{try{return parseExtensionsState(value)}catch(error){ctx.addIssue({code:z.ZodIssueCode.custom,message:error instanceof Error?error.message:'Некорректная конфигурация Store'});return z.NEVER}});
Object.assign(branchShapes.store,{catalog:object({published:z.boolean(),title:text,description:text}),billingPlan:z.enum(['Free','Starter','Business','Enterprise']),extensions});
branchShapes.mcp.connection=object({enabled:z.boolean(),endpoint:text,clients:array(object({id,name:id,tools:z.array(toolName),enabled:z.boolean(),credential:z.string().regex(/^demo-mcp-[a-f0-9-]{12}$/)})).refine(unique)});
export const settingsBranchSchemas=Object.fromEntries(settingsBranches.map(branch=>[branch,object(branchShapes[branch])])) as Record<SettingsBranch,z.AnyZodObject>;
const documentSchema=object({schemaVersion:z.literal(1),...settingsBranchSchemas});
export const defaultSettingsDocument=structuredClone(defaults) as SettingsDocument;
const dangerous=new Set(['__proto__','prototype','constructor']);
const secretKey=/^(?:password|passwd|secret|clientSecret|apiKey|api_key|accessToken|access_token|refreshToken|refresh_token|privateKey|private_key|authorization|credential|credentials|token|verify)$/i;
function inspect(value:unknown,path='',strip=false):unknown{
 if(Array.isArray(value))return value.map((item,index)=>inspect(item,path+'.'+index,strip));
 if(value&&typeof value==='object'){
  if(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null)throw new Error('Недопустимый объект конфигурации: '+path);
  const result:Record<string,unknown>={};for(const [key,item] of Object.entries(value)){if(dangerous.has(key))throw new Error('Недопустимое поле: '+key);if((secretKey.test(key)&&!(key==='credential'&&path.includes('mcp')&&typeof item==='string'&&/^demo-mcp-[a-f0-9-]{12}$/.test(item)))||(key==='key'&&path.includes('integrations'))){if(strip)continue;throw new Error('Секреты не входят в settings.json: '+path+'.'+key)}result[key]=inspect(item,path+'.'+key,strip)}return result;
 }
 if(typeof value==='string'&&(/\bsk-(?:proj-)?[A-Za-z0-9_-]{16,}/.test(value)||/https?:\/\/[^/\s]+:[^/@\s]+@/.test(value)||/[?&](?:api_key|token|secret|access_token)=([^&#\s]+)/i.test(value))){if(strip)return '';throw new Error('В конфигурации обнаружен секрет: '+path)}
 return value;
}
export function validateSettingsDocument(input:unknown):SettingsDocument{const safe=inspect(input);const parsed=documentSchema.safeParse(safe);if(!parsed.success){const issue=parsed.error.issues[0];throw new Error('Некорректная настройка '+(issue.path.join('.')||'settings.json')+': '+issue.message)}return parsed.data as SettingsDocument}
export function readSettingsAlias(document:SettingsDocument,key:string):unknown{
 if(key==='workspace')return (document.business.company as Record<string,unknown>).company;
 if(key==='inventory-company-v3'){const company=document.business.company as Record<string,unknown>;return {name:company.company,inn:company.tax,director:company.director,phone:company.phone,address:company.address,currency:company.currency,timezone:company.timezone}}
 if(key==='settings-deep-v2'){const flat:Record<string,unknown>={};for(const [branch,slot] of Object.values(settingsSectionPaths))Object.assign(flat,document[branch][slot]);const stages=document.crm.stages as {sales:{name:string}[];repeat:{name:string}[]};flat.stages=stages.sales.map(row=>row.name).join('\n');flat.repeatStages=stages.repeat.map(row=>row.name).join('\n');flat.roles=(document.permissions.roles as TeamRole[]).map(role=>role.name).join('\n');return flat}
 const path=settingsAliases[key];return path?document[path[0]][path[1]]:undefined;
}
export function setSettingsAlias(document:SettingsDocument,key:string,value:unknown):SettingsDocument{
 const next=structuredClone(document),safe=inspect(value,settingsAliases[key]?.[0]||'') as Record<string,unknown>;
 if(key==='workspace')(next.business.company as Record<string,unknown>).company=value;
 else if(key==='inventory-company-v3'){if(!safe||typeof safe!=='object'||Array.isArray(safe))throw new Error('Ожидается объект компании');const company=next.business.company as Record<string,unknown>;for(const [from,to] of Object.entries({name:'company',inn:'tax',director:'director',phone:'phone',address:'address',currency:'currency',timezone:'timezone'})){if(Object.hasOwn(safe,from))company[to]=safe[from]}}
 else if(key==='settings-deep-v2'){if(!safe||typeof safe!=='object'||Array.isArray(safe))throw new Error('Ожидается объект настроек');for(const section of settingsCatalog){const [branch,slot]=settingsSectionPaths[section.name];for(const field of section.fields)if(!['stages','repeatStages','roles'].includes(field.key)&&Object.hasOwn(safe,field.key))(next[branch][slot] as Record<string,unknown>)[field.key]=safe[field.key]}}
 else{const path=settingsAliases[key];if(!path)throw new Error('Неизвестный ключ настроек: '+key);next[path[0]][path[1]]=safe}
 return validateSettingsDocument(next);
}
function mergeLegacy(base:unknown,value:unknown):unknown{if(base&&value&&typeof base==='object'&&typeof value==='object'&&!Array.isArray(base)&&!Array.isArray(value)){const result={...base} as Record<string,unknown>;for(const [key,item] of Object.entries(value))result[key]=mergeLegacy(result[key],item);return result}return value}
export function getSettingsDocument(storage:SettingsStorage=localStorage):SettingsDocument{
 const raw=storage.getItem(settingsDocumentKey);if(raw)return validateSettingsDocument(JSON.parse(raw));
 let document=structuredClone(defaultSettingsDocument);const warnings:string[]=[];
 for(const key of ['settings-deep-v2','inventory-company-v3','workspace',...Object.keys(settingsAliases)]){const legacy=storage.getItem('life-'+key);if(legacy===null)continue;try{let value=inspect(JSON.parse(legacy),settingsAliases[key]?.[0]||'',true);if(key==='team-roles-v3'&&Array.isArray(value)){value=value.map(role=>{if(!role||typeof role!=='object'||Array.isArray(role))throw new Error('Некорректная роль');const row=role as Record<string,unknown>,validPage=(page:unknown)=>typeof page==='string'&&navigation.some(item=>item[1]===page),validAction=(action:unknown)=>typeof action==='string'&&Object.hasOwn(teamActions,action);return {id:row.id,name:row.name,pages:Array.isArray(row.pages)?row.pages.filter(validPage):[],actions:Array.isArray(row.actions)?row.actions.filter(validAction):[],...(row.pageActions&&typeof row.pageActions==='object'?{pageActions:Object.fromEntries(Object.entries(row.pageActions).filter(([page])=>validPage(page)).map(([page,actions])=>[page,Array.isArray(actions)?actions.filter(validAction):[]]))}:{})}})}document=setSettingsAlias(document,key,mergeLegacy(readSettingsAlias(document,key),value))}catch(error){if(key==='team-roles-v3')document.permissions.roles=[];warnings.push(key+': '+(error instanceof Error?error.message:'не удалось прочитать'))}}
 storage.setItem(settingsDocumentKey,JSON.stringify(document));if(warnings.length)storage.setItem('life-settings-migration-report-v1',JSON.stringify(warnings));return document;
}
export type SettingsDiff={branch:SettingsBranch;section:string;path:string;before:unknown;after:unknown};
export function settingsDocumentDiff(before:SettingsDocument,after:SettingsDocument):SettingsDiff[]{const result:SettingsDiff[]=[];for(const branch of settingsBranches)for(const section of Object.keys(before[branch]))if(JSON.stringify(before[branch][section])!==JSON.stringify(after[branch][section]))result.push({branch,section,path:branch+'.'+section,before:before[branch][section],after:after[branch][section]});return result}
export type SettingsAccess={canRead:(branch:SettingsBranch)=>boolean;canWrite:(branch:SettingsBranch,section:string)=>boolean;canGrant:(grant:string,operation?:'install'|'update')=>boolean;canExport:boolean};
export function settingsAccess(employee:Employee|undefined,roles:TeamRole[],canEdit=true):SettingsAccess{
 const has=(page?:string,action?:keyof typeof teamActions)=>hasAccess(employee,roles,page,action),settingsEdit=canEdit&&has('settings','edit');
 const branchPage:Record<SettingsBranch,string>={system:'settings',appearance:'settings',crm:'crm',business:'settings',ai:'laboratory',agents:'agents',integrations:'integrations',permissions:'employees',store:'store',mcp:'mcp'};
 const canRead=(branch:SettingsBranch)=>branch==='permissions'?has('employees','manageTeam'):has(branchPage[branch])||(branch!=='store'&&branch!=='mcp'&&has('settings'));
 const canWrite=(branch:SettingsBranch,section:string)=>{if(!canEdit||!canRead(branch))return false;if(branch==='permissions')return has('employees','manageTeam');if(branch==='agents')return has('agents','edit');if(branch==='store')return has('store','edit')&&(section!=='moderation'||has('store','manageTeam')&&has('store','production'));if(branch==='mcp')return has('mcp','edit');if(branch==='system'&&section==='ai')return has('agents','edit');if(branch==='system'&&['server','engineer','watchdog'].includes(section))return has('server','edit')&&has('server','production');return settingsEdit||has(branchPage[branch],'edit')};
 return {canRead,canWrite,canGrant:(grant,operation='install')=>{if(grant.startsWith('tool:')){const tool=systemTools.find(tool=>tool.name===grant.slice(5));return Boolean(tool&&tool.pages.some(page=>has(page,'action' in tool?tool.action:undefined)))}const required=extensionPermissions[grant as ExtensionPermission];return Boolean(required&&required.pages.some(page=>has(page,grant.endsWith('.read')?undefined:operation==='update'&&required.action==='create'?'edit':required.action)))},canExport:has('settings','export')};
}
export function authorizeSettingsChange(before:SettingsDocument,after:SettingsDocument,access:SettingsAccess){
 for(const change of settingsDocumentDiff(before,after))if(!access.canWrite(change.branch,change.section))throw new Error('Недостаточно прав: '+settingsBranchLabels[change.branch]+' / '+change.section);
 if((before.system.ai as {approval:boolean}).approval!==(after.system.ai as {approval:boolean}).approval&&!access.canWrite('system','engineer'))throw new Error('Для изменения подтверждения инженерных действий нужно право production');
 const oldPublications=(before.store.extensions as {publications:{id:string;status:string;securityCheckedAt?:string;publishedAt?:string;reviewNote:string}[]}).publications,newPublications=(after.store.extensions as {publications:typeof oldPublications}).publications;
 const reviewed=(item:typeof oldPublications[number])=>['security','published','changes-requested','withdrawn'].includes(item.status)||Boolean(item.securityCheckedAt||item.publishedAt);
 if([...oldPublications,...newPublications].some(item=>reviewed(item)&&JSON.stringify(oldPublications.find(row=>row.id===item.id))!==JSON.stringify(newPublications.find(row=>row.id===item.id)))&&!access.canWrite('store','moderation'))throw new Error('Модерация Store требует прав редактирования, управления командой и production');
 const previous=before.store.extensions as {installs:{id:string;grants:string[]}[]},next=after.store.extensions as typeof previous;
 for(const row of next.installs)for(const grant of row.grants)if(!previous.installs.find(item=>item.id===row.id)?.grants.includes(grant)&&!access.canGrant(grant,previous.installs.some(item=>item.id===row.id)?'update':'install'))throw new Error('Нет права расширения: '+grant);
 const oldClients=(before.mcp.connection as {clients:{id:string;tools:string[]}[]}).clients,newClients=(after.mcp.connection as {clients:{id:string;tools:string[]}[]}).clients;
 for(const client of newClients)for(const tool of client.tools)if(!oldClients.find(item=>item.id===client.id)?.tools.includes(tool)&&!access.canGrant('tool:'+tool))throw new Error('Нет доступа к инструменту: '+tool);
 for(const tool of (after.system.ai as {tools:string[]}).tools)if(!(before.system.ai as {tools:string[]}).tools.includes(tool)&&!access.canGrant('tool:'+tool))throw new Error('Нет доступа к инструменту: '+tool);
}
export function writeSettingsDocument(next:SettingsDocument,access:SettingsAccess,storage:SettingsStorage=localStorage){const current=getSettingsDocument(storage),valid=validateSettingsDocument(next);authorizeSettingsChange(current,valid,access);persistSettingsDocument(valid,storage);return valid}
export function persistSettingsDocument(document:SettingsDocument,storage:SettingsStorage=localStorage){storage.setItem(settingsDocumentKey,JSON.stringify(validateSettingsDocument(document)));if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('storage-custom',{detail:{key:settingsDocumentKey}}))}
export function resetSettingsBranches(document:SettingsDocument,branches:SettingsBranch[]){const next=structuredClone(document);for(const branch of branches)next[branch]=structuredClone(defaultSettingsDocument[branch]);return validateSettingsDocument(next)}
export function exportSettingsDocument(document:SettingsDocument,access:SettingsAccess){document=validateSettingsDocument(document);if(!access.canExport)throw new Error('Экспорт настроек запрещён вашей ролью');const branches=settingsBranches.filter(access.canRead);return branches.length===settingsBranches.length?document:{schemaVersion:1,kind:'settings-export',branches:Object.fromEntries(branches.map(branch=>[branch,document[branch]]))}}
export function parseSettingsImport(input:unknown,current:SettingsDocument):SettingsDocument{
 const safe=inspect(input);if(safe&&typeof safe==='object'&&(safe as Record<string,unknown>).kind==='settings-export'){const envelope=object({schemaVersion:z.literal(1),kind:z.literal('settings-export'),branches:object(Object.fromEntries(settingsBranches.map(branch=>[branch,settingsBranchSchemas[branch].optional()]))).refine(value=>Object.keys(value).length>0)}).safeParse(safe);if(!envelope.success)throw new Error('Неполный или неизвестный раздел в файле настроек');return validateSettingsDocument({...current,...envelope.data.branches})}return validateSettingsDocument(safe);
}
