import {navigation} from './data.ts';
export const teamActions={create:'Создание записей',edit:'Редактирование',remove:'Удаление',export:'Экспорт данных',ai:'Запуск ИИ',finance:'Финансовые операции',inventory:'Проведение складских документов',manageTeam:'Управление сотрудниками',password:'Пароль и защита своего аккаунта',production:'Действия в production'};
export type TeamAction=keyof typeof teamActions;
export type TeamRole={id:string;name:string;pages:string[];actions:TeamAction[]};
export type Employee={id:string;name:string;email:string;position:string;role:string;status:'Активен'|'Заблокирован'|'Уволен';passwordChangedAt?:string;forcePasswordChange?:boolean};
export const initialRoles:TeamRole[]=[{id:'owner',name:'Владелец',pages:navigation.map(n=>n[1]),actions:Object.keys(teamActions) as TeamAction[]},{id:'manager',name:'Менеджер',pages:['dashboard','crm','conversations','customers','orders','tasks','calendar','my-time','messenger','knowledge','help'],actions:['create','edit','ai','password']},{id:'warehouse',name:'Склад',pages:['dashboard','inventory','pos','tasks','my-time','messenger','help'],actions:['create','edit','inventory','password']},{id:'analyst',name:'Аналитик',pages:['dashboard','analytics','planning','agents','help'],actions:['export','ai','password']}];
export const initialEmployees:Employee[]=[{id:'owner-user',name:'Алихан Торебеков',email:'alihan@demiresults.kg',position:'Основатель',role:'owner',status:'Активен'},{id:'aiym',name:'Айым Абдиева',email:'aiym@demiresults.kg',position:'Менеджер продаж',role:'manager',status:'Активен'},{id:'nuriza',name:'Нуриза Асанова',email:'nuriza@demiresults.kg',position:'Менеджер продаж',role:'manager',status:'Активен'},{id:'medina',name:'Медина Осмонова',email:'medina@demiresults.kg',position:'Консультант',role:'manager',status:'Активен'}];
export function resolvedRolePages(role:TeamRole|undefined){return role?.id==='owner'?navigation.map(item=>item[1]):role?.pages||[]}
export function hasAccess(employee:Employee|undefined,roles:TeamRole[],page?:string,action?:TeamAction){if(!employee||employee.status!=='Активен')return false;const role=roles.find(r=>r.id===employee.role);return Boolean(role&&(!page||resolvedRolePages(role).includes(page))&&(!action||role.actions.includes(action)))}
export type ActionPermissions=Record<TeamAction,boolean>;
export function actionPermissions(employee:Employee|undefined,roles:TeamRole[],page:string):ActionPermissions{return Object.fromEntries((Object.keys(teamActions) as TeamAction[]).map(action=>[action,hasAccess(employee,roles,page,action)])) as ActionPermissions}
export function requiresPasswordChange(employee:Employee|undefined){return employee?.status==='Активен'&&employee.forcePasswordChange===true}
