'use client';
import Select from './Select';
import {X,SlidersHorizontal} from 'lucide-react';
import type {Entity} from '../../lib/os/data';
import {activeDealFilters,type DealFilters as FilterValues} from '../../lib/os/deal-filters';
export default function DealFilters({values,set,deals,stages,colors,count,reset}:{values:FilterValues;set:(key:keyof FilterValues,value:string)=>void;deals:Entity[];stages:string[];colors:string[];count:number;reset:()=>void}){
 const unique=(key:'owner'|'city')=>[...new Set(deals.map(d=>d[key]).filter(Boolean))] as string[];
 const tags=[...new Set(deals.flatMap(d=>d.tags||[]))];
 const controls:[keyof FilterValues,string,string[]][]=[['assignment','Назначение',['Все','Мои','Без ответственного']],['employee','Сотрудник',['Все',...unique('owner')]],['stage','Этап',['Все',...stages]],['tag','Тег',['Все',...tags]],['source','Источник',['Все',...new Set([...deals.map(d=>d.channel),'WhatsApp','Instagram','Telegram','Сайт','Вручную'])]],['attention','Важность',['Все','Срочные','Требуют внимания']],['deadline','Срок задачи',['Все','Просроченные','Непросроченные']],['taskMode','Задачи',['Все','С задачами','Без задач','Без следующей задачи']],['city','Город',['Все',...unique('city')]],['reply','Ответ клиенту',['Все','Без ответа','Ответ отправлен']]];
 const invalid=(values.min&&values.max&&Number(values.min)>Number(values.max))||(values.createdFrom&&values.createdTo&&values.createdFrom>values.createdTo);
 return <section className="panel crm-filter-studio"><header><div><SlidersHorizontal size={16}/><b>Фильтры сделок</b><small>{count} найдено · {activeDealFilters(values).length} условий</small></div><button onClick={reset}><X size={14}/>Сбросить всё</button></header><div className="crm-filter-grid">{controls.map(([key,label,options])=><label key={key}>{label}<Select aria-label={label+' сделок'} value={values[key]} optionColors={key==='stage'?Object.fromEntries(stages.map((s,i)=>[s,colors[i]])):undefined} onChange={e=>set(key,e.target.value)}>{options.map(value=><option key={value}>{value}</option>)}</Select></label>)}<label>Созданы от<input type="date" aria-label="Созданы от" value={values.createdFrom} onChange={e=>set('createdFrom',e.target.value)}/></label><label>Созданы до<input type="date" aria-label="Созданы до" value={values.createdTo} onChange={e=>set('createdTo',e.target.value)}/></label><label>Сумма от, сом<input type="number" min="0" value={values.min} onChange={e=>set('min',e.target.value)}/></label><label>Сумма до, сом<input type="number" min="0" value={values.max} onChange={e=>set('max',e.target.value)}/></label><label>Сортировка<Select aria-label="Сортировка сделок" value={values.sort} onChange={e=>set('sort',e.target.value)}>{[['updated-desc','Сначала активные'],['created-desc','Сначала новые'],['amount-desc','Сумма по убыванию'],['amount-asc','Сумма по возрастанию'],['task-asc','Ближайшая задача']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></label></div>{invalid&&<p className="form-error" role="alert">Начало диапазона не должно превышать конец. Исправьте даты или сумму.</p>}</section>
}
