'use client';
import {X,ArrowUpRight,Search} from 'lucide-react';
import {useEffect,useRef,type ReactNode} from 'react';
export function Badge({children,tone=''}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Modal({title,children,close,wide=false}:{title:string;children:ReactNode;close:()=>void;wide?:boolean}){
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.querySelector<HTMLElement>('input:not([type=hidden]),textarea,select,button')?.focus();return()=>{document.body.style.overflow=bodyOverflow;previous?.focus()}},[]);
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={root} role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){const elements=Array.from(root.current?.querySelectorAll<HTMLElement>('button,a[href],input,textarea,select,[tabindex="0"]')||[]).filter(el=>!el.hasAttribute('disabled')&&el.getClientRects().length);const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header><h2>{title}</h2><button aria-label="Закрыть" onClick={close}><X size={18}/></button></header>{children}</section></div>
}
export function Drawer({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <div className="overlay drawer-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section role="dialog" aria-label={title} aria-modal="true" className="drawer"><header><h2>{title}</h2><button aria-label="Закрыть" onClick={close}><X size={18}/></button></header><div className="drawer-content">{children}</div></section></div>}
export function Metric({label,value,change,comparison=true}:{label:string;value:string;change:string;comparison?:boolean}){return <div className="metric"><span>{label}<ArrowUpRight size={15}/></span><strong>{value}</strong><small><b>{change}</b>{comparison?' к прошлому периоду':''}</small></div>}
export function SearchField({value,set,placeholder='Поиск...'}:{value:string;set:(x:string)=>void;placeholder?:string}){return <label className="search-field"><Search size={16}/><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
