'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,Sparkles,Volume2} from 'lucide-react';
const transcript='Кожа немного сухая, иногда бывают покраснения. Нужен мягкий уход без отдушек и солнцезащитный крем. Подскажите, что есть в наличии?';
const bars=Array.from({length:44},(_,i)=>8+((i*17+i*i*3)%28));
export default function VoiceMessage(){const [playing,setPlaying]=useState(false);const [progress,setProgress]=useState(0);const [speed,setSpeed]=useState(1);const [error,setError]=useState('');const speech=useRef<SpeechSynthesisUtterance|null>(null);const seek=useRef(0);const timer=useRef<ReturnType<typeof setInterval>|null>(null);const duration=16;const time=(n:number)=>'0:'+String(Math.min(duration,Math.floor(n))).padStart(2,'0');
const stopTimer=()=>{if(timer.current)clearInterval(timer.current);timer.current=null};
useEffect(()=>()=>{stopTimer();if(speech.current&&typeof speechSynthesis!=='undefined')speechSynthesis.cancel()},[]);
function play(from=progress){if(typeof window.speechSynthesis==='undefined'){setError('Синтез речи недоступен в этом браузере. Расшифровка доступна ниже.');return}speechSynthesis.cancel();stopTimer();const start=from>=duration?0:from;seek.current=start;const utterance=new SpeechSynthesisUtterance(transcript.slice(Math.floor(start/duration*transcript.length)));utterance.lang='ru-RU';utterance.rate=speed;speech.current=utterance;utterance.onstart=()=>{setPlaying(true);const began=performance.now();timer.current=setInterval(()=>setProgress(Math.min(duration-.1,start+(performance.now()-began)/1000*speed)),100)};utterance.onend=()=>{stopTimer();setPlaying(false);setProgress(duration)};utterance.onerror=e=>{stopTimer();setPlaying(false);if(e.error!=='canceled'&&e.error!=='interrupted')setError('Не удалось воспроизвести демоозвучку. Попробуйте ещё раз.')};setError('');speechSynthesis.speak(utterance)}
function pause(){speechSynthesis.cancel();stopTimer();setPlaying(false)}
return <div className="voice-message"><div className="voice-player"><button className="voice-play" aria-label={playing?'Пауза голосового сообщения':'Воспроизвести демоозвучку'} onClick={()=>playing?pause():play()}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><div className="voice-seek"><div className="voice-wave" aria-hidden="true">{bars.map((h,i)=><i key={i} style={{height:h,background:i/bars.length<=progress/duration?'var(--accent)':'var(--muted)'}}/>)}</div><input aria-label="Позиция голосового сообщения" type="range" min="0" max={duration} step="0.1" value={progress} onChange={e=>{const value=Number(e.target.value);setProgress(value);if(playing)play(value)}}/></div><span>{time(progress)} / {time(duration)}</span><select aria-label="Скорость голосового сообщения" value={speed} onChange={e=>{const next=Number(e.target.value);setSpeed(next);if(playing){pause()}}}>{[1,1.5,2].map(s=><option key={s} value={s}>{s}×</option>)}</select></div><div className="voice-meta"><Volume2 size={12}/>Демоозвучка синтезом речи · 12:41</div>{error&&<p role="status" className="voice-error">{error}</p>}<div className="voice-transcript"><small><Sparkles size={13}/>Текст, проанализированный ботом</small><p>{transcript}</p><span>AI: запрос на мягкий уход и SPF · чувствительная кожа</span></div></div>}
