'use client';
import Select from '../../components/os/Select';
import {useState} from 'react';
import {Target,Plus,Pencil,Download,Check} from 'lucide-react';
import {useStored} from '../../lib/os/storage';
import {initialDeals,money} from '../../lib/os/data';
import {initialEmployees,type ActionPermissions,type TeamAction} from '../../lib/os/team';
import {planningPersonKey,planningPersonOptions} from '../../lib/os/planning-people';
import {exportCSV} from '../../lib/os/export';
import NeutralArt from '../../components/os/NeutralArt';
import DocumentExplorer from '../DocumentExplorer';
import {Modal,Badge} from '../../components/os/ui';
type Salary={id:string;name:string;employeeId?:string;base:number;bonus:number;advance:number;status:string;month:string};
type Consultation={id:string;client:string;clientId?:string;employee:string;employeeId?:string;date:string;time:string;status:string;note:string};
export default function BusinessPlanning({notify,audit,permissions}:{notify:(s:string)=>void;audit:(s:string)=>void;permissions?:ActionPermissions}){
 const allow=(action:TeamAction)=>permissions?.[action]??true;
 const guard=(action:TeamAction)=>{if(allow(action))return true;notify('Действие запрещено ролью сотрудника');return false};
 const [employees]=useStored('team-employees-v3',initialEmployees);
 const [clients]=useStored('deals',initialDeals);
 const people=employees.map(employee=>({id:employee.id,name:employee.name,active:employee.status==='Активен'}));
 const [tab,setTab]=useState('Декомпозиция');
 const [plan,setPlan]=useStored('decomposition-v2',{revenue:1000000,check:5000,conversion:30,days:26,adBudget:60000});
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [salary,setSalary]=useStored<Salary[]>('salary-v2',['Айым','Медина','Алихан'].map((name,i)=>({id:'sal'+i,name,base:25000+i*5000,bonus:6000+i*1500,advance:5000,status:'Черновик',month:new Date().toISOString().slice(0,7)})));
 const [consultations,setConsultations]=useStored<Consultation[]>('consultations-v2',[{id:'consult1',client:'Айжан',employee:'Медина',date:'2026-10-06',time:'14:00',status:'Подтверждена',note:'Подбор ухода'}]);
 const [editSalary,setEditSalary]=useState<Salary|null>(null);
 const [salaryOpen,setSalaryOpen]=useState(false);
 const [consultOpen,setConsultOpen]=useState(false);
 const [editConsult,setEditConsult]=useState<Consultation|null>(null);
 const [dateFilter,setDateFilter]=useState('');
 const orders=plan.check>0?Math.ceil(plan.revenue/plan.check):0;
 const leads=plan.conversion>0?Math.ceil(orders/(plan.conversion/100)):0;
 const perDay=Math.ceil(leads/Math.max(plan.days,1));
 const salaryPeople=planningPersonOptions(people,editSalary?.name,editSalary?.employeeId);
 const consultPeople=planningPersonOptions(people,editConsult?.employee,editConsult?.employeeId);
 const consultClients=planningPersonOptions(clients,editConsult?.client,editConsult?.clientId);
 const salaryAction=editSalary?'edit':'create';
 const consultAction=editConsult?'edit':'create';
 const salaryLocked=!allow(salaryAction)||(editSalary?.status==='Выплачено'&&!allow('finance'));
 return <div className="studio-page"><header className="studio-heading"><div><h1><Target size={24}/>Планирование и команда</h1><p>Декомпозиция продаж, начисления, консультации и документы.</p></div><Badge>Демо workspace</Badge></header><div className="workspace-tabs">{['Декомпозиция','Зарплаты','Консультации','Документы','KPI команды'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Декомпозиция'?<><div className="split-panels"><section className="panel"><h2>План бизнеса</h2><form data-permission="edit" onSubmit={e=>{e.preventDefault();if(!guard('edit'))return;audit('Сохранена декомпозиция продаж');notify('План сохранён')}}>{[['revenue','План выручки, сом',1,100000000],['check','Средний чек, сом',1,1000000],['conversion','Конверсия, %',1,100],['days','Рабочих дней',1,31],['adBudget','Бюджет рекламы, сом',0,10000000]].map(([key,label,min,max])=><label key={String(key)}>{label}<input disabled={!allow('edit')} type="number" min={Number(min)} max={Number(max)} value={plan[key as keyof typeof plan]} onChange={e=>{if(!guard('edit'))return;const value=Number(e.target.value);if(Number.isFinite(value))setPlan(v=>({...v,[key]:value}))}}/></label>)}<button data-permission="edit" disabled={!allow('edit')} className="primary">Сохранить план</button></form></section><section className="panel funnel-plan"><NeutralArt kind="team" className="planning-art"/><h2>Расчётная воронка</h2><p>План рассчитывается из введённых показателей.</p>{[['Лидов за месяц',leads],['Заказов',orders],['Лидов в рабочий день',perDay],['Выручка в день',money(plan.revenue/Math.max(plan.days,1))],['Плановый CAC',money(plan.adBudget/Math.max(orders,1))]].map(([name,value])=><div className="report-row" key={String(name)}><span>{name}</span><strong>{value}</strong></div>)}<button data-permission="export" disabled={!allow('export')} onClick={()=>{if(guard('export'))exportCSV('business-plan.csv',['Метрика','План'],[['Выручка',plan.revenue],['Лиды',leads],['Заказы',orders],['Лиды в день',perDay]])}}><Download size={14}/>Экспорт плана</button></section></div><section className="panel"><h3>План по рабочим дням</h3><div className="daily-plan">{Array.from({length:Math.max(1,Math.min(31,Math.floor(plan.days)))},(_,i)=><div key={i}><small>День {i+1}</small><b>{perDay} лидов</b><span>{Math.ceil(orders/Math.max(plan.days,1))} заказов</span></div>)}</div></section></>
 :tab==='Зарплаты'?<><div className="toolbar"><input aria-label="Месяц зарплаты" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button data-permission="create" disabled={!allow('create')} className="primary" onClick={()=>{if(!guard('create'))return;setEditSalary(null);setSalaryOpen(true)}}><Plus size={15}/>Начисление</button><button data-permission="export" disabled={!allow('export')} onClick={()=>{if(guard('export'))exportCSV('salary-'+month+'.csv',['Сотрудник','Оклад','Бонус','Аванс','Итого','Статус'],salary.filter(s=>s.month===month).map(s=>[s.name,s.base,s.bonus,s.advance,s.base+s.bonus-s.advance,s.status]))}}><Download size={14}/>CSV</button></div><div className="stat-grid"><div><small>Начислено</small><strong>{money(salary.filter(s=>s.month===month).reduce((sum,s)=>sum+s.base+s.bonus,0))}</strong></div><div><small>К выплате после авансов</small><strong>{money(salary.filter(s=>s.month===month&&s.status!=='Выплачено').reduce((sum,s)=>sum+s.base+s.bonus-s.advance,0))}</strong></div></div><section className="panel table-scroll"><table className="os-table"><thead><tr>{['Сотрудник','Оклад','KPI и бонусы','Аванс','Итого','Статус',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{salary.filter(s=>s.month===month).map(s=><tr key={s.id}><td>{employees.find(employee=>employee.id===planningPersonKey(people,s.name,s.employeeId))?.name||s.name}</td><td>{money(s.base)}</td><td>{money(s.bonus)}</td><td>{money(s.advance)}</td><td><b>{money(s.base+s.bonus-s.advance)}</b></td><td><Badge>{s.status}</Badge></td><td className="table-actions"><button data-permission="edit" disabled={!allow('edit')||(s.status==='Выплачено'&&!allow('finance'))} aria-label={'Редактировать начисление '+s.name} onClick={()=>{if(!guard('edit')||(s.status==='Выплачено'&&!guard('finance')))return;setEditSalary(s);setSalaryOpen(true)}}><Pencil size={14}/></button><button data-permission="finance" disabled={s.status==='Выплачено'||!allow('edit')||!allow('finance')} onClick={()=>{if(!guard('edit')||!guard('finance'))return;setSalary(v=>v.map(x=>x.id===s.id?{...x,status:'Выплачено'}:x));audit('Демо отметка выплаты '+s.name);notify('Выплата отмечена локально, деньги не переводились')}}><Check size={14}/>Отметить выплату</button></td></tr>)}</tbody></table></section></>
 :tab==='Консультации'?<><div className="toolbar"><input aria-label="Дата консультации" type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/><button onClick={()=>setDateFilter('')}>Все даты</button><button data-permission="create" disabled={!allow('create')} className="primary" onClick={()=>{if(!guard('create'))return;setEditConsult(null);setConsultOpen(true)}}><Plus size={15}/>Записать клиента</button></div><div className="integration-grid">{consultations.filter(c=>!dateFilter||c.date===dateFilter).map(c=><section className="panel consultation-card" key={c.id}><div className="row-between"><h3>{clients.find(client=>client.id===planningPersonKey(clients,c.client,c.clientId))?.name||c.client}</h3><Badge>{c.status}</Badge></div><b>{c.date} · {c.time}</b><p>{employees.find(employee=>employee.id===planningPersonKey(people,c.employee,c.employeeId))?.name||c.employee} · {c.note}</p><Select disabled={!allow('edit')} aria-label={'Статус консультации '+c.client} value={c.status} onChange={e=>{if(!guard('edit'))return;setConsultations(v=>v.map(x=>x.id===c.id?{...x,status:e.target.value}:x));audit('Изменён статус консультации '+c.client)}}>{['Запланирована','Подтверждена','Завершена','Неявка','Отменена'].map(s=><option key={s}>{s}</option>)}</Select><button data-permission="edit" disabled={!allow('edit')} onClick={()=>{if(!guard('edit'))return;setEditConsult(c);setConsultOpen(true)}}>Изменить запись</button></section>)}</div></>
 :tab==='Документы'?<DocumentExplorer notify={notify} audit={audit} permissions={permissions}/>
 :<TeamKPI notify={notify} canEdit={allow('edit')}/>}
 {salaryOpen&&<Modal title="Начисление зарплаты" close={()=>setSalaryOpen(false)}><form data-permission={salaryAction} onSubmit={e=>{e.preventDefault();if(!guard(salaryAction)||(editSalary?.status==='Выплачено'&&!guard('finance')))return;const f=new FormData(e.currentTarget);const person=salaryPeople.find(option=>option.value===f.get('employee'));if(!person){notify('Выберите сотрудника из списка');return}const s:Salary={id:editSalary?.id||crypto.randomUUID(),name:person.name,employeeId:person.id,base:Number(f.get('base')),bonus:Number(f.get('bonus')),advance:Number(f.get('advance')),status:String(f.get('status')),month:editSalary?.month||month};if(s.status==='Выплачено'&&!guard('finance'))return;if([s.base,s.bonus,s.advance].some(value=>!Number.isFinite(value)||value<0)){notify('Укажите неотрицательные суммы');return}if(s.advance>s.base+s.bonus){notify('Аванс превышает начисление');return}setSalary(v=>editSalary?v.map(x=>x.id===s.id?s:x):[...v,s]);setSalaryOpen(false);audit('Сохранено начисление '+s.name);notify('Начисление сохранено')}}><label>Сотрудник<Select name="employee" disabled={salaryLocked} required defaultValue={editSalary?planningPersonKey(people,editSalary.name,editSalary.employeeId):''}><option value="">Выберите сотрудника</option>{salaryPeople.map(person=><option value={person.value} key={person.value}>{person.name}</option>)}</Select></label>{[['base','Оклад'],['bonus','Бонусы'],['advance','Аванс']].map(([key,label])=><label key={key}>{label}<input disabled={salaryLocked} name={key} type="number" min={0} step="0.01" required defaultValue={editSalary?.[key as 'base']||0}/></label>)}<label>Статус<Select name="status" disabled={salaryLocked} defaultValue={editSalary?.status||'Черновик'}><option>Черновик</option><option>Рассчитано</option><option disabled={!allow('finance')}>Выплачено</option></Select></label><button data-permission={salaryAction} disabled={salaryLocked} className="primary">Сохранить начисление</button></form></Modal>}
 {consultOpen&&<Modal title="Запись на консультацию" close={()=>setConsultOpen(false)}><form data-permission={consultAction} onSubmit={e=>{e.preventDefault();if(!guard(consultAction))return;const f=new FormData(e.currentTarget);const employee=consultPeople.find(option=>option.value===f.get('employee'));const client=consultClients.find(option=>option.value===f.get('client'));if(!employee||!client){notify('Выберите клиента и сотрудника из списка');return}const c:Consultation={id:editConsult?.id||crypto.randomUUID(),client:client.name,clientId:client.id,employee:employee.name,employeeId:employee.id,date:String(f.get('date')),time:String(f.get('time')),status:editConsult?.status||'Запланирована',note:String(f.get('note')).trim()};if(consultations.some(x=>x.id!==c.id&&planningPersonKey(people,x.employee,x.employeeId)===planningPersonKey(people,c.employee,c.employeeId)&&x.date===c.date&&x.time===c.time&&!['Отменена','Неявка'].includes(x.status))){notify('У сотрудника уже есть запись на это время');return}setConsultations(v=>editConsult?v.map(x=>x.id===c.id?c:x):[...v,c]);setConsultOpen(false);audit('Записан клиент '+c.client);notify('Запись сохранена')}}><label>Клиент<Select name="client" disabled={!allow(consultAction)} required defaultValue={editConsult?planningPersonKey(clients,editConsult.client,editConsult.clientId):''}><option value="">Выберите клиента</option>{consultClients.map(client=><option value={client.value} key={client.value}>{client.name}</option>)}</Select></label><label>Сотрудник<Select name="employee" disabled={!allow(consultAction)} required defaultValue={editConsult?planningPersonKey(people,editConsult.employee,editConsult.employeeId):''}><option value="">Выберите сотрудника</option>{consultPeople.map(employee=><option value={employee.value} key={employee.value}>{employee.name}</option>)}</Select></label>{[['date','Дата'],['time','Время'],['note','Комментарий']].map(([key,label])=><label key={key}>{label}<input disabled={!allow(consultAction)} name={key} required={key!=='note'} type={key==='date'?'date':key==='time'?'time':'text'} defaultValue={editConsult?.[key as 'client']||''}/></label>)}<button data-permission={consultAction} disabled={!allow(consultAction)} className="primary">Сохранить запись</button></form></Modal>}
 </div>;
}
function TeamKPI({notify,canEdit}:{notify:(s:string)=>void;canEdit:boolean}){
 const [rows,setRows]=useStored('team-kpi-v2',['Айым','Медина','Алихан'].map((name,i)=>({name,salesPlan:300000,sales:240000+i*18000,consultPlan:50,consult:42+i*2,response:4+i})));
 const labels={salesPlan:'План продаж',sales:'Факт продаж',consultPlan:'План консультаций',consult:'Факт консультаций',response:'Ответ, мин'};
 const change=(index:number,key:keyof typeof labels,value:string)=>{if(!canEdit)return;const number=Number(value);if(!Number.isFinite(number)||number<0)return;setRows(previous=>previous.map((row,i)=>i===index?{...row,[key]:number}:row))};
 return <section className="panel"><h2>KPI команды · демо</h2><p>{canEdit?'Редактируйте план и факт, чтобы увидеть выполнение.':'План, фактические результаты и выполнение показателей команды.'}</p><div className="table-scroll"><table className="os-table"><thead><tr><th>Сотрудник</th><th>План продаж</th><th>Факт</th><th>Выполнение</th><th>План консультаций</th><th>Факт</th><th>Ответ, мин</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.name}><td>{r.name}</td>{(['salesPlan','sales'] as const).map(key=><td key={key}><input disabled={!canEdit} aria-label={r.name+' · '+labels[key]} type="number" min={0} value={r[key]} onChange={e=>change(i,key,e.target.value)}/></td>)}<td>{r.salesPlan?Math.round(r.sales/r.salesPlan*100):0}%</td>{(['consultPlan','consult','response'] as const).map(key=><td key={key}><input disabled={!canEdit} aria-label={r.name+' · '+labels[key]} type="number" min={0} value={r[key]} onChange={e=>change(i,key,e.target.value)}/></td>)}</tr>)}</tbody></table></div><button data-permission="edit" disabled={!canEdit} className="primary" onClick={()=>{if(canEdit)notify('KPI команды сохранены локально')}}>Сохранить KPI</button></section>;
}
