'use client';
import {useState} from 'react';
import {ExternalLink,Search,ShoppingBag,Download,Settings2} from 'lucide-react';
import {useStored} from '../../lib/os/storage';
import {initialStorefront,shopStatuses,shopDeliveries,shopPayments,changeShopOrderStatus,type ShopOrder} from '../../lib/os/shop';
import {money} from '../../lib/os/data';
import {exportCSV} from '../../lib/os/export';
import type {ActionPermissions} from '../../lib/os/team';
import {Modal,Badge} from '../../components/os/ui';
import Select from '../../components/os/Select';
import './InventoryStorefront.css';

export default function InventoryStorefront({notify,permissions}:{notify:(message:string)=>void;permissions?:ActionPermissions}){
 const [settings,setSettings]=useStored('storefront-v2',initialStorefront),[orders,setOrders]=useStored<ShopOrder[]>('shop-orders-v1',[]);
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [detailId,setDetailId]=useState(''),[settingsOpen,setSettingsOpen]=useState(false);
 const canEdit=permissions?.edit??true,canExport=permissions?.export??true;
 const detail=orders.find(order=>order.id===detailId);
 const filtered=orders.filter(order=>(!status||order.status===status)&&(!from||order.date.slice(0,10)>=from)&&(!to||order.date.slice(0,10)<=to)&&[order.number,order.customerName,order.phone,order.address,order.comment,...order.items.map(item=>item.name)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 function update(id:string,value:ShopOrder['status']){if(!canEdit)return;try{setOrders(changeShopOrderStatus(orders,id,value));notify('Статус заказа сохранён')}catch(error){notify(error instanceof Error?error.message:'Проверьте заказ')}}
 return <div className="storefront-workspace"><div className="toolbar"><h2><ShoppingBag size={21}/>Витрина и заказы</h2><Badge tone={settings.published?'green':''}>{settings.published?'Приём заказов открыт':'Витрина закрыта'}</Badge><a className="button-link" href="/shop" target="_blank" rel="noreferrer">Открыть витрину <ExternalLink size={15}/></a><button data-permission="edit" disabled={!canEdit} onClick={()=>setSettingsOpen(true)}><Settings2 size={15}/>Настройки</button></div>
  <div className="storefront-summary"><section><small>Новые заявки</small><strong>{orders.filter(order=>order.status==='new').length}</strong></section><section><small>Подтверждены</small><strong>{orders.filter(order=>order.status==='confirmed').length}</strong></section><section><small>Выполнены</small><strong>{orders.filter(order=>order.status==='completed').length}</strong></section><section><small>Сумма выполненных заказов</small><strong>{money(orders.filter(order=>order.status==='completed').reduce((sum,order)=>sum+order.total,0))}</strong></section></div>
  <section className="panel storefront-filters"><label className="search-field"><Search size={16}/><input placeholder="Заказ, клиент, телефон, товар…" aria-label="Поиск заказов витрины" value={query} onChange={event=>setQuery(event.target.value)}/></label><label>Статус<Select value={status} onChange={event=>setStatus(event.target.value)}><option value="">Все заказы</option>{Object.entries(shopStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label><label>С даты<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>По дату<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button onClick={()=>{setQuery('');setStatus('');setFrom('');setTo('')}}>Сбросить</button><button data-permission="export" disabled={!canExport||!filtered.length} onClick={()=>{if(!canExport)return;exportCSV('shop-orders.csv',['Заказ','Дата','Клиент','Телефон','Адрес','Получение','Оплата','Статус','Сумма','Комментарий'],filtered.map(order=>[order.number,order.date,order.customerName,order.phone,order.address,shopDeliveries[order.deliveryMethod],shopPayments[order.paymentMethod],shopStatuses[order.status],order.total,order.comment]))}}><Download size={15}/>Экспорт</button></section>
  {from&&to&&from>to&&<p role="alert" className="form-error">Дата окончания должна быть позже начала.</p>}
  <div className="panel table-scroll"><table className="os-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Получение</th><th>Сумма</th><th>Статус</th><th/></tr></thead><tbody>{filtered.map(order=><tr key={order.id}><td><button className="storefront-order-link" onClick={()=>setDetailId(order.id)}>№{order.number}</button><small className="storefront-cell-note">{new Date(order.date).toLocaleString('ru-RU')}</small></td><td><b>{order.customerName}</b><a className="storefront-cell-note" href={'tel:'+order.phone}>{order.phone}</a></td><td>{shopDeliveries[order.deliveryMethod]}<small className="storefront-cell-note">{order.address}</small></td><td><b>{money(order.total)}</b><small className="storefront-cell-note">{order.items.length} позиций</small></td><td><Select aria-label={'Статус заказа '+order.number} disabled={!canEdit} value={order.status} onChange={event=>update(order.id,event.target.value as ShopOrder['status'])}>{Object.entries(shopStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></td><td><button onClick={()=>setDetailId(order.id)}>Открыть</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><ShoppingBag size={30}/><h3>{orders.length?'Нет заказов по этим фильтрам':'Здесь появятся заказы клиентов'}</h3><p>{orders.length?'Измените поиск или период.':'Включите витрину в настройках и оформите тестовый заказ на /shop.'}</p></div>}</div>
  <p className="storefront-footnote">Локальные заявки сохраняются в этом браузере. Остатки проверяются при оформлении; статусы заказа не списывают товар и не создают оплату в кассе.</p>
  {detail&&<Modal title={'Заказ №'+detail.number} close={()=>setDetailId('')} wide><div className="storefront-detail"><div className="row-between"><div><h3>{detail.customerName}</h3><a href={'tel:'+detail.phone}>{detail.phone}</a><p>{detail.address||'Адрес не указан'}</p></div><Badge tone={detail.status==='completed'?'green':''}>{shopStatuses[detail.status]}</Badge></div><dl><div><dt>Дата</dt><dd>{new Date(detail.date).toLocaleString('ru-RU')}</dd></div><div><dt>Получение</dt><dd>{shopDeliveries[detail.deliveryMethod]}</dd></div><div><dt>Оплата</dt><dd>{shopPayments[detail.paymentMethod]} · ожидает согласования</dd></div></dl><div className="table-scroll"><table className="os-table"><thead><tr><th>Товар</th><th>Количество</th><th>Цена</th><th>Итого</th></tr></thead><tbody>{detail.items.map(item=><tr key={item.productId}><td>{item.name}</td><td>{item.quantity}</td><td>{money(item.unitPrice)}</td><td>{money(item.total)}</td></tr>)}</tbody></table></div>{detail.comment&&<p className="storefront-comment">{detail.comment}</p>}<div className="row-between"><label>Статус<Select disabled={!canEdit} value={detail.status} onChange={event=>update(detail.id,event.target.value as ShopOrder['status'])}>{Object.entries(shopStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label><strong className="storefront-detail-total">{money(detail.total)}</strong></div></div></Modal>}
  {settingsOpen&&<Modal title="Настройки витрины" close={()=>setSettingsOpen(false)}><form data-permission="edit" onSubmit={event=>{event.preventDefault();if(!canEdit)return;const data=new FormData(event.currentTarget);setSettings({title:String(data.get('title')).trim(),description:String(data.get('description')).trim(),published:data.get('published')==='on'});setSettingsOpen(false);notify('Настройки витрины сохранены')}}><fieldset disabled={!canEdit} className="storefront-settings-fields"><label>Название<input name="title" required maxLength={120} defaultValue={settings.title}/></label><label>Описание<textarea name="description" maxLength={500} defaultValue={settings.description}/></label><label className="setting-toggle">Открыть витрину для заказов<input name="published" type="checkbox" defaultChecked={settings.published}/></label><p>Каталог берёт товары, цены, скидки и остатки из товароучёта. Услуги в витрине не показываются.</p></fieldset><div className="modal-footer"><button type="button" onClick={()=>setSettingsOpen(false)}>Отмена</button><button className="primary" disabled={!canEdit}>Сохранить</button></div></form></Modal>}
 </div>;
}
