'use client';
import {useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Download,Pencil,Plus,Search,Trash2,Wallet} from 'lucide-react';
import {useStored} from '../../lib/os/storage';
import {initialEmployees,type ActionPermissions} from '../../lib/os/team';
import {settingDefaults} from '../settings/catalog';
import {exportCSV} from '../../lib/os/export';
import {moneyAccounts,moneyAccountId,moneyAccountBalances,moneyRowCurrency,moneyStatus,moneyStatuses,moneyCounterpartyKey,filterMoneyRows,emptyMoneyFilters,saveMoneyRow,deleteMoneyRow,type MoneyRow,type MoneyFilters,type MoneyStatus} from '../../lib/os/inventory-money';
import {inventoryDirectories} from './InventoryDirectory';
import {Modal,Badge} from '../../components/os/ui';
import Select from '../../components/os/Select';
import './InventoryMoney.css';
const amountText=(amount:number,currency='KGS')=>currency==='KGS'?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(amount)+' сом':new Intl.NumberFormat('ru-RU',{style:'currency',currency,maximumFractionDigits:2}).format(amount);
export default function InventoryMoney({notify,audit,chooseTab,permissions}:{notify:(message:string)=>void;audit:(message:string)=>void;chooseTab:(tab:string)=>void;permissions?:ActionPermissions}){
 const [rows,setRows]=useStored<MoneyRow[]>('inventory-money-v3',[]);
 const [directory]=useStored('inventory-directories-v2',inventoryDirectories);
 const [settings]=useStored('settings-deep-v2',settingDefaults);
 const [employees]=useStored('team-employees-v3',initialEmployees);
 const [filters,setFilters]=useState<MoneyFilters>(emptyMoneyFilters);
 const [open,setOpen]=useState(false);
 const [editing,setEditing]=useState<MoneyRow|null>(null);
 const [detail,setDetail]=useState<MoneyRow|null>(null);
 const [removing,setRemoving]=useState<MoneyRow|null>(null);
 const [direction,setDirection]=useState('Приход');
 const [account,setAccount]=useState('');
 const [error,setError]=useState('');
 const accounts=moneyAccounts(directory.Счета||[],rows);
 const activeAccounts=accounts.filter(item=>!item.archived);
 const can=(action:'create'|'edit'|'remove')=>!permissions||(permissions.finance&&permissions[action]);
 const guard=(action:'create'|'edit'|'remove')=>{if(can(action))return true;notify('Действие запрещено ролью сотрудника');return false};
 const canExport=permissions?.export??true;
 const filtered=filterMoneyRows(rows,filters,accounts);
 const periodInvalid=Boolean(filters.from&&filters.to&&filters.from>filters.to);
 const filter=(key:keyof MoneyFilters,value:string)=>setFilters(current=>({...current,[key]:value}));
 const categories=[...new Set(['Продажа','Закупка','Зарплата','Аренда','Прочее',...String(settings.expenseCategories||'').split('\n'),...rows.map(row=>row.category)].filter(Boolean))];
 const counterparties=[...(directory.Поставщики||[]).map(row=>({id:'supplier:'+row.id,name:row.name,label:row.name+' · поставщик'})),...(directory.Клиенты||[]).map(row=>({id:'client:'+row.id,name:row.name,label:row.name+' · клиент'})),...employees.filter(employee=>employee.status==='Активен').map(employee=>({id:'employee:'+employee.id,name:employee.name,label:employee.name+' · сотрудник'}))];
 const currentCounterparty=editing?moneyCounterpartyKey(editing):'';
 const editorParties=editing?.counterparty&&!counterparties.some(party=>party.id===currentCounterparty)?[...counterparties,{id:currentCounterparty,name:editing.counterparty,label:editing.counterparty+' · сохранено ранее'}]:counterparties;
 const partyFilters=[...new Map(rows.map(row=>[moneyCounterpartyKey(row),{value:moneyCounterpartyKey(row),label:counterparties.find(party=>party.id===row.counterpartyId)?.name||row.counterparty||'Без контрагента'}])).values()];
 const editorAccounts=accounts.filter(item=>!item.archived||editing&&moneyAccountId(editing,accounts)===item.id);
 const totals=new Map<string,{income:number;expense:number}>();
 for(const row of filtered){if(moneyStatus(row)!=='Проведена')continue;const currency=moneyRowCurrency(row,accounts);const total=totals.get(currency)||{income:0,expense:0};if(row.direction==='Приход')total.income+=Math.round(row.amount*100);if(row.direction==='Расход')total.expense+=Math.round(row.amount*100);totals.set(currency,total)}
 const currencies=[...totals.entries()];
 const balances=moneyAccountBalances(accounts,rows).filter(item=>!filters.account||item.id===filters.account);
 function begin(direction:string,row:MoneyRow|null=null){if(!guard(row?'edit':'create'))return;setDirection(direction);setAccount(row?moneyAccountId(row,accounts):'');setEditing(row);setError('');setDetail(null);setOpen(true)}
 return <div className="money-workspace">
  <div className="toolbar"><h2><Wallet size={21}/>Движение денег</h2><button data-permission="create" disabled={!can('create')||!activeAccounts.length} onClick={()=>begin('Приход')}><Plus size={15}/>Приход</button><button data-permission="create" disabled={!can('create')||!activeAccounts.length} onClick={()=>begin('Расход')}><Plus size={15}/>Расход</button><button data-permission="export" disabled={!canExport||!filtered.length} onClick={()=>{if(!canExport)return;exportCSV('money-movement.csv',['Дата','Операция','Тип','Сумма','Валюта','Категория','Счёт','Контрагент','Статус','Номер документа','Комментарий'],filtered.map(row=>[row.date,row.operation,row.direction,row.amount,moneyRowCurrency(row,accounts),row.category,accounts.find(item=>item.id===moneyAccountId(row,accounts))?.name||row.account,row.counterparty,moneyStatus(row),row.reference||'',row.note||'']));notify('Выбранные операции экспортированы')}}><Download size={15}/>Экспорт</button></div>
  {!activeAccounts.length&&<div className="info-panel"><span>Добавьте счёт для новых денежных операций.</span><button onClick={()=>chooseTab('Счета')}>Открыть счета</button></div>}
  <section className="panel money-filters" aria-label="Фильтры денежных операций">
   <label className="search-field"><Search size={15}/><input aria-label="Поиск денежных операций" placeholder="Назначение, категория, номер…" value={filters.query} onChange={e=>filter('query',e.target.value)}/></label>
   <label>С даты<input type="date" aria-label="Денежные операции с даты" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>По дату<input type="date" aria-label="Денежные операции по дату" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label>
   <label>Тип<Select value={filters.direction} onChange={e=>filter('direction',e.target.value)}><option value="">Все операции</option><option>Приход</option><option>Расход</option></Select></label>
   <label>Счёт<Select value={filters.account} onChange={e=>filter('account',e.target.value)}><option value="">Все счета</option>{accounts.map(item=><option value={item.id} key={item.id}>{item.name}{item.archived?' · архив':''}</option>)}</Select></label>
   <label>Контрагент<Select value={filters.counterparty} onChange={e=>filter('counterparty',e.target.value)}><option value="">Все контрагенты</option>{partyFilters.map(party=><option key={party.value} value={party.value}>{party.label}</option>)}</Select></label>
   <label>Статус<Select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">Все статусы</option>{moneyStatuses.map(status=><option key={status}>{status}</option>)}</Select></label>
   <button type="button" onClick={()=>setFilters(emptyMoneyFilters)} disabled={!Object.values(filters).some(Boolean)}>Сбросить фильтры</button>
  </section>
  {periodInvalid&&<p className="form-error" role="alert">Конец периода должен быть не раньше начала.</p>}
  <div className="stat-grid money-totals">{(['income','expense','net'] as const).map((key,i)=><div key={key}><small>{['Поступило за выборку','Списано за выборку','Разница за выборку'][i]}</small>{currencies.length?currencies.map(([currency,total])=><strong key={currency}>{amountText((key==='net'?total.income-total.expense:total[key])/100,currency)}</strong>):<strong>{amountText(0)}</strong>}</div>)}<div><small>Операций в выборке</small><strong>{filtered.length}</strong><small>{filtered.filter(row=>moneyStatus(row)==='Черновик').length} в черновиках</small></div></div>
  <section className="panel table-scroll"><table className="os-table"><thead><tr>{['Дата','Операция','Сумма','Счёт','Контрагент','Статус','Действия'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td>{row.date}</td><td><button className="money-record-link" onClick={()=>setDetail(row)}>{row.direction==='Приход'?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}<span>{row.operation}<small>{row.direction} · {row.category}</small></span></button></td><td><b className={row.direction==='Приход'?'positive':''}>{row.direction==='Приход'?'+':'−'}{amountText(row.amount,moneyRowCurrency(row,accounts))}</b></td><td>{accounts.find(item=>item.id===moneyAccountId(row,accounts))?.name||row.account}</td><td>{counterparties.find(party=>party.id===row.counterpartyId)?.name||row.counterparty||'—'}</td><td><Badge tone={moneyStatus(row)==='Проведена'?'green':moneyStatus(row)==='Черновик'?'orange':''}>{moneyStatus(row)}</Badge></td><td className="table-actions"><button data-permission="edit" disabled={!can('edit')} aria-label={'Редактировать операцию '+row.operation} onClick={()=>begin(row.direction,row)}><Pencil size={14}/></button><button data-permission="remove" disabled={!can('remove')} aria-label={'Удалить операцию '+row.operation} onClick={()=>{if(guard('remove')){setRemoving(row);setError('')}}}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="inline-empty">{rows.length?'Нет операций с такими фильтрами.':'Добавьте первый приход или расход.'}</p>}<p className="money-ledger-note">В расчёт входят только проведённые ручные операции. Оплаты и возвраты POS доступны в кассовых отчётах.</p></section>
  <section className="panel"><div className="panel-title"><div><h3>Остатки по счетам</h3><p>Начальный баланс и все проведённые ручные операции. Фильтры периода и контрагента не меняют остатки.</p></div></div><div className="money-balances">{balances.map(item=><article key={item.id}><span>{item.name}{item.archived&&<small>Сохранённый счёт</small>}</span><strong>{amountText(item.balance,item.currency)}</strong><small>Начальный: {amountText(item.opening,item.currency)}</small><div><small>+ {amountText(item.income,item.currency)}</small><small>− {amountText(item.expense,item.currency)}</small></div></article>)}</div>{!balances.length&&<p>Счета ещё не добавлены.</p>}</section>
  {open&&<Modal title={editing?'Изменить денежную операцию':'Новая денежная операция'} close={()=>setOpen(false)} wide><form data-permission={editing?'edit':'create'} onSubmit={e=>{e.preventDefault();if(!guard(editing?'edit':'create'))return;const data=new FormData(e.currentTarget);const party=editorParties.find(item=>item.id===data.get('counterparty'));const input:MoneyRow={id:editing?.id||crypto.randomUUID(),direction,operation:String(data.get('operation')||''),amount:Number(data.get('amount')),category:String(data.get('category')||''),accountId:account,account:'',counterparty:party?.name||'',counterpartyId:party?.id,date:String(data.get('date')||''),status:String(data.get('status')) as MoneyStatus,reference:String(data.get('reference')||''),note:String(data.get('note')||'')};try{const next=saveMoneyRow(rows,input,accounts,permissions);setRows(next);setOpen(false);audit((editing?'Изменена':'Создана')+' денежная операция: '+input.operation);notify('Операция сохранена, остаток счёта пересчитан')}catch(error){setError(error instanceof Error?error.message:'Проверьте поля операции')}}}>
   <div className="form-grid"><label>Тип<Select disabled={!can(editing?'edit':'create')} value={direction} onChange={e=>setDirection(e.target.value)}><option>Приход</option><option>Расход</option></Select></label><label>Дата<input disabled={!can(editing?'edit':'create')} name="date" type="date" required defaultValue={editing?.date||new Date().toLocaleDateString('en-CA')}/></label></div>
   <label>Назначение операции<input disabled={!can(editing?'edit':'create')} name="operation" required defaultValue={editing?.operation||''} placeholder="Например: оплата аренды за октябрь"/></label>
   <div className="form-grid"><label>Счёт<Select required disabled={!can(editing?'edit':'create')} name="account" value={account} onChange={e=>setAccount(e.target.value)}><option value="">Выберите счёт</option>{editorAccounts.map(item=><option value={item.id} key={item.id}>{item.name} · {item.currency}{item.archived?' · архив':''}</option>)}</Select></label><label>Сумма{account?' · '+accounts.find(item=>item.id===account)?.currency:''}<input disabled={!can(editing?'edit':'create')} name="amount" type="number" min={.01} step=".01" required defaultValue={editing?.amount||''}/></label><label>Категория<Select disabled={!can(editing?'edit':'create')} name="category" defaultValue={editing?.category||'Прочее'}>{categories.map(category=><option key={category}>{category}</option>)}</Select></label><label>Статус<Select disabled={!can(editing?'edit':'create')} name="status" defaultValue={editing?moneyStatus(editing):'Проведена'}>{moneyStatuses.map(status=><option key={status}>{status}</option>)}</Select></label></div>
   <label>Контрагент<Select disabled={!can(editing?'edit':'create')} name="counterparty" defaultValue={editing?.counterparty?currentCounterparty:''}><option value="">Без контрагента</option>{editorParties.map(party=><option key={party.id} value={party.id}>{party.label}</option>)}</Select></label><label>Номер платежа или документа<input disabled={!can(editing?'edit':'create')} name="reference" defaultValue={editing?.reference||''}/></label><label>Комментарий<textarea disabled={!can(editing?'edit':'create')} name="note" defaultValue={editing?.note||''}/></label>
   <small>Черновики и отменённые операции не влияют на остаток счёта.</small>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={()=>setOpen(false)}>Отмена</button><button data-permission={editing?'edit':'create'} disabled={!can(editing?'edit':'create')} className="primary">Сохранить операцию</button></div>
  </form></Modal>}
  {detail&&<Modal title={detail.operation} close={()=>setDetail(null)}><div className="money-detail"><strong>{detail.direction==='Приход'?'+':'−'}{amountText(detail.amount,moneyRowCurrency(detail,accounts))}</strong>{[['Дата',detail.date],['Тип',detail.direction],['Статус',moneyStatus(detail)],['Категория',detail.category],['Счёт',accounts.find(item=>item.id===moneyAccountId(detail,accounts))?.name||detail.account],['Контрагент',detail.counterparty||'Не указан'],['Номер документа',detail.reference||'Не указан']].map(([name,value])=><div className="report-row" key={name}><span>{name}</span><b>{value}</b></div>)}{detail.note&&<p>{detail.note}</p>}</div><div className="modal-footer"><button onClick={()=>setDetail(null)}>Закрыть</button><button data-permission="edit" disabled={!can('edit')} className="primary" onClick={()=>begin(detail.direction,detail)}>Редактировать</button></div></Modal>}
  {removing&&<Modal title="Удалить денежную операцию?" close={()=>setRemoving(null)}><p>«{removing.operation}» · {amountText(removing.amount,moneyRowCurrency(removing,accounts))}</p><p>Остаток счёта пересчитается без этой операции.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button onClick={()=>setRemoving(null)}>Отмена</button><button data-permission="remove" disabled={!can('remove')} className="primary" onClick={()=>{if(!guard('remove'))return;try{setRows(deleteMoneyRow(rows,removing.id,permissions));audit('Удалена денежная операция: '+removing.operation);setRemoving(null);notify('Операция удалена, остаток счёта пересчитан')}catch(error){setError(error instanceof Error?error.message:'Не удалось удалить операцию')}}}>Удалить операцию</button></div></Modal>}
 </div>;
}
