'use client';
import Select from '../components/os/Select';
import DocumentExplorer from './DocumentExplorer';
import AutomationWorkspace from './AutomationWorkspace';
import type {ActionPermissions} from '../lib/os/team';
import {useEffect,useState} from 'react';
import NeutralArt from '../components/os/NeutralArt';
import {Plus,Trash2,Pencil,Play,Pause,CalendarDays,ChevronLeft,ChevronRight,FileText,Workflow,Users,ArrowUpRight,Download} from 'lucide-react';
import {useStored} from '../lib/os/storage';
import {type Entity,money} from '../lib/os/data';
import {Modal,Drawer,Badge,SearchField} from '../components/os/ui';
export const businessRoutes=['calendar','employees','knowledge','marketing','finance','automations'];
type RecordItem=Entity&{date?:string;time?:string;email?:string;category?:string};
type Props={route:string;tab:string;setTab:(s:string)=>void;search:string;setSearch:(s:string)=>void;notify:(s:string)=>void;audit:(s:string)=>void;go:(s:string)=>void;onDetail?:(d:Entity)=>void;onCreate?:()=>void;createSignal?:number;permissions?:ActionPermissions};
const make=(name:string,i:number,extra:Partial<RecordItem>={}):RecordItem=>({id:'BM-'+i,name,value:0,status:'Активно',channel:'Основное',owner:'Алихан',note:'',...extra});
export const initial:Record<string,RecordItem[]>={calendar:[make('Планирование команды',1,{date:'2026-10-05',time:'10:00',owner:'Айым',note:'План недели и приоритеты',channel:'Встреча'}),make('Консультация: Айжан',2,{date:'2026-10-05',time:'14:30',channel:'Консультация'}),make('Запуск осенней кампании',3,{date:'2026-10-08',time:'11:00',channel:'Маркетинг'})],employees:['Айым Абдиева','Медина Осмонова','Алихан Торебеков'].map((n,i)=>make(n,10+i,{channel:['Менеджер продаж','Консультант','Администратор'][i],owner:['Оператор','Оператор','Владелец'][i],email:['aiym','medina','alihan'][i]+'@demiresults.kg',value:48+i*8,note:'Работает с клиентами и задачами команды',status:'В сети'})),knowledge:['Каталог косметики','Правила консультации','Доставка и оплата','Ответы на частые вопросы'].map((n,i)=>make(n,20+i,{channel:i===3?'FAQ':'Документ',owner:'Sales Agent',status:'Индексирован',note:['Beauty of Joseon SPF 50 — 1 800 сом. Мягкое очищение и подбор ухода.','Уточните тип кожи, текущий уход и чувствительность. Медицинские вопросы передавайте специалисту.','Бишкек: доставка курьером. Оплата наличными или переводом.','Как выбрать SPF? Уточните тип кожи и предпочтения клиента.'][i]})),marketing:['Осенний уход','Повторные продажи','SPF • Meta Ads','Органический трафик'].map((n,i)=>make(n,30+i,{channel:['Instagram','WhatsApp','Meta Ads','Сайт'][i],value:[18000,3200,12000,0][i],note:'Осенняя кампания • персональный подбор ухода',status:i===3?'Завершено':'Активно',category:'utm_campaign=autumn_'+i})),finance:[make('Продажи магазина',40,{channel:'Доход',value:842500,date:'2026-10-05',status:'Оплачен'}),make('Закупка товара',41,{channel:'Расход',value:320000,date:'2026-10-04',status:'Оплачен'}),make('Аренда помещения',42,{channel:'Расход',value:68000,date:'2026-10-01',status:'Оплачен'}),make('Расходы AI',43,{channel:'Расход',value:1240,date:'2026-10-05',status:'Оплачен'})],automations:['Новый лид → Sales Agent','Follow-up через 24 часа','Проверка оплаты → CRM','Склад: низкий остаток'].map((n,i)=>make(n,50+i,{value:24+i*8,channel:['lead.created','timer.24h','order.paid','stock.low'][i],note:'Событие → проверка условия → действие',status:i===3?'Пауза':'Активно'}))};
export function applyBusinessBlueprint(selections:boolean[],description='',kind:'setup'|'automation'='setup'){
 if(typeof window==='undefined')return;
 let existing:Record<string,RecordItem[]>;
 try{existing={...initial,...JSON.parse(localStorage.getItem('life-business-modules-v1')||'{}')}}catch{existing={...initial}}
 const workflows=[...(existing.automations||[])];
 if(kind==='automation'){
  const name='Лиды без ответа 10 минут → Sales Agent';
  if(!workflows.some(w=>w.name===name))workflows.push(make(name,Date.now(),{id:crypto.randomUUID(),channel:'lead.unanswered',note:'Таймер: 10 минут → проверить ответ сотрудника → назначить Sales Agent → уведомить менеджера. '+description,status:'Активно'}));
 }else if(selections[4]){
  for(const template of initial.automations){if(!workflows.some(w=>w.name===template.name))workflows.push({...template,id:crypto.randomUUID(),note:template.note+(description?' • '+description:'')})}
 }
 localStorage.setItem('life-business-modules-v1',JSON.stringify({...existing,automations:workflows}));
 window.dispatchEvent(new Event('storage-custom'));
}
const titles:Record<string,string>={calendar:'событие',employees:'сотрудника',knowledge:'документ',marketing:'кампанию',finance:'операцию',automations:'автоматизацию'};
function BusinessModulesBase({route,tab,setTab,search,setSearch,notify,audit,go,createSignal=0}:Props){
 const [data,setData]=useStored('business-modules-v1',initial);const [editing,setEditing]=useState<RecordItem|null>(null);const [formOpen,setFormOpen]=useState(false);const [detail,setDetail]=useState<RecordItem|null>(null);const [calendarView,setCalendarView]=useStored('calendar-view','Месяц');const [anchor,setAnchor]=useState('2026-10-05');const [runHistory,setRunHistory]=useStored<{name:string;time:string}[]>('business-runs',[]);
 useEffect(()=>{setDetail(null);setFormOpen(false)},[route]);useEffect(()=>{if(createSignal>0){setEditing(null);setFormOpen(true)}},[createSignal]);
 const list=data[route]||[];const tabs=route==='finance'?['Обзор','Доходы','Расходы','P&L']:route==='knowledge'?['Все документы','Коллекции','FAQ']:route==='marketing'?['Кампании','Источники','UTM']:route==='automations'?['Все workflow','Активные','История']:[];
 const current=tabs.includes(tab)?tab:tabs[0];const visible=list.filter(x=>(x.name+' '+x.channel+' '+x.owner+' '+x.note).toLowerCase().includes(search.toLowerCase())).filter(x=>current==='Доходы'?x.channel==='Доход':current==='Расходы'?x.channel==='Расход':current==='FAQ'?x.channel==='FAQ':current==='Активные'?x.status==='Активно':true);
 const update=(items:RecordItem[])=>setData(d=>({...d,[route]:items}));const add=()=>{setEditing(null);setFormOpen(true)};const edit=(item:RecordItem)=>{setEditing(item);setDetail(null);setFormOpen(true)};const remove=(item:RecordItem)=>{update(list.filter(x=>x.id!==item.id));setDetail(null);audit('Удалено: '+item.name);notify('Запись удалена')};
 const save=(form:HTMLFormElement)=>{const f=new FormData(form);const item:RecordItem={id:editing?.id||crypto.randomUUID(),name:String(f.get('name')).trim(),value:f.has('value')?Number(f.get('value')||0):(editing?.value||0),status:String(f.get('status')||'Активно'),channel:String(f.get('channel')||'Основное'),owner:String(f.get('owner')||'Алихан'),note:String(f.get('note')||''),date:String(f.get('date')||anchor),time:String(f.get('time')||'10:00'),email:String(f.get('email')||''),category:String(f.get('category')||'')};update(editing?list.map(x=>x.id===item.id?item:x):[...list,item]);audit((editing?'Изменено: ':'Создано: ')+item.name);setFormOpen(false);notify('Изменения сохранены')};
 const income=list.filter(x=>x.channel==='Доход').reduce((s,x)=>s+x.value,0),costs=list.filter(x=>x.channel==='Расход').reduce((s,x)=>s+x.value,0);
 function exportCSV(){const quote=(s:string)=>'"'+s.replaceAll('"','""')+'"';const csv='Название,Тип,Сумма,Статус\n'+visible.map(x=>[quote(x.name),quote(x.channel),x.value,quote(x.status)].join(',')).join('\n');const a=document.createElement('a');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.href=u;a.download=route+'.csv';a.click();URL.revokeObjectURL(u);notify('CSV экспортирован')}
 function run(x:RecordItem){setRunHistory(h=>[{name:x.name,time:new Date().toLocaleString('ru-RU')},...h]);update(list.map(y=>y.id===x.id?{...y,value:y.value+1}:y));audit('Демо workflow выполнен: '+x.name);notify('Демонстрационный запуск завершён')}
 const date=new Date(anchor+'T12:00:00');const start=new Date(date);if(calendarView==='Месяц'){start.setDate(1);start.setDate(1-((start.getDay()+6)%7))}else if(calendarView==='Неделя')start.setDate(start.getDate()-((start.getDay()+6)%7));const count=calendarView==='День'?1:calendarView==='Неделя'?7:42;const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 return <>{['knowledge','automations'].includes(route)&&<div className="module-art-heading"><div><h2>{route==='knowledge'?'Знания, на которые можно опереться':'Процессы, которые работают за вас'}</h2><p>{route==='knowledge'?'Документы и инструкции команды в одном месте.':'События, условия и действия вашего бизнеса.'}</p></div><NeutralArt kind={route==='knowledge'?'knowledge':'workflow'}/></div>}<div className="toolbar">{route==='calendar'?<><button aria-label="Предыдущий период" onClick={()=>{const d=new Date(date);calendarView==='Месяц'?d.setMonth(d.getMonth()-1):d.setDate(d.getDate()-(calendarView==='Неделя'?7:1));setAnchor(iso(d))}}><ChevronLeft size={16}/></button><h3>{date.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h3><button aria-label="Следующий период" onClick={()=>{const d=new Date(date);calendarView==='Месяц'?d.setMonth(d.getMonth()+1):d.setDate(d.getDate()+(calendarView==='Неделя'?7:1));setAnchor(iso(d))}}><ChevronRight size={16}/></button><button onClick={()=>setAnchor(iso(new Date()))}>Сегодня</button><div className="tabs">{['День','Неделя','Месяц'].map(v=><button key={v} className={calendarView===v?'selected':''} onClick={()=>setCalendarView(v)}>{v}</button>)}</div></>:tabs.length?<div className="tabs">{tabs.map(t=><button className={current===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>:<Badge>{list.length} сотрудника</Badge>}<SearchField value={search} set={setSearch}/><button onClick={exportCSV}><Download size={14}/>CSV</button><button className="primary" onClick={add}><Plus size={15}/>Добавить {titles[route]}</button></div>
 {route==='calendar'&&<><div className={'calendar '+(calendarView==='День'?'day':calendarView==='Неделя'?'week':'')}>{Array.from({length:count},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const day=iso(d);return <div key={day} className={day===anchor?'today':''}><div className="row-between"><b>{d.toLocaleDateString('ru-RU',{day:'numeric',...(calendarView!=='Месяц'?{weekday:'short' as const}:{})})}</b><button aria-label={'Добавить событие '+day} onClick={()=>{setAnchor(day);add()}}><Plus size={12}/></button></div>{visible.filter(x=>x.date===day).sort((a,b)=>(a.time||'').localeCompare(b.time||'')).map(x=><button key={x.id} onClick={()=>setDetail(x)}>{x.name}<small>{x.time} · {x.owner}</small></button>)}</div>})}</div><div className="info-panel"><CalendarDays size={16}/>События сохраняются в браузере. Выберите дату или откройте событие для редактирования.</div></>}
 {route==='employees'&&<div className="cards-grid">{visible.map((x,i)=><section key={x.id} className="panel employee"><div className="row-between"><span className="avatar large">{x.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><Badge tone={x.status==='В сети'?'green':''}>{x.status}</Badge></div><h3>{x.name}</h3><p>{x.channel}</p><Badge>{x.owner}</Badge><div className="agent-metrics"><div><b>{x.value}</b><small>продаж • демо</small></div><div><b>{32+i*5}%</b><small>конверсия • демо</small></div></div><label>Загрузка · {Math.min(64+i*12,96)}%</label><div className="bar-track"><div style={{width:Math.min(64+i*12,96)+'%'}}/></div><button onClick={()=>setDetail(x)}>Карточка сотрудника<ArrowUpRight size={14}/></button></section>)}</div>}
 {route==='finance'&&<div className="metrics">{[['Доходы',income],['Расходы',costs],['Прибыль',income-costs],['Операций',list.length]].map(([label,value],i)=><div className="metric" key={label}><span>{label}</span><strong>{i===3?value:money(Number(value))}</strong><small>На основе локальных операций</small></div>)}</div>}
 {route==='automations'&&current==='История'?<section className="panel">{runHistory.length?runHistory.map((h,i)=><div className="activity-row" key={i}><Workflow size={16}/><div>{h.name}<small>{h.time}</small></div><Badge tone="green">Демо: выполнено</Badge></div>):<div className="empty">Запустите workflow, чтобы увидеть историю.</div>}</section>:!['calendar','employees'].includes(route)&&<section className="panel table-panel"><table><thead><tr><th>{route==='knowledge'?'Документ':route==='marketing'&&current==='UTM'?'Кампания / UTM':'Название'}</th><th>{route==='finance'?'Тип':route==='knowledge'?'Коллекция / доступ':'Канал / триггер'}</th><th>{route==='finance'?'Сумма':route==='marketing'?'Бюджет':route==='automations'?'Запуски':'Статус'}</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><button onClick={()=>setDetail(x)}>{route==='knowledge'?<FileText size={15}/>:route==='automations'?<Workflow size={15}/>:null}{x.name}</button>{route==='marketing'&&current==='UTM'&&<small>{x.category||'UTM не задан'}</small>}</td><td>{route==='knowledge'?(current==='Коллекции'?x.channel:x.owner):x.channel}</td><td>{route==='finance'||route==='marketing'?money(x.value):route==='automations'?x.value:<Badge tone="violet">{x.channel}</Badge>}</td><td><Badge tone={x.status==='Пауза'?'orange':'green'}>{x.status}</Badge></td><td><div className="row"><button aria-label={'Редактировать '+x.name} onClick={()=>edit(x)}><Pencil size={14}/></button>{route==='automations'&&<><button aria-label={'Сменить статус '+x.name} onClick={()=>{update(list.map(y=>y.id===x.id?{...y,status:y.status==='Активно'?'Пауза':'Активно'}:y));audit('Обновлён статус '+x.name)}}>{x.status==='Активно'?<Pause size={14}/>:<Play size={14}/>}</button><button disabled={x.status==='Пауза'} onClick={()=>run(x)}>Тест</button><button onClick={()=>go('builder')}>Builder</button></>}<button aria-label={'Удалить '+x.name} onClick={()=>remove(x)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">Записей нет. Добавьте запись или измените поиск.</div>}</section>}
 {detail&&<Drawer title={detail.name} close={()=>setDetail(null)}><Badge tone="violet">{detail.status}</Badge><label>Тип / канал<b>{detail.channel}</b></label><label>{route==='employees'?'Роль доступа':'Ответственный / доступ AI'}<b>{detail.owner}</b></label>{route==='employees'&&<label>Email<b>{detail.email}</b></label>}{route==='calendar'&&<label>Дата и время<b>{detail.date} · {detail.time}</b></label>}{['finance','marketing'].includes(route)&&<label>Сумма<b>{money(detail.value)}</b></label>}<label>Описание<p style={{whiteSpace:'pre-wrap'}}>{detail.note||'Описание пока не добавлено.'}</p></label>{route==='knowledge'&&<div className="info-panel"><FileText size={16}/>Содержимое документа доступно в локальной базе знаний. Индексация AI демонстрационная.</div>}{route==='employees'&&<div className="info-panel"><Users size={16}/>Доступ определяется ролью сотрудника. В прототипе права показываются для ознакомления.</div>}<div className="row"><button className="primary" onClick={()=>edit(detail)}><Pencil size={15}/>Редактировать</button><button onClick={()=>remove(detail)}><Trash2 size={15}/>Удалить</button></div></Drawer>}
 {formOpen&&<Modal title={(editing?'Редактировать ':'Добавить ')+titles[route]} close={()=>setFormOpen(false)}><form className="entity-form" onSubmit={e=>{e.preventDefault();save(e.currentTarget)}}><label>Название / имя<input required name="name" autoFocus defaultValue={editing?.name}/></label><div className="form-grid"><label>{route==='employees'?'Должность':'Тип / канал'}{route==='finance'?<Select name="channel" defaultValue={editing?.channel||'Доход'}><option>Доход</option><option>Расход</option></Select>:route==='knowledge'?<Select name="channel" defaultValue={editing?.channel||'Документ'}><option>Документ</option><option>FAQ</option><option>Каталог</option><option>Политики</option></Select>:<input name="channel" defaultValue={editing?.channel||({employees:'Менеджер',calendar:'Встреча',marketing:'Instagram',automations:'lead.created'}[route])}/>}</label><label>Статус<Select name="status" defaultValue={editing?.status||({employees:'В сети',knowledge:'Индексирован',finance:'Оплачен'}[route]||'Активно')}>{(route==='employees'?['В сети','Не в сети','Отпуск']:route==='knowledge'?['Индексирован','Черновик']:route==='finance'?['Оплачен','Ожидает оплаты']:['Активно','Пауза','Завершено']).map(s=><option key={s}>{s}</option>)}</Select></label><label>{route==='employees'?'Роль доступа':route==='knowledge'?'Агенты с доступом':'Ответственный'}<input name="owner" defaultValue={editing?.owner||'Алихан'}/></label>{['finance','marketing'].includes(route)&&<label>Сумма / бюджет, сом<input name="value" type="number" min="0" defaultValue={editing?.value||0}/></label>}{['calendar','finance'].includes(route)&&<label>Дата<input required name="date" type="date" defaultValue={editing?.date||anchor}/></label>}{route==='calendar'&&<label>Время<input required name="time" type="time" defaultValue={editing?.time||'10:00'}/></label>}{route==='employees'&&<label>Email<input name="email" type="email" defaultValue={editing?.email}/></label>}{route==='marketing'&&<label>UTM<input name="category" defaultValue={editing?.category} placeholder="utm_campaign=autumn"/></label>}</div><label>{route==='knowledge'?'Содержимое документа':'Описание'}<textarea name="note" rows={5} defaultValue={editing?.note}/></label><div className="modal-footer"><button type="button" onClick={()=>setFormOpen(false)}>Отмена</button><button className="primary">Сохранить</button></div></form></Modal>}
 </>;
}

export default function BusinessModules(props:Props){return props.route==='automations'?<AutomationWorkspace {...props} initialData={initial}/>:props.route==='knowledge'?<DocumentExplorer notify={props.notify} audit={props.audit} createSignal={props.createSignal}/>:<BusinessModulesBase {...props}/>;}
