'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {CalendarDays,Plus,ChevronLeft,ChevronRight,Clock,MapPin,UserRound,Pencil,Trash2,ArrowUpRight,Download,List,CheckCircle2} from 'lucide-react';
import {Modal,Drawer,Badge,SearchField} from '../components/os/ui';
import Select from '../components/os/Select';
import {useStored} from '../lib/os/storage';
import {initialDeals,initialTasks,money,type Entity} from '../lib/os/data';
import {initialInventory} from '../lib/os/inventory-model';
import {initialEmployees,type ActionPermissions} from '../lib/os/team';
import {planningPersonKey,planningPersonOptions} from '../lib/os/planning-people';
import {settingDefaults} from './settings/catalog';
import {exportCSV} from '../lib/os/export';
import {buildCalendarEvents,calendarSources,calendarToday,calendarRange,shiftCalendar,validCalendarDate,validCalendarTime,calendarTimezone,initialCalendarConsultations,type CalendarRecord,type CalendarEvent,type CalendarView,type CalendarSource} from '../lib/os/calendar';
import './CalendarWorkspace.css';
type Props={initialData:Record<string,Entity[]>;search:string;setSearch:(value:string)=>void;notify:(message:string)=>void;audit:(message:string)=>void;go:(route:string)=>void;permissions?:ActionPermissions;allowedPages?:string[];createSignal?:number};
const weekdays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const formatDay=(date:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'long'})=>new Intl.DateTimeFormat('ru-RU',{...options,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
const statuses=['Запланировано','Подтверждено','Завершено','Отменено'];
const types=['Встреча','Звонок','Командное событие','Личное напоминание','Обучение','Консультация'];
export default function CalendarWorkspace({initialData,search,setSearch,notify,audit,go,permissions,allowedPages,createSignal=0}:Props){
 const canCreate=permissions?.create??true,canEdit=permissions?.edit??true,canRemove=permissions?.remove??true,canExport=permissions?.export??true;
 const [business,setBusiness]=useStored<Record<string,CalendarRecord[]>>('business-modules-v1',initialData);
 const [consultations]=useStored('consultations-v2',initialCalendarConsultations),[deals]=useStored('deals',initialDeals),[tasks]=useStored('tasks',initialTasks),[inventory]=useStored('inventory-v2',initialInventory),[employees]=useStored('team-employees-v3',initialEmployees),[settings]=useStored('settings-deep-v2',settingDefaults);
 const timeZone=calendarTimezone(String(settings.timezone||'Asia/Bishkek'));
 const today=calendarToday(timeZone);
 const [anchor,setAnchor]=useState(today),[selectedDate,setSelectedDate]=useState(today);
 const [savedView,setView]=useStored('calendar-view','Месяц');
 const view:CalendarView=savedView==='Неделя'||savedView==='Список'?savedView:'Месяц';
 const [filters,setFilters]=useStored('calendar-filters-v1',{source:'Все',owner:'Все',state:'Все'});
 const [editing,setEditing]=useState<CalendarRecord|null>(null),[formOpen,setFormOpen]=useState(false),[formDate,setFormDate]=useState(today),[formTime,setFormTime]=useState('09:00'),[formEndTime,setFormEndTime]=useState(''),[allDay,setAllDay]=useState(false),[detailId,setDetailId]=useState(''),[removeId,setRemoveId]=useState('');
 const events=buildCalendarEvents({business,consultations,deals,tasks,inventory,employees,timeZone,allowedPages});
 const filtered=events.filter(event=>(filters.source==='Все'||event.source===filters.source)&&(filters.owner==='Все'||event.ownerId===filters.owner)&&(filters.state==='Все'||(filters.state==='Активные'?!event.completed:event.completed))&&(event.title+' '+event.owner+' '+event.note).toLowerCase().includes(search.toLowerCase()));
 const range=calendarRange(anchor,view);
 const periodEvents=filtered.filter(event=>event.date>=range.start&&event.date<=range.end);
 const dayEvents=filtered.filter(event=>event.date===selectedDate);
 const detail=events.find(event=>event.id===detailId);
 const ownRecords=business.calendar||[];
 const ownerOptions=[...new Map([...employees.map(employee=>[employee.id,employee.name] as const),...events.map(event=>[event.ownerId,event.owner] as const)]).entries()];
 const sourceOptions=(Object.entries(calendarSources) as [CalendarSource,typeof calendarSources[CalendarSource]][]).filter(([key,source])=>key==='calendar'||!allowedPages||allowedPages.includes(source.route));
 const people=employees.map(employee=>({...employee,active:employee.status==='Активен'}));
 const formOwners=planningPersonOptions(people,editing?.owner,editing?.employeeId);
 const currentSignal=useRef(0);
 useEffect(()=>{if(createSignal>0&&createSignal!==currentSignal.current){currentSignal.current=createSignal;queueMicrotask(()=>{if(canCreate){setEditing(null);setFormDate(today);setFormTime('09:00');setFormEndTime('');setAllDay(false);setFormOpen(true)}})}},[createSignal,canCreate,today]);
 function navigate(direction:number){const next=shiftCalendar(anchor,view,direction);setAnchor(next);setSelectedDate(next)}
 function selectDate(date:string){if(!validCalendarDate(date))return;setAnchor(date);setSelectedDate(date)}
 function add(date=selectedDate){if(!canCreate)return;setEditing(null);setFormDate(date);setFormTime('09:00');setFormEndTime('');setAllDay(false);setFormOpen(true)}
 function edit(record:CalendarRecord){if(!canEdit)return;setEditing(record);setFormDate(record.date||selectedDate);setFormTime(record.time||'09:00');setFormEndTime(record.endTime||'');setAllDay(!record.time);setFormOpen(true);setDetailId('')}
 function save(form:HTMLFormElement){
  if(editing?!canEdit:!canCreate)return;
  const values=new FormData(form),name=String(values.get('name')||'').trim(),date=String(values.get('date')||''),time=allDay?'':String(values.get('time')||''),endTime=allDay?'':String(values.get('endTime')||'');
  const ownerKey=String(values.get('owner')||'__none'),person=formOwners.find(option=>option.value===ownerKey);
  if(!name||!validCalendarDate(date)){notify('Укажите название и корректную дату');return}
  if(!allDay&&(!validCalendarTime(time)||(endTime&&(!validCalendarTime(endTime)||endTime<=time)))){notify('Укажите время начала и более позднее время окончания');return}
  if(ownerKey!=='__none'&&!person){notify('Выберите ответственного из списка');return}
  const record:CalendarRecord={...editing,id:editing?.id||crypto.randomUUID(),name,value:editing?.value||0,owner:person?.name||'',employeeId:person?.id,status:String(values.get('status')||statuses[0]),channel:String(values.get('channel')||types[0]),note:String(values.get('note')||'').trim(),date,time,endTime,location:String(values.get('location')||'').trim()};
  setBusiness(value=>({...value,calendar:editing?(value.calendar||[]).map(row=>row.id===record.id?record:row):[...(value.calendar||[]),record]}));setFormOpen(false);selectDate(date);setFilters({source:'Все',owner:'Все',state:'Все'});setSearch('');setDetailId('calendar:'+record.id);audit((editing?'Изменено':'Создано')+' событие: '+name);notify('Событие сохранено');
 }
 const eventButton=(event:CalendarEvent,compact=false)=><button key={event.id} className={'calendar-event-button '+(compact?'compact ':'')+(event.completed?'is-completed':'')} style={{'--event-color':calendarSources[event.source].color} as CSSProperties} onClick={()=>setDetailId(event.id)} title={event.title+' · '+(event.time||'Весь день')+' · '+event.owner}><span className="calendar-event-time">{event.time||'Весь день'}</span><span className="calendar-event-title">{event.title}</span>{!compact&&<small>{event.owner} · {calendarSources[event.source].label}</small>}</button>;
 return <div className="calendar-workspace">
  <header className="calendar-heading"><div><span className="calendar-eyebrow"><CalendarDays size={16}/>Рабочий календарь</span><h2>Команда, клиенты и важные даты</h2><p>События из рабочих разделов собираются здесь автоматически.</p></div><button data-permission="create" disabled={!canCreate} className="primary" onClick={()=>add()}><Plus size={16}/>Новое событие</button></header>
  <div className="calendar-controls"><div className="calendar-period-control"><button aria-label="Предыдущий период" onClick={()=>navigate(-1)}><ChevronLeft size={17}/></button><button aria-label="Следующий период" onClick={()=>navigate(1)}><ChevronRight size={17}/></button><h3>{view==='Неделя'?formatDay(range.start)+' — '+formatDay(range.end,{day:'numeric',month:'long',year:'numeric'}):formatDay(anchor,{month:'long',year:'numeric'})}</h3><button onClick={()=>selectDate(today)}>Сегодня</button></div><div className="tabs">{(['Месяц','Неделя','Список'] as const).map(item=><button key={item} className={view===item?'selected':''} onClick={()=>setView(item)}>{item==='Список'&&<List size={14}/>} {item}</button>)}</div></div>
  <div className="calendar-filters"><label>Дата<input aria-label="Перейти к дате" type="date" value={anchor} onChange={event=>selectDate(event.target.value)}/></label><label>Сотрудник<Select value={filters.owner} onChange={event=>setFilters(value=>({...value,owner:event.target.value}))}><option value="Все">Все сотрудники</option>{ownerOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}{filters.owner!=='Все'&&!ownerOptions.some(([id])=>id===filters.owner)&&<option value={filters.owner}>Сохранённый сотрудник</option>}</Select></label><label>Тип события<Select value={filters.source} onChange={event=>setFilters(value=>({...value,source:event.target.value}))}><option value="Все">Все источники</option>{sourceOptions.map(([key,source])=><option value={key} key={key}>{source.label}</option>)}</Select></label><label>Статус<Select value={filters.state} onChange={event=>setFilters(value=>({...value,state:event.target.value}))}>{['Все','Активные','Завершённые / отменённые'].map(value=><option key={value}>{value}</option>)}</Select></label><SearchField value={search} set={setSearch} placeholder="Поиск события или клиента"/>{(filters.source!=='Все'||filters.owner!=='Все'||filters.state!=='Все'||search)&&<button onClick={()=>{setFilters({source:'Все',owner:'Все',state:'Все'});setSearch('')}}>Сбросить</button>}</div>
  <div className="calendar-caption"><span>{periodEvents.length} событий за период · {timeZone}</span><button data-permission="export" disabled={!canExport||!periodEvents.length} onClick={()=>{if(canExport)exportCSV('calendar-'+range.start+'.csv',['Дата','Время','Событие','Источник','Ответственный','Статус'],periodEvents.map(event=>[event.date,event.time,event.title,calendarSources[event.source].label,event.owner,event.status]))}}><Download size={14}/>Экспорт</button></div>
  {view==='Список'?<div className="calendar-list">{[...new Set(periodEvents.map(event=>event.date))].map(date=><section className="panel calendar-list-day" key={date}><header><h3>{formatDay(date,{weekday:'short',day:'numeric',month:'long'})}</h3><small>{date===today?'Сегодня':''}</small><button data-permission="create" disabled={!canCreate} aria-label={'Добавить событие '+date} onClick={()=>add(date)}><Plus size={14}/></button></header>{periodEvents.filter(event=>event.date===date).map(event=>eventButton(event))}</section>)}{!periodEvents.length&&<section className="panel empty"><CalendarDays size={28}/><p>В этом месяце нет событий по выбранным фильтрам.</p><button data-permission="create" disabled={!canCreate} onClick={()=>add()}>Добавить событие</button></section>}</div>:<div className="calendar-main"><div className="calendar-grid-scroll"><div className={'calendar-board '+(view==='Неделя'?'week-board':'month-board')}>{weekdays.map(day=><div key={day} className="calendar-week-label">{day}</div>)}{range.days.map(date=>{const items=filtered.filter(event=>event.date===date);return <section key={date} className={'calendar-day-cell '+(date===today?'is-today ':'')+(date===selectedDate?'is-selected ':'')+(view==='Месяц'&&date.slice(0,7)!==anchor.slice(0,7)?'outside-month':'')}><header><button aria-label={'Показать события '+date} aria-pressed={date===selectedDate} onClick={()=>selectDate(date)}><time dateTime={date}>{Number(date.slice(-2))}</time>{view==='Неделя'&&<small>{formatDay(date,{month:'short'})}</small>}</button><button data-permission="create" disabled={!canCreate} aria-label={'Добавить событие '+date} onClick={()=>add(date)}><Plus size={13}/></button></header><div>{(view==='Месяц'?items.slice(0,3):items).map(event=>eventButton(event,true))}</div>{view==='Месяц'&&items.length>3&&<button className="calendar-more" onClick={()=>selectDate(date)}>Ещё {items.length-3}</button>}</section>})}</div></div><aside className="panel calendar-day-agenda"><div className="row-between"><div><small>{selectedDate===today?'Сегодня':'События дня'}</small><h3>{formatDay(selectedDate,{day:'numeric',month:'long'})}</h3></div><button data-permission="create" disabled={!canCreate} aria-label="Добавить событие выбранного дня" onClick={()=>add()}><Plus size={16}/></button></div>{dayEvents.length?dayEvents.map(event=>eventButton(event)):<p className="calendar-empty-day">На этот день ничего не запланировано по выбранным фильтрам.</p>}</aside></div>}
  <div className="calendar-source-legend">{sourceOptions.map(([key,source])=><button key={key} aria-pressed={filters.source===key} className={filters.source===key?'selected':''} onClick={()=>setFilters(value=>({...value,source:value.source===key?'Все':key}))}><i style={{background:source.color}}/>{source.label}</button>)}</div>
  <p className="calendar-footnote">Показываются записи с указанной датой. Задачи без срока остаются в разделе «Задачи». Время продаж пересчитано в часовой пояс компании.</p>
  {formOpen&&<Modal title={editing?'Изменить событие':'Новое событие'} close={()=>setFormOpen(false)}><form data-permission={editing?'edit':'create'} onSubmit={event=>{event.preventDefault();save(event.currentTarget)}}><fieldset disabled={editing?!canEdit:!canCreate} className="calendar-form-fields"><label>Название<input name="name" required autoFocus defaultValue={editing?.name||''} placeholder="О чём нужно помнить"/></label><div className="form-grid"><label>Дата<input name="date" type="date" required value={formDate} onChange={event=>setFormDate(event.target.value)}/></label><label>Тип<Select name="channel" defaultValue={editing?.channel||types[0]}>{[...new Set([...types,...(editing?.channel?[editing.channel]:[])])].map(value=><option key={value}>{value}</option>)}</Select></label></div><label className="check-label"><input type="checkbox" checked={allDay} onChange={event=>setAllDay(event.target.checked)}/>Весь день</label>{!allDay&&<div className="form-grid"><label>Начало<input name="time" type="time" required value={formTime} onChange={event=>setFormTime(event.target.value)}/></label><label>Окончание<input name="endTime" type="time" value={formEndTime} onChange={event=>setFormEndTime(event.target.value)}/></label></div>}<label>Ответственный<Select name="owner" defaultValue={editing?.owner||editing?.employeeId?planningPersonKey(people,editing.owner,editing.employeeId):'__none'}><option value="__none">Не назначен</option>{formOwners.map(person=><option key={person.value} value={person.value}>{person.name}</option>)}</Select></label><label>Статус<Select name="status" defaultValue={editing?.status||statuses[0]}>{[...new Set([...statuses,...(editing?.status?[editing.status]:[])])].map(value=><option key={value}>{value}</option>)}</Select></label><label>Место / ссылка на встречу<input name="location" defaultValue={editing?.location||''} placeholder="Офис, кабинет или ссылка"/></label><label>Описание<textarea name="note" defaultValue={editing?.note||''}/></label></fieldset><div className="modal-footer"><button type="button" onClick={()=>setFormOpen(false)}>Отмена</button><button className="primary" disabled={editing?!canEdit:!canCreate}>Сохранить</button></div></form></Modal>}
  {detail&&<Drawer title={detail.title} close={()=>setDetailId('')}><div className="calendar-detail-source"><Badge>{calendarSources[detail.source].label}</Badge><Badge tone={detail.completed?'green':''}>{detail.status}</Badge></div><dl className="calendar-detail-list"><div><CalendarDays size={18}/><dt>Дата</dt><dd>{formatDay(detail.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</dd></div><div><Clock size={18}/><dt>Время</dt><dd>{detail.time?detail.time+(detail.endTime?' — '+detail.endTime:''):'Весь день'}</dd></div><div><UserRound size={18}/><dt>Ответственный</dt><dd>{detail.owner}</dd></div>{detail.location&&<div><MapPin size={18}/><dt>Место</dt><dd>{detail.location}</dd></div>}{detail.amount!==undefined&&<div><CheckCircle2 size={18}/><dt>Сумма</dt><dd>{money(detail.amount)}</dd></div>}</dl>{detail.note&&<p className="calendar-detail-note">{detail.note}</p>}{detail.source==='calendar'?<div className="row"><button data-permission="edit" disabled={!canEdit} className="primary" onClick={()=>{const record=ownRecords.find(item=>item.id===detail.recordId);if(record)edit(record)}}><Pencil size={15}/>Изменить</button><button data-permission="remove" disabled={!canRemove} onClick={()=>{setRemoveId(detail.recordId);setDetailId('')}}><Trash2 size={15}/>Удалить</button></div>:<><p className="calendar-footnote">Запись связана с рабочим разделом. Изменения в нём автоматически отразятся в календаре.</p><button onClick={()=>{setDetailId('');go(calendarSources[detail.source].route)}}>Открыть исходный раздел <ArrowUpRight size={15}/></button></>}</Drawer>}
  {removeId&&<Modal title="Удалить событие?" close={()=>setRemoveId('')}><p>«{ownRecords.find(record=>record.id===removeId)?.name}» будет удалено из календаря.</p><div className="modal-footer"><button onClick={()=>setRemoveId('')}>Отмена</button><button data-permission="remove" disabled={!canRemove} className="danger" onClick={()=>{if(!canRemove)return;setBusiness(value=>({...value,calendar:(value.calendar||[]).filter(record=>record.id!==removeId)}));audit('Удалено событие: '+ownRecords.find(record=>record.id===removeId)?.name);setRemoveId('');notify('Событие удалено')}}>Удалить</button></div></Modal>}
 </div>;
}
