'use client';
import {useState} from 'react';
import {ShoppingBag,MessageSquare,CalendarDays,Ticket,ArrowUpRight} from 'lucide-react';
import type {Entity} from '../lib/os/data';
import {money} from '../lib/os/data';
import {dealPipeline} from '../lib/os/deals';
import type {Sale} from '../lib/os/inventory-model';
import type {CalendarConsultation} from '../lib/os/calendar';
import {customerDealIds,customerPurchaseSummary,customerSales,type CustomerCoupon} from '../lib/os/customer-relations';
import {customerAIEvents} from '../lib/os/customer-ai-events';
import type {BotReplyDraft,BotReplyFeedback} from '../lib/os/bot-reply-approval';
import {useStored} from '../lib/os/storage';
import {Modal} from '../components/os/ui';
import Select from '../components/os/Select';
import './Customer360.css';
type Props={customer:Entity;deals:Entity[];sales:Sale[];tasks:Entity[];appointments:CalendarConsultation[];canReadSales:boolean;canReadDialogs:boolean;canReadTasks:boolean;canReadAppointments:boolean;canEdit:boolean;onDialog:(id:string)=>void;onDeal:(id:string)=>void;onTask:(id:string)=>void;onSale:(customerId:string)=>void;onAppointments:(customerId:string)=>void;notify:(text:string)=>void;audit:(text:string,id?:string)=>void};
export default function Customer360(p:Props){
 const id=p.customer.customerId||p.customer.id;
 const [tab,setTab]=useState('Сводка'),[receipt,setReceipt]=useState<Sale|null>(null),[addingCoupon,setAddingCoupon]=useState(false),[error,setError]=useState('');
 const [coupons,setCoupons]=useStored<CustomerCoupon[]>('customer-coupons-v1',[]);
 const [replyDrafts]=useStored<Record<string,BotReplyDraft>>('bot-reply-drafts-v1',{}),[replyFeedback]=useStored<BotReplyFeedback[]>('bot-reply-feedback-v1',[]);
 const ids=customerDealIds(p.deals,id),deals=p.deals.filter(deal=>ids.includes(deal.id));
 const aiEvents=customerAIEvents(id,ids,replyDrafts,replyFeedback,p.canReadDialogs);
 const purchases=p.canReadSales?customerSales(p.sales,id):[],summary=customerPurchaseSummary(purchases,id);
 const tasks=p.canReadTasks?p.tasks.filter(task=>task.clientId===id||Boolean(task.dealId&&ids.includes(task.dealId))):[];
 const appointments=p.canReadAppointments?p.appointments.filter(item=>item.clientId===id||Boolean(item.clientId&&ids.includes(item.clientId))):[];
 const available=['Сводка','Сделки',...(p.canReadSales?['Покупки']:[]),...(p.canReadDialogs?['Диалоги','AI события']:[]),...(p.canReadAppointments?['Записи']:[]),...(p.canReadTasks?['Задачи']:[]),'Купоны'];
 const current=available.includes(tab)?tab:'Сводка';
 const customerCoupons=coupons.filter(coupon=>coupon.customerId===id);
 return <section className="customer-360" aria-label="Связанные данные клиента">
  <div className="customer-summary"><button disabled={!p.canReadSales} onClick={()=>setTab('Покупки')}><small>Покупки за всё время</small><strong>{p.canReadSales?money(summary.spent):'Нет доступа'}</strong>{p.canReadSales&&<span>{summary.count} чеков · {summary.products.length} товаров <ArrowUpRight size={14}/></span>}</button><div><small>Открытые сделки</small><strong>{deals.filter(deal=>!['Успешно','Неуспешно'].includes(dealPipeline(deal))).length}</strong><span>История связана с этим клиентом</span></div></div>
  <div className="tabs customer-linked-tabs">{available.map(name=><button key={name} className={current===name?'selected':''} onClick={()=>setTab(name)}>{name}</button>)}</div>
  {current==='Сводка'&&<div className="customer-links">{p.canReadDialogs&&<button onClick={()=>p.onDialog(ids[0]||p.customer.id)}><MessageSquare size={18}/><span>Открыть диалог<small>{p.customer.channel} · {p.customer.phone||p.customer.username||'Контакт не указан'}</small></span><ArrowUpRight size={15}/></button>}{p.canReadSales&&<button onClick={()=>p.onSale(id)}><ShoppingBag size={18}/><span>Новая покупка<small>Клиент сразу выбран в кассе</small></span><ArrowUpRight size={15}/></button>}{p.canReadAppointments&&<button onClick={()=>p.onAppointments(id)}><CalendarDays size={18}/><span>Записать клиента<small>Встреча, процедура, звонок или услуга</small></span><ArrowUpRight size={15}/></button>}<p className="muted">{p.customer.note||'Заметок пока нет.'}</p></div>}
  {current==='Сделки'&&<div>{deals.map(deal=><button className="customer-related-row" key={deal.id} onClick={()=>p.onDeal(deal.id)}><span><b>{deal.name}</b><small>{deal.pipeline||'Продажи'} · {deal.status} · {deal.owner||'Не назначен'}</small></span><strong>{money(deal.value)}</strong><ArrowUpRight size={14}/></button>)}</div>}
  {current==='Покупки'&&<>{purchases.length?<div className="customer-receipts">{purchases.map(sale=><button key={sale.id} className="customer-related-row" onClick={()=>setReceipt(sale)}><ShoppingBag size={17}/><span><b>{sale.id}</b><small>{new Date(sale.date).toLocaleDateString('ru-RU')} · {sale.items.length} позиций · {sale.status}</small></span><strong>{money(sale.total-sale.refunds)}</strong><ArrowUpRight size={14}/></button>)}</div>:<p className="muted">Покупок пока нет. Создайте продажу в кассе и привяжите этого клиента.</p>}</>}
  {current==='Диалоги'&&<div>{deals.map(deal=><button className="customer-related-row" key={deal.id} onClick={()=>p.onDialog(deal.id)}><MessageSquare size={17}/><span><b>{deal.channel}</b><small>{deal.phone||deal.username||deal.name} · {deal.status}</small></span><ArrowUpRight size={14}/></button>)}</div>}
  {current==='Записи'&&<>{appointments.length?appointments.map(item=><div className="customer-related-row" key={item.id}><CalendarDays size={17}/><span><b>{item.date} · {item.time}</b><small>{item.note||'Запись'} · {item.employee} · {item.status}</small></span></div>):<p className="muted">Записей нет.</p>}<button onClick={()=>p.onAppointments(id)}>Открыть записи клиента</button></>}
  {current==='Задачи'&&<>{tasks.length?tasks.map(task=><button className="customer-related-row" key={task.id} onClick={()=>p.onTask(task.id)}><span><b>{task.name}</b><small>{task.status} · {task.owner} · {task.nextTaskAt||'Без срока'}</small></span><ArrowUpRight size={14}/></button>):<p className="muted">Связанных задач пока нет. Выберите клиента или сделку при создании задачи.</p>}</>}
  {current==='AI события'&&<div><p className="muted">Сохранённые ответы и обратная связь по связанным диалогам.</p>{aiEvents.map(event=><article key={event.id} className="customer-ai-event"><div className="row-between"><b>{event.type}</b><small>{new Date(event.at).toLocaleString('ru-RU')}</small></div><small>{event.agent}</small><p style={{whiteSpace:'pre-wrap'}}>{event.text}</p><button onClick={()=>p.onDialog(event.dealId)}>Открыть диалог</button></article>)}{!aiEvents.length&&<p className="muted">Сохранённых AI событий этого клиента пока нет.</p>}</div>}
  {current==='Купоны'&&<><div className="row-between"><p>Персональные скидки</p><button disabled={!p.canEdit} data-permission="edit" onClick={()=>{if(p.canEdit){setError('');setAddingCoupon(true)}}}><Ticket size={15}/>Добавить купон</button></div><small className="muted">Купоны можно применять повторно до указанной даты. Доступны только этому клиенту.</small>{customerCoupons.map(coupon=><div className="customer-related-row" key={coupon.id}><Ticket size={17}/><span><b>{coupon.code} · {coupon.kind==='percent'?coupon.value+'%':money(coupon.value)}</b><small>{coupon.active?'Активен':'Отключён'} · {coupon.expiresAt?'до '+coupon.expiresAt:'без срока'}</small></span><button disabled={!p.canEdit} data-permission="edit" onClick={()=>{if(!p.canEdit)return;setCoupons(all=>all.map(item=>item.id===coupon.id?{...item,active:!item.active}:item));p.audit('Изменён купон '+coupon.code,id)}}>{coupon.active?'Отключить':'Включить'}</button></div>)}</>}
  {receipt&&p.canReadSales&&<Modal title={'Чек '+receipt.id} close={()=>setReceipt(null)}><p>{new Date(receipt.date).toLocaleString('ru-RU')} · {receipt.status}</p><div className="table-scroll"><table><thead><tr><th>Товар</th><th>Количество</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>{receipt.items.map(item=><tr key={item.productId}><td>{item.name}{item.returned>0&&<small>Возвращено: {item.returned}</small>}</td><td>{item.quantity}</td><td>{money(item.price)}</td><td>{money(item.price*item.quantity)}</td></tr>)}</tbody></table></div><div className="customer-receipt-total"><span>Скидка {money(receipt.discount)}</span><strong>Оплачено {money(receipt.total)}</strong>{receipt.refunds>0&&<span>Возвраты {money(receipt.refunds)}</span>}</div></Modal>}
  {addingCoupon&&<Modal title="Персональный купон" close={()=>setAddingCoupon(false)}><form data-permission="edit" onSubmit={event=>{event.preventDefault();if(!p.canEdit)return;const form=new FormData(event.currentTarget),kind=form.get('kind') as CustomerCoupon['kind'],value=Number(form.get('value')),expiresAt=String(form.get('expiresAt')||'');if(!Number.isFinite(value)||value<=0||(kind==='percent'&&value>100)){setError('Укажите положительную скидку; процент не больше 100.');return}const coupon={id:crypto.randomUUID(),customerId:id,code:'OS-'+crypto.randomUUID().slice(0,8).toUpperCase(),kind,value,expiresAt,active:true};setCoupons(all=>[coupon,...all]);p.audit('Создан персональный купон '+coupon.code,id);p.notify('Купон доступен в кассе для этого клиента');setAddingCoupon(false)}}><label>Тип скидки<Select name="kind"><option value="percent">Процент</option><option value="fixed">Сумма в сомах</option></Select></label><label>Размер скидки<input name="value" type="number" min="0.01" step="0.01" required/></label><label>Действует до<input name="expiresAt" type="date"/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={!p.canEdit}>Создать купон</button></form></Modal>}
 </section>;
}
