'use client';
import {useState} from 'react';
import {ClipboardList,Plus,MessageSquare,ShoppingBag,CheckCircle2,Pencil,Clock} from 'lucide-react';
import {useStored} from '../lib/os/storage';
import {initialEmployees,type ActionPermissions} from '../lib/os/team';
import {initialTasks} from '../lib/os/data';
import {initialInventory} from '../lib/os/inventory-model';
import type {ChatMessage} from '../lib/os/conversations';
import {canReviewEmployeeReports,employeeReportDate,employeeReportMetrics,employeeShifts,employeeTasks,saveEmployeeReport,visibleEmployeeReports,type EmployeeReport,type EmployeeMetrics,type ReportPeriod} from '../lib/os/employee-reports';
import {Modal,Badge} from '../components/os/ui';
import Select from '../components/os/Select';
import './EmployeeReports.css';

type Props={employeeId?:string;targetEmployeeId?:string;permissions?:ActionPermissions;notify:(message:string)=>void;audit:(message:string)=>void};
const metricLabels={replies:'Ответов клиентам',sales:'Чеков',openTasks:'Открытых задач',completedTasks:'Выполненных задач'};
function Metrics({metrics}:{metrics:EmployeeMetrics}){return <div className="employee-report-metrics">{(Object.keys(metricLabels) as (keyof typeof metricLabels)[]).map(key=><div key={key}><small>{metricLabels[key]}</small><strong>{metrics[key]}</strong></div>)}</div>}

export default function EmployeeReports({employeeId='owner-user',targetEmployeeId='',permissions,notify,audit}:Props){
 const [employees]=useStored('team-employees-v3',initialEmployees),[reports,setReports]=useStored<EmployeeReport[]>('employee-reports-v1',[]);
 const [messages]=useStored<Record<string,ChatMessage[]>>('messages',{}),[inventory]=useStored('inventory-v2',initialInventory),[tasks]=useStored('tasks',initialTasks);
 const actor={employeeId,permissions},canReview=canReviewEmployeeReports(actor,employees),canCreate=permissions?.create??employeeId==='owner-user',canEdit=permissions?.edit??employeeId==='owner-user';
 const [selectedId,setSelectedId]=useState(targetEmployeeId||employeeId),[period,setPeriod]=useState<ReportPeriod>(()=>({kind:'day',date:employeeReportDate(new Date())}));
 const [formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<EmployeeReport|null>(null),[error,setError]=useState('');
 const currentId=canReview?selectedId:employeeId,employee=employees.find(person=>person.id===currentId),me=employees.find(person=>person.id===employeeId&&person.status==='Активен'),own=currentId===employeeId;
 const context={messages,sales:inventory.sales,shifts:inventory.shifts,tasks},today=employeeReportDate(new Date());
 const ownShifts=employee?employeeShifts(employee,employees,inventory.shifts):[],ownTasks=employee?employeeTasks(employee,employees,tasks):[];
 const visible=visibleEmployeeReports(reports,actor,employees,currentId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
 let metrics:EmployeeMetrics|undefined,metricsError='';
 if(employee)try{metrics=employeeReportMetrics(employee,employees,context,period,new Date().toISOString())}catch(error){metricsError=error instanceof Error?error.message:'Выберите период'}
 function save(form:HTMLFormElement){
  if(!own)return;
  const data=new FormData(form);
  try{const next=saveEmployeeReport(reports,{...(editing||period),id:editing?.id||crypto.randomUUID(),employeeId,results:String(data.get('results')||''),comment:String(data.get('comment')||'')},actor,employees,context,new Date().toISOString());setReports(next);setFormOpen(false);setEditing(null);setError('');audit((editing?'Исправлен':'Отправлен')+' личный отчёт: '+employee?.name);notify('Отчёт сохранён вместе с показателями')}catch(error){setError(error instanceof Error?error.message:'Не удалось сохранить отчёт')}
 }
 if(!me)return <section className="panel empty">Личные отчёты недоступны для этого аккаунта.</section>;
 return <div className="employee-reports"><header className="employee-reports-heading"><div><span><ClipboardList size={18}/>Работа и результаты</span><h1>{own?'Мои отчёты':'Отчёты сотрудника'}</h1><p>Итоги дня или смены, комментарий и показатели из сохранённых операций.</p></div>{own&&<button data-permission="create" className="primary" disabled={!canCreate||Boolean(metricsError)} onClick={()=>{if(!canCreate||metricsError)return;setEditing(null);setError('');setFormOpen(true)}}><Plus size={16}/>Отправить отчёт</button>}</header>
  <div className="panel employee-reports-toolbar">{canReview&&<label>Сотрудник<Select value={currentId} onChange={event=>{setSelectedId(event.target.value);setPeriod({kind:'day',date:today});setFormOpen(false);setEditing(null)}}>{employees.map(person=><option key={person.id} value={person.id}>{person.name}{person.id===employeeId?' · я':''}</option>)}</Select></label>}<label>Период<Select value={period.kind} onChange={event=>setPeriod({kind:event.target.value as ReportPeriod['kind'],date:period.date,shiftId:event.target.value==='shift'?ownShifts[0]?.id:undefined})}><option value="day">За день</option><option value="shift">За кассовую смену</option></Select></label>{period.kind==='day'?<label>Дата<input type="date" max={today} value={period.date} onChange={event=>setPeriod(value=>({...value,date:event.target.value}))}/></label>:<label>Смена<Select value={period.shiftId||''} onChange={event=>setPeriod(value=>({...value,shiftId:event.target.value}))}><option value="">Выберите свою смену</option>{ownShifts.map(shift=><option key={shift.id} value={shift.id}>{employeeReportDate(shift.opened)} · {shift.register}{shift.closed?' · закрыта':' · открыта'}</option>)}</Select></label>}</div>
  {!employee?<div className="panel empty">Сотрудник недоступен.</div>:<>{metrics&&<Metrics metrics={metrics}/>}<p className="employee-report-explanation"><MessageSquare size={15}/>Ответы и чеки относятся к выбранному периоду. Задачи показывают состояние сейчас. Сообщения без автора и операции без однозначного сотрудника не учитываются.</p>{metricsError&&<p className="form-error" role="alert">{metricsError}</p>}<section className="panel employee-report-tasks"><h2><CheckCircle2 size={17}/>Задачи · {ownTasks.length}</h2>{ownTasks.map(task=><div className="report-row" key={task.id}><span>{task.name}</span><Badge>{task.status}</Badge></div>)}{!ownTasks.length&&<p className="muted">Назначенных задач нет.</p>}</section><section className="employee-report-history"><h2><Clock size={18}/>Отправленные отчёты · {visible.length}</h2>{visible.map(report=><article className="panel employee-report-card" key={report.id}><header><div><b>{report.kind==='day'?'День':'Смена'} · {report.date}</b><small>Отправлен {new Date(report.submittedAt).toLocaleString('ru-RU')}{report.updatedAt!==report.submittedAt?' · исправлен '+new Date(report.updatedAt).toLocaleString('ru-RU'):''}</small></div>{own&&<button data-permission="edit" disabled={!canEdit} aria-label={'Исправить отчёт '+report.date} onClick={()=>{if(!canEdit)return;setEditing(report);setError('');setFormOpen(true)}}><Pencil size={15}/></button>}</header><Metrics metrics={report.metrics}/><h3>Результаты</h3><p>{report.results}</p>{report.comment&&<><h3>Комментарий</h3><p>{report.comment}</p></>}{report.revisions.length>0&&<details><summary>История исправлений · {report.revisions.length}</summary>{report.revisions.map((revision,index)=><section key={revision.at+index}><small>{new Date(revision.at).toLocaleString('ru-RU')}</small><p>{revision.results}</p>{revision.comment&&<p>{revision.comment}</p>}<small>{revision.metrics.replies} ответов · {revision.metrics.sales} чеков · {revision.metrics.openTasks} открытых задач</small></section>)}</details>}</article>)}{!visible.length&&<div className="panel empty"><ClipboardList size={26}/><p>Отправленных отчётов пока нет.</p></div>}</section></>}
  {formOpen&&own&&<Modal title={editing?'Исправить свой отчёт':'Отправить свой отчёт'} close={()=>setFormOpen(false)}><form data-permission={editing?'edit':'create'} onSubmit={event=>{event.preventDefault();save(event.currentTarget)}}><p>{editing?editing.date:period.kind==='shift'?employeeReportDate(ownShifts.find(shift=>shift.id===period.shiftId)?.opened||''):period.date} · {(editing?.kind||period.kind)==='day'?'за день':'за смену'}</p><label>Что сделано и какой результат<textarea required name="results" rows={5} autoFocus defaultValue={editing?.results} placeholder="Завершённые задачи, работа с клиентами, результаты смены"/></label><label>Комментарий<textarea name="comment" rows={3} defaultValue={editing?.comment} placeholder="Сложности, вопросы, что нужно передать следующей смене"/></label><p className="employee-report-explanation"><ShoppingBag size={15}/>При сохранении прикрепятся текущие счётчики ответов, чеков и задач. Общая выручка в отчёт не попадает.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={()=>setFormOpen(false)}>Отмена</button><button className="primary" disabled={editing?!canEdit:!canCreate}>{editing?'Сохранить исправление':'Отправить отчёт'}</button></div></form></Modal>}
 </div>;
}
