'use client';
import {useEffect,useRef,useState} from 'react';
import {Bot,Send,X,Sparkles,ScanLine} from 'lucide-react';
import {assistantTargets,demoAssistant,validAssistantAction,type AssistantAction,type AssistantResponse} from '../lib/os/assistant';
type Message={role:'user'|'assistant';text:string};
export default function HeaderAssistant({go}:{go:(route:string)=>void}){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Помогу найти страницу или компонент CRM. Например: «Покажи выбор воронки».'}]),[target,setTarget]=useState<keyof typeof assistantTargets|null>(null),[rect,setRect]=useState<{top:number;left:number;width:number;height:number}|null>(null);const end=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const goRef=useRef(go);goRef.current=go;
 const execute=(action:AssistantAction)=>{setTarget(null);setRect(null);if(timer.current)clearTimeout(timer.current);if(action.type==='navigate'){goRef.current(action.route);return;}const selected=action.target;goRef.current(assistantTargets[selected].route);timer.current=setTimeout(()=>{const el=document.querySelector<HTMLElement>(`[data-ai-target="${selected}"]`);if(!el){setMessages(m=>[...m,{role:'assistant',text:'Компонент сейчас недоступен. Открыл нужную страницу.'}]);return;}el.scrollIntoView({behavior:'smooth',block:'center'});if(action.type==='open')el.click();setTarget(selected);},260);};
 useEffect(()=>{const receive=(event:Event)=>{const response=(event as CustomEvent<AssistantResponse>).detail;if(!response||typeof response.text!=='string'||!Array.isArray(response.actions))return;setOpen(true);setMessages(m=>[...m,{role:'assistant',text:response.text}]);const action=response.actions.find(validAssistantAction);if(action)execute(action);};window.addEventListener('life-assistant-response',receive);return()=>{window.removeEventListener('life-assistant-response',receive);if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(!target)return;const update=()=>{const el=document.querySelector<HTMLElement>(`[data-ai-target="${target}"]`);if(!el){setRect(null);return;}const r=el.getBoundingClientRect();setRect({top:r.top-5,left:r.left-5,width:r.width+10,height:r.height+10});};update();window.addEventListener('scroll',update,true);window.addEventListener('resize',update);const timeout=setTimeout(update,600);return()=>{clearTimeout(timeout);window.removeEventListener('scroll',update,true);window.removeEventListener('resize',update);};},[target]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[messages,open]);
 const submit=(text:string)=>{if(!text.trim())return;setInput('');const response=demoAssistant(text);setMessages(m=>[...m,{role:'user',text},{role:'assistant',text:response.text}]);response.actions.forEach(execute);};
 return <><button className="header-ai" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Bot size={17}/><span>AI помощник</span></button>{open&&<section className="header-ai-panel" aria-label="AI помощник"><header><div><Bot size={19}/><b>Помощник Businnes OS</b></div><button aria-label="Закрыть помощника" onClick={()=>{setOpen(false);setTarget(null);setRect(null);}}><X size={17}/></button></header><small className="assistant-demo"><Sparkles size={12}/>Демо · серверный AI ещё не подключён</small><div className="assistant-messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={'assistant-message '+m.role}>{m.text}</div>)}<div ref={end}/></div><div className="assistant-suggestions">{['Открой CRM','Покажи выбор воронки','Покажи фильтры аналитики','Создай сделку'].map(s=><button key={s} onClick={()=>submit(s)}>{s}</button>)}</div><form onSubmit={e=>{e.preventDefault();submit(input);}}><input aria-label="Сообщение AI помощнику" placeholder="Что открыть или показать?" value={input} onChange={e=>setInput(e.target.value)}/><button className="primary" aria-label="Отправить" disabled={!input.trim()}><Send size={16}/></button></form></section>}{target&&rect&&<div className="assistant-highlight" style={rect}><span><ScanLine size={13}/>{assistantTargets[target].label}<button aria-label="Убрать подсветку" onClick={()=>{setTarget(null);setRect(null);}}><X size={13}/></button></span></div>}</>;
}
