'use client';
import {useId,useState} from 'react';
import {Search,BookOpen,MessageCircle,LifeBuoy,Plus,Check} from 'lucide-react';
import {useStored} from '../lib/os/storage';
import NeutralArt from '../components/os/NeutralArt';
import {Modal,Badge} from '../components/os/ui';
const articles=[
 ['Начало работы','Как настроить workspace?','Откройте Настройки → Компания, заполните название, валюту и рабочие часы. Затем настройте палитру, команду и нужные модули.'],
 ['Доступ','Не получается войти','Во фронтенд-демо используйте любой корректный email и пароль от 8 символов либо кнопку «Посмотреть без регистрации». Настоящая авторизация появится с backend.'],
 ['Доступ','Как восстановить пароль?','На странице входа нажмите «Забыли пароль?». В демо используйте код 123456 или резервный код DEMO-RECOVERY. Письма пока не отправляются.'],
 ['CRM','Как перенести сделку?','Откройте CRM, выберите воронку и переместите карточку на нужный этап либо измените статус в карточке сделки.'],
 ['Товароучёт','Как оприходовать товары?','В разделе Товароучёт → Документы создайте приход, выберите товар, склад и количество, затем проведите документ. В демо изменится локальный остаток.'],
 ['Касса','Как начать продажу?','Откройте Касса → Смены, откройте смену. Добавьте товары в чек, укажите скидку и распределите оплату между наличными, картой и QR.'],
 ['Интеграции','Как настроить GREEN-API?','В Интеграциях выберите GREEN-API, укажите idInstance и параметры аккаунта, выберите события и маршрутизацию. Секреты в демо не сохраняются.'],
 ['Интеграции','Как подключить Telegram и Instagram?','Откройте карточку нужной интеграции и заполните настройки. Проверка формы локальная; webhook и проверка токенов будут на сервере.'],
 ['AI','Что делает лаборатория?','Позволяет менять промпт и память, тестировать демонстрационные ответы, редактировать их и сохранять настройки агента. Реальные запросы к моделям не выполняются.'],
 ['Сервер','Что показывает мониторинг?','CPU, RAM, диск, сеть, сервисы, контейнеры, базу, бэкапы, SSL, логи и зависимости. Сейчас все показатели демонстрационные.'],
 ['Данные','Где сохраняются изменения?','В localStorage текущего браузера. Очистка данных сайта удалит демонастройки. Экспортируйте важные настройки перед очисткой.'],
 ['Внешний вид','Как выбрать произвольный цвет?','Настройки → Внешний вид → Своя палитра. Нажмите на цвет, переместите точку, задайте оттенок полосой или введите HEX. Светлая и тёмная палитры настраиваются отдельно.']
];
function HelpArticle({category,title,body}:{category:string;title:string;body:string}){const [open,setOpen]=useState(false);const id=useId();return <section className={'panel help-article'+(open?' is-open':'')}><button className="help-question" id={id+'-question'} aria-expanded={open} aria-controls={id+'-answer'} onClick={()=>setOpen(v=>!v)}><BookOpen size={16}/><span><small>{category}</small>{title}</span><Plus className="help-plus" size={16}/></button><div className="help-answer" id={id+'-answer'} role="region" aria-labelledby={id+'-question'} aria-hidden={!open}><div><p>{body}</p></div></div></section>}
export default function HelpCenter({publicMode=false}:{publicMode?:boolean}){const [query,setQuery]=useState('');const [category,setCategory]=useState('Все');const [ticket,setTicket]=useState(false);const [saved,setSaved]=useState(false);const [tickets,setTickets]=useStored<{id:string;subject:string;message:string;date:string}[]>('support-tickets-v2',[]);const visible=articles.filter(a=>(!publicMode||['Доступ','Начало работы','Данные'].includes(a[0]))&&(category==='Все'||a[0]===category)&&a.join(' ').toLowerCase().includes(query.toLowerCase()));return <div className="studio-page help-page"><div className="help-hero"><div><Badge><LifeBuoy size={13}/>Центр помощи</Badge><h1>Найдём ответ вместе</h1><p>Инструкции по работе, доступу и настройкам.</p><label className="settings-search"><Search size={17}/><input aria-label="Поиск в помощи" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Что вы хотите узнать?"/></label></div><NeutralArt kind="help"/></div><div className="toolbar"><div className="tabs">{['Все',...new Set(articles.filter(a=>!publicMode||['Доступ','Начало работы','Данные'].includes(a[0])).map(a=>a[0]))].map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="help-articles">{visible.map(([c,title,body])=><HelpArticle key={title} category={c} title={title} body={body}/>)}{!visible.length&&<p>Ничего не найдено. Попробуйте другой запрос или оставьте обращение.</p>}</div><section className="panel help-contact"><MessageCircle size={26}/><div><h3>Нужна помощь с вашим случаем?</h3><p>Сохраните обращение в демопространстве.</p></div><button className="primary" onClick={()=>{setTicket(true);setSaved(false)}}>Создать обращение</button></section>{tickets.length>0&&<section className="panel"><h3>Локальные обращения</h3>{tickets.map(t=><div className="activity-row" key={t.id}><div><b>{t.subject}</b><small>{t.date} · Черновик, не отправлено</small><p>{t.message}</p></div></div>)}</section>}{ticket&&<Modal title="Обращение в поддержку" close={()=>setTicket(false)}>{saved?<div className="auth-success"><Check size={24}/><h3>Черновик сохранён</h3><p>Отправка в поддержку появится после подключения backend.</p><button onClick={()=>setTicket(false)}>Готово</button></div>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setTickets(v=>[{id:crypto.randomUUID(),subject:String(f.get('subject')),message:String(f.get('message')),date:new Date().toLocaleString('ru-RU')},...v]);setSaved(true)}}><label>Тема<input name="subject" required/></label><label>Опишите ситуацию<textarea name="message" required minLength={10}/></label><button className="primary">Сохранить черновик</button></form>}</Modal>}</div>}
