'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,CalendarDays,Heart,Minus,Moon,Package,Plus,Search,ShoppingBag,Sun,Trash2,Truck} from 'lucide-react';
import {useStored} from '../lib/os/storage';
import {useAppearance} from '../lib/os/appearance';
import {initialInventory,type Product} from '../lib/os/inventory-model';
import {calendarToday,initialCalendarConsultations} from '../lib/os/calendar';
import {initialStorefront,shopProducts,shopPrice,shopAvailable,shopDeliveries,shopPayments,shopStatuses,emptyCheckout,createShopOrder,shopConsultation,shopRecommendations,type ShopCart,type ShopCheckout,type ShopOrder} from '../lib/os/shop';
import {money} from '../lib/os/data';
import {Modal,Badge} from '../components/os/ui';
import Select from '../components/os/Select';
import './Shop.css';

export default function Shop(){
 const [theme,setTheme]=useStored('theme','Light');useAppearance(theme);
 const [inventory]=useStored('inventory-v2',initialInventory);
 const [settings]=useStored('storefront-v2',initialStorefront);
 const [orders,setOrders]=useStored<ShopOrder[]>('shop-orders-v1',[]);
 const [cart,setCart]=useStored<ShopCart>('shop-cart-v1',{});
 const [consultations,setConsultations]=useStored('consultations-v2',initialCalendarConsultations);
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[stockOnly,setStockOnly]=useState(false);
 const [cartOpen,setCartOpen]=useState(false),[consultOpen,setConsultOpen]=useState(false),[consultSent,setConsultSent]=useState(false);
 const [detail,setDetail]=useState<Product|null>(null),[placedId,setPlacedId]=useState('');
 const [checkout,setCheckout]=useState<ShopCheckout>(emptyCheckout),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const orderId=useRef('');
 const [advisorOpen,setAdvisorOpen]=useState(false),[advisorRequest,setAdvisorRequest]=useState(''),[advisorSubmitted,setAdvisorSubmitted]=useState(false);
 const products=shopProducts(inventory.products),count=Object.values(cart).reduce((sum,quantity)=>sum+quantity,0);
 const categories=[...new Set(products.map(product=>product.category).filter(Boolean))];
 const filtered=products.filter(product=>(!category||product.category===category)&&(!stockOnly||shopAvailable(product)>0)&&[product.name,product.sku,product.description].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const total=products.reduce((sum,product)=>sum+Math.round(shopPrice(product)*(cart[product.id]||0)*100),0)/100;
 const placed=orders.find(order=>order.id===placedId);
 function quantity(product:Product,value:number){setError('');setCart(current=>{const next={...current},quantity=Math.min(99,shopAvailable(product),Math.max(0,value));if(quantity)next[product.id]=quantity;else delete next[product.id];return next})}
 function add(product:Product){quantity(product,(cart[product.id]||0)+1);setNotice(product.name+' добавлен в корзину')}
 function openCart(){setNotice('');setError('');setPlacedId('');orderId.current=crypto.randomUUID();setCartOpen(true)}
 function submitOrder(){try{
  if(!settings.published)throw new Error('Приём заказов приостановлен.');
  const currentProducts=JSON.parse(localStorage.getItem('life-inventory-v2')||'null')?.products||inventory.products;
  const currentOrders:ShopOrder[]=JSON.parse(localStorage.getItem('life-shop-orders-v1')||'null')||orders;
  const next=createShopOrder(currentOrders,currentProducts,cart,checkout,orderId.current,new Date().toISOString());
  setOrders(next);setPlacedId(orderId.current);setCart({});setError('');
 }catch(error){setError(error instanceof Error?error.message:'Не удалось сохранить заказ.')}}
 const visual=(product:Product)=><div className="shop-product-visual">{product.image?<img src={product.image} alt={product.name} loading="lazy"/>:<Package size={48} strokeWidth={1}/>}<span>{product.category||'Каталог'}</span></div>;
 return <div className="shop-page">
  <header className="shop-header"><Link href="/shop" className="shop-brand"><span><ShoppingBag size={21}/></span>{settings.title}</Link><div className="row"><button aria-label="Переключить тему" onClick={()=>setTheme(theme==='Light'?'Dark':'Light')}>{theme==='Light'?<Moon size={17}/>:<Sun size={17}/>}</button><button className="primary" onClick={openCart}><ShoppingBag size={17}/>Корзина <b>{count}</b></button></div></header>
  <div className="shop-demo-note">Локальная витрина · заказы сохраняются в этом браузере, оплата не списывается</div>
  {settings.published?<main>
   <section className="shop-intro"><div><Badge>Ваш ежедневный уход</Badge><h1>Найдите то,<br/>что подходит вам.</h1><p>{settings.description}</p><button onClick={()=>{setConsultSent(false);setError('');setConsultOpen(true)}}><CalendarDays size={17}/>Записаться на консультацию <ArrowRight size={17}/></button></div><aside><Heart size={31} strokeWidth={1.25}/><h2>Подберём вместе</h2><p>Расскажите о своём запросе на консультации. Менеджер поможет выбрать средства и согласует удобное время.</p><div><span><Truck size={16}/>Доставка по согласованию</span><span><Package size={16}/>Остатки из товароучёта</span></div></aside></section>
   <section className="shop-catalog" aria-label="Каталог"><div className="shop-catalog-heading"><h2>Каталог <small>{filtered.length}</small></h2><button onClick={()=>{setAdvisorOpen(true);setAdvisorSubmitted(false)}}><Heart size={15}/>Помочь с выбором</button><label className="search-field"><Search size={17}/><input aria-label="Найти товар" placeholder="Название, артикул, описание" value={query} onChange={event=>setQuery(event.target.value)}/></label></div><div className="shop-categories"><button className={!category?'selected':''} onClick={()=>setCategory('')}>Все товары</button>{categories.map(value=><button key={value} className={value===category?'selected':''} onClick={()=>setCategory(value)}>{value}</button>)}<label className="check-label"><input type="checkbox" checked={stockOnly} onChange={event=>setStockOnly(event.target.checked)}/>В наличии</label></div>
    <div className="shop-product-grid">{filtered.map(product=><article className="shop-product" key={product.id}><button className="shop-product-open" aria-label={'Подробнее: '+product.name} onClick={()=>setDetail(product)}>{visual(product)}</button><div className="shop-product-content"><small>{product.sku} · {shopAvailable(product)>0?'В наличии: '+shopAvailable(product)+' '+product.unit:'Нет в наличии'}</small><button className="shop-product-title" onClick={()=>setDetail(product)}>{product.name}</button><div className="shop-product-bottom"><div><strong>{money(shopPrice(product))}</strong>{shopPrice(product)<product.price&&<del>{money(product.price)}</del>}</div><button disabled={!shopAvailable(product)||(cart[product.id]||0)>=Math.min(99,shopAvailable(product))} aria-label={'Добавить в корзину '+product.name} onClick={()=>add(product)}>{cart[product.id]?<Check size={17}/>:<Plus size={17}/>}</button></div></div></article>)}</div>
    {!filtered.length&&<div className="shop-empty"><Search size={30}/><h3>Ничего не найдено</h3><p>Измените запрос или выберите другую категорию.</p><button onClick={()=>{setQuery('');setCategory('');setStockOnly(false)}}>Сбросить фильтры</button></div>}
   </section>
  </main>:<main className="shop-empty"><ShoppingBag size={40}/><h1>Витрина готовится к открытию</h1><p>Владелец может включить её в товароучёте → Витрина.</p><Link className="button-link" href="/inventory/storefront">Перейти в управление</Link></main>}
  <footer className="shop-footer"><span>{settings.title}</span><span>Работает на Business OS</span></footer>
  {advisorOpen&&<Modal title="Поможем с выбором" close={()=>setAdvisorOpen(false)}><form onSubmit={event=>{event.preventDefault();setAdvisorSubmitted(true)}}><label>Что вы ищете?<textarea required minLength={5} maxLength={800} value={advisorRequest} onChange={event=>{setAdvisorRequest(event.target.value);setAdvisorSubmitted(false)}} placeholder="Например: очищение и защита от солнца"/></label><div className="shop-categories">{['Защита от солнца','Мягкое очищение','Увлажняющий крем'].map(request=><button type="button" key={request} onClick={()=>{setAdvisorRequest(request);setAdvisorSubmitted(false)}}>{request}</button>)}</div><button className="primary">Подобрать из каталога</button></form><p className="storefront-footnote">Локальный подбор по названиям и описаниям товаров. Модель AI не подключена; индивидуальный уход поможет выбрать консультант.</p>{advisorSubmitted&&<div className="shop-advisor-results">{shopRecommendations(products,advisorRequest).map(product=><article key={product.id}><div><b>{product.name}</b><small>{product.category} · {money(shopPrice(product))}</small></div><button onClick={()=>add(product)} disabled={(cart[product.id]||0)>=Math.min(99,shopAvailable(product))}><Plus size={15}/>В корзину</button></article>)}{!shopRecommendations(products,advisorRequest).length&&<p>Не нашли точного совпадения в каталоге. Уточните запрос или запишитесь на консультацию.</p>}</div>}</Modal>}
  {notice&&<div className="toast" role="status"><span>{notice}</span><button onClick={()=>{setNotice('');openCart()}}>Открыть корзину</button><button aria-label="Скрыть уведомление" onClick={()=>setNotice('')}>×</button></div>}
  {detail&&<Modal title={detail.name} close={()=>setDetail(null)}><div className="shop-detail">{visual(detail)}<p>{detail.description||'Уточните подробности у менеджера на консультации.'}</p><dl><div><dt>Артикул</dt><dd>{detail.sku}</dd></div>{detail.country&&<div><dt>Страна</dt><dd>{detail.country}</dd></div>}<div><dt>Наличие</dt><dd>{shopAvailable(detail)} {detail.unit}</dd></div></dl><div className="row-between"><strong>{money(shopPrice(detail))}</strong><button className="primary" disabled={!shopAvailable(detail)||(cart[detail.id]||0)>=Math.min(99,shopAvailable(detail))} onClick={()=>add(detail)}><Plus size={16}/>В корзину</button></div></div></Modal>}
  {cartOpen&&<Modal title={placed?'Заказ оформлен':'Ваша корзина'} close={()=>setCartOpen(false)} wide>
   {placed?<div className="shop-success"><div className="shop-success-mark"><Check size={30}/></div><h2>Спасибо, {placed.customerName}!</h2><p>Заказ №{placed.number} сохранён в витрине.</p><div className="shop-success-order"><Badge>{shopStatuses[placed.status]}</Badge><strong>{money(placed.total)}</strong><span>{shopDeliveries[placed.deliveryMethod]}</span></div><p>{placed.paymentMethod==='mbank_qr'?'Выбран MBANK QR. В демо платёж не выполняется; реквизиты согласует менеджер.':'Способ оплаты согласует менеджер.'}</p>{placed.deliveryMethod==='yandex'&&<p>Стоимость доставки рассчитывается после подтверждения и не включена в итог.</p>}<button className="primary" onClick={()=>setCartOpen(false)}>Продолжить покупки</button></div>:!count?<div className="shop-empty"><ShoppingBag size={32}/><h2>Здесь пока пусто</h2><button onClick={()=>setCartOpen(false)}>Перейти к каталогу</button></div>:<div className="shop-checkout"><div className="shop-cart-items">{Object.entries(cart).filter(([,quantity])=>quantity>0).map(([id,value])=>{const product=products.find(product=>product.id===id);return <article key={id}><div><b>{product?.name||'Товар недоступен'}</b><small>{product?money(shopPrice(product))+' / '+product.unit:'Удалите позицию перед оформлением'}</small>{product&&value>shopAvailable(product)&&<small className="form-error">Осталось {shopAvailable(product)} — измените количество</small>}</div><div className="shop-quantity"><button aria-label={'Уменьшить '+(product?.name||'количество')} onClick={()=>{if(product)quantity(product,value-1)}} disabled={!product}><Minus size={14}/></button><span>{value}</span><button aria-label={'Увеличить '+(product?.name||'количество')} disabled={!product||value>=Math.min(99,shopAvailable(product))} onClick={()=>{if(product)quantity(product,value+1)}}><Plus size={14}/></button></div><button aria-label={'Убрать '+(product?.name||'недоступный товар')} onClick={()=>setCart(current=>{const next={...current};delete next[id];return next})}><Trash2 size={15}/></button></article>})}</div>
    <form onSubmit={event=>{event.preventDefault();submitOrder()}}><h3>Оформление</h3><div className="form-grid"><label>Ваше имя<input required minLength={2} maxLength={120} autoComplete="name" value={checkout.customerName} onChange={event=>setCheckout(value=>({...value,customerName:event.target.value}))}/></label><label>Телефон<input required type="tel" autoComplete="tel" maxLength={30} value={checkout.phone} onChange={event=>setCheckout(value=>({...value,phone:event.target.value}))}/></label></div><div className="form-grid"><label>Получение<Select value={checkout.deliveryMethod} onChange={event=>setCheckout(value=>({...value,deliveryMethod:event.target.value as ShopCheckout['deliveryMethod']}))}>{Object.entries(shopDeliveries).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label><label>Оплата<Select value={checkout.paymentMethod} onChange={event=>setCheckout(value=>({...value,paymentMethod:event.target.value as ShopCheckout['paymentMethod']}))}>{Object.entries(shopPayments).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label></div>{checkout.deliveryMethod==='yandex'&&<label>Адрес доставки<input required minLength={5} maxLength={300} autoComplete="street-address" value={checkout.address} onChange={event=>setCheckout(value=>({...value,address:event.target.value}))}/></label>}<label>Комментарий<textarea maxLength={500} value={checkout.comment} onChange={event=>setCheckout(value=>({...value,comment:event.target.value}))} placeholder="Пожелания к заказу"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="shop-checkout-total"><span>Итого за товары</span><strong>{money(total)}</strong></div><small>Заявка сохраняется локально. Менеджер подтверждает наличие, оплату и доставку.</small><button className="primary" disabled={!settings.published}>Оформить заказ <ArrowRight size={17}/></button></form></div>}
  </Modal>}
  {consultOpen&&<Modal title="Запись на консультацию" close={()=>setConsultOpen(false)}>{consultSent?<div className="shop-success"><Check size={30}/><h2>Заявка сохранена</h2><p>Она появилась в консультациях и календаре команды. Время подтвердит менеджер.</p><button className="primary" onClick={()=>setConsultOpen(false)}>Готово</button></div>:<form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const record=shopConsultation({client:String(data.get('client')),phone:String(data.get('phone')),date:String(data.get('date')),time:String(data.get('time')),format:String(data.get('format')),concern:String(data.get('concern'))},crypto.randomUUID(),calendarToday('Asia/Bishkek'));setConsultations([...consultations,record]);setConsultSent(true);setError('')}catch(error){setError(error instanceof Error?error.message:'Проверьте поля')}}}><div className="form-grid"><label>Ваше имя<input name="client" minLength={2} maxLength={120} required autoComplete="name"/></label><label>Телефон<input name="phone" type="tel" maxLength={30} required autoComplete="tel"/></label></div><div className="form-grid"><label>Дата<input name="date" type="date" min={calendarToday('Asia/Bishkek')} required/></label><label>Время<input name="time" type="time" required/></label></div><label>Формат<Select name="format" defaultValue="Онлайн"><option>Онлайн</option><option>Офлайн</option></Select></label><label>Ваш запрос<textarea name="concern" minLength={5} maxLength={800} required placeholder="Что вы хотели бы обсудить?"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={()=>setConsultOpen(false)}><ArrowLeft size={15}/>Назад</button><button className="primary">Отправить заявку</button></div></form>}</Modal>}
 </div>;
}
