'use client';
import {useState} from 'react';
import {Plus,ShieldCheck,LockKeyhole} from 'lucide-react';
import {useStored} from '../lib/os/storage';
import {navigation} from '../lib/os/data';
import {initialEmployees,initialRoles,teamActions,type Employee,type TeamRole,type TeamAction} from '../lib/os/team';
import {Modal,Badge} from '../components/os/ui';
import Select from '../components/os/Select';
export default function TeamManagement({notify,audit,createSignal=0}:{notify:(s:string)=>void;audit:(s:string)=>void;createSignal?:number}){
 const [employees,setEmployees]=useStored('team-employees-v3',initialEmployees);const [roles,setRoles]=useStored('team-roles-v3',initialRoles);const [,setPreview]=useStored('team-preview-v3','');const [tab,setTab]=useState('Сотрудники');const [employee,setEmployee]=useState<Employee|null>(null);const [role,setRole]=useState<TeamRole|null>(null);const [password,setPassword]=useState<Employee|null>(null);const [confirm,setConfirm]=useState<{employee:Employee;status:Employee['status']}|null>(null);const [error,setError]=useState('');
 const addEmployee=()=>setEmployee({id:crypto.randomUUID(),name:'',email:'',position:'',role:'manager',status:'Активен'});
 const [lastSignal,setLastSignal]=useState(createSignal);if(createSignal!==lastSignal){setLastSignal(createSignal);setEmployee({id:crypto.randomUUID(),name:'',email:'',position:'',role:'manager',status:'Активен'})}
 function saveEmployee(form:HTMLFormElement){if(!employee)return;const f=new FormData(form);const email=String(f.get('email')).trim().toLowerCase();if(!String(f.get('name')).trim()){setError('Укажите имя сотрудника');return}if(employees.some(e=>e.id!==employee.id&&e.email.toLowerCase()===email)){setError('Этот email уже используется');return}const next={...employee,name:String(f.get('name')).trim(),email,position:String(f.get('position')),role:String(f.get('role'))};setEmployees(v=>v.some(e=>e.id===next.id)?v.map(e=>e.id===next.id?next:e):[...v,next]);setEmployee(null);setError('');audit('Сохранён сотрудник '+next.name);notify('Сотрудник сохранён')}
 return <div className="studio-page"><header className="studio-heading"><div><h1><ShieldCheck size={24}/>Команда и доступ</h1><p>Роли, разрешения и жизненный цикл аккаунтов.</p></div><button data-permission="manageTeam" className="primary" onClick={tab==='Сотрудники'?addEmployee:()=>setRole({id:crypto.randomUUID(),name:'',pages:['help'],actions:[]})}><Plus size={16}/>{tab==='Сотрудники'?'Добавить сотрудника':'Создать роль'}</button></header><div className="demo-strip">Настройки сохраняются локально. Серверная авторизация и смена настоящих паролей требуют backend.</div><div className="workspace-tabs">{['Сотрудники','Роли и разрешения'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Сотрудники'?<div className="cards-grid">{employees.map(e=><section className="panel team-card" key={e.id}><div className="row-between"><span className="avatar large">{e.name.slice(0,1)}</span><Badge tone={e.status==='Активен'?'green':'orange'}>{e.status}</Badge></div><h3>{e.name}</h3><p>{e.position} · {e.email}</p><Badge>{roles.find(r=>r.id===e.role)?.name||'Роль удалена'}</Badge><p>{roles.find(r=>r.id===e.role)?.pages.length||0} доступных страниц</p>{e.passwordChangedAt&&<small>Демо-смена пароля: {new Date(e.passwordChangedAt).toLocaleString('ru-RU')}</small>}<div className="row"><button data-permission="manageTeam" onClick={()=>{setEmployee(e);setError('')}}>Настроить</button><button onClick={()=>setPreview(e.id)}>Проверить доступ</button><button data-permission="manageTeam" disabled={e.status!=='Активен'} onClick={()=>{setPassword(e);setError('')}}><LockKeyhole size={14}/>Пароль</button>{e.id!=='owner-user'&&<><button data-permission="manageTeam" disabled={e.status==='Уволен'} onClick={()=>setConfirm({employee:e,status:e.status==='Заблокирован'?'Активен':'Заблокирован'})}>{e.status==='Заблокирован'?'Разблокировать':'Заблокировать'}</button><button data-permission="manageTeam" disabled={e.status==='Уволен'} onClick={()=>setConfirm({employee:e,status:'Уволен'})}>Уволить</button></>}</div></section>)}</div>:<div className="cards-grid">{roles.map(r=><section className="panel" key={r.id}><h3>{r.name}</h3><p>{r.pages.length} страниц · {r.actions.length} разрешений</p><div className="row">{r.actions.slice(0,3).map(a=><Badge key={a}>{teamActions[a]}</Badge>)}</div><button data-permission="manageTeam" onClick={()=>{setRole({...r,pages:[...r.pages],actions:[...r.actions]});setError('')}}>Настроить права</button><button data-permission="manageTeam" disabled={r.id==='owner'||employees.some(e=>e.role===r.id)} onClick={()=>setRoles(v=>v.filter(x=>x.id!==r.id))}>Удалить роль</button></section>)}</div>}
 {employee&&<Modal title={employee.name?'Настройка сотрудника':'Новый сотрудник'} close={()=>setEmployee(null)}><form data-permission="manageTeam" className="entity-form" onSubmit={e=>{e.preventDefault();saveEmployee(e.currentTarget)}}><label>Имя<input name="name" required defaultValue={employee.name}/></label><label>Email<input name="email" type="email" required defaultValue={employee.email}/></label><label>Должность<input name="position" defaultValue={employee.position}/></label><label>Роль<Select name="role" defaultValue={employee.role} disabled={employee.id==='owner-user'}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select>{employee.id==='owner-user'&&<input type="hidden" name="role" value="owner"/>}</label>{error&&<p role="alert">{error}</p>}<button data-permission="manageTeam" className="primary">Сохранить</button></form></Modal>}
 {role&&<Modal wide title="Разрешения роли" close={()=>setRole(null)}><form data-permission="manageTeam" className="entity-form" onSubmit={e=>{e.preventDefault();if(!role.name.trim()){setError('Укажите название роли');return}if(roles.some(r=>r.id!==role.id&&r.name.toLowerCase()===role.name.trim().toLowerCase())){setError('Название роли занято');return}setRoles(v=>v.some(r=>r.id===role.id)?v.map(r=>r.id===role.id?{...role,name:role.name.trim()}:r):[...v,{...role,name:role.name.trim()}]);audit('Обновлены права роли '+role.name);setRole(null);notify('Права сохранены')}}><label>Название роли<input required value={role.name} onChange={e=>setRole({...role,name:e.target.value})}/></label><h3>Доступные страницы</h3><div className="permission-grid">{navigation.map(([,id,name])=><label key={id}><input disabled={role.id==='owner'} type="checkbox" checked={role.pages.includes(id)} onChange={e=>setRole({...role,pages:e.target.checked?[...role.pages,id]:role.pages.filter(p=>p!==id)})}/>{name}</label>)}</div><h3>Что разрешено делать</h3><div className="permission-grid">{(Object.keys(teamActions) as TeamAction[]).map(a=><label key={a}><input disabled={role.id==='owner'} type="checkbox" checked={role.actions.includes(a)} onChange={e=>setRole({...role,actions:e.target.checked?[...role.actions,a]:role.actions.filter(x=>x!==a)})}/>{teamActions[a]}</label>)}</div>{error&&<p role="alert">{error}</p>}<button data-permission="manageTeam" className="primary">Сохранить роль</button></form></Modal>}
 {password&&<Modal title={'Пароль · '+password.name} close={()=>setPassword(null)}><form data-permission="manageTeam" className="entity-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('repeat')){setError('Пароли не совпадают');return}setEmployees(v=>v.map(x=>x.id===password.id?{...x,passwordChangedAt:new Date().toISOString(),forcePasswordChange:f.get('force')==='on'}:x));e.currentTarget.reset();setPassword(null);audit('Демо-смена пароля '+password.name);notify('Демо-смена сохранена. Настоящий пароль на сервере не изменялся')}}><p>Проверка интерфейса: пароль не сохраняется и не отправляется на сервер.</p><label>Новый пароль<input name="password" type="password" autoComplete="new-password" required minLength={12}/></label><label>Повторите пароль<input name="repeat" type="password" autoComplete="new-password" required minLength={12}/></label><label className="check-label"><input name="force" type="checkbox" defaultChecked/>Потребовать смену при следующем входе</label>{error&&<p role="alert">{error}</p>}<button data-permission="manageTeam" className="primary">Сменить пароль · демо</button></form></Modal>}
 {confirm&&<Modal title={confirm.status==='Уволен'?'Увольнение сотрудника':'Изменение доступа'} close={()=>setConfirm(null)}><p>{confirm.employee.name}: статус «{confirm.status}». {confirm.status!=='Активен'?'В предпросмотре все страницы будут заблокированы. История работы сохранится.':'Доступ по роли будет восстановлен.'}</p><button data-permission="manageTeam" className="primary" onClick={()=>{setEmployees(v=>v.map(e=>e.id===confirm.employee.id?{...e,status:confirm.status}:e));audit(confirm.employee.name+': '+confirm.status);setConfirm(null);notify('Статус аккаунта обновлён локально')}}>Подтвердить</button></Modal>}
 </div>
}
