'use client';
import {useState} from 'react';
import type {Node,Edge} from '@xyflow/react';
import {Modal} from '../components/os/ui';
import {useStored} from '../lib/os/storage';
import {downloadText} from '../lib/os/export';
import {validateWorkflow} from '../lib/os/workflow-validation';
type Snapshot={id:string;name:string;date:string;nodes:Node[];edges:Edge[]};
export default function WorkflowLibrary({nodes,edges,load,close,notify}:{nodes:Node[];edges:Edge[];load:(nodes:Node[],edges:Edge[])=>void;close:()=>void;notify:(s:string)=>void}){const [saved,setSaved]=useStored<Snapshot[]>('workflow-library-v1',[]);const [name,setName]=useState('Новый сценарий');const [preview,setPreview]=useState<string|null>(null);return <Modal title="Сценарии и версии" wide close={close}><form onSubmit={e=>{e.preventDefault();setSaved(v=>[{id:crypto.randomUUID(),name:name.trim(),date:new Date().toISOString(),nodes:structuredClone(nodes),edges:structuredClone(edges)},...v]);notify('Снимок сценария сохранён')}}><label>Название версии<input required value={name} onChange={e=>setName(e.target.value)}/></label><div className="row"><button className="primary">Сохранить версию</button><button type="button" onClick={()=>downloadText('workflow.json',JSON.stringify({version:1,nodes,edges},null,2),'application/json')}>Экспорт JSON</button><label className="button-link">Импорт JSON<input hidden type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.nodes)||!Array.isArray(data.edges)||data.nodes.some((n:Node)=>!n.id||!n.data||!n.position||!Number.isFinite(n.position.x)||!Number.isFinite(n.position.y)))throw Error();const problems=validateWorkflow(data.nodes,data.edges);if(problems.some(p=>p.includes('ID')||p.includes('отсутствующими')))throw Error();setSaved(v=>[{id:crypto.randomUUID(),name:'Импорт: '+file.name,date:new Date().toISOString(),nodes:data.nodes.map((n:Node)=>({...n,type:'agent'})),edges:data.edges},...v]);notify('Импортирован в библиотеку. Выберите «Открыть» для загрузки.')}catch{notify('Некорректный файл сценария')}e.target.value=''}}/></label></div></form><section className="workflow-snapshots">{saved.map(s=><article className="panel" key={s.id}><div className="row-between"><div><b>{s.name}</b><small>{new Date(s.date).toLocaleString('ru-RU')} · {s.nodes.length} блоков · {s.edges.length} связей</small></div><div className="row"><button onClick={()=>setPreview(preview===s.id?null:s.id)}>Проверить</button><button onClick={()=>{load(s.nodes,s.edges);close();notify('Сценарий загружен')}}>Открыть</button><button onClick={()=>setSaved(v=>v.filter(x=>x.id!==s.id))}>Удалить снимок</button></div></div>{preview===s.id&&<p>{validateWorkflow(s.nodes,s.edges).join('. ')||'Структура валидна'}</p>}</article>)}{!saved.length&&<p>Сохраните текущий сценарий, чтобы создать первую версию.</p>}</section></Modal>}
