'use client';
import {useState} from 'react';
import type {Node,Edge} from '@xyflow/react';
import {Modal} from '../components/os/ui';
import {parseWorkflowImport} from '../lib/os/workflow-schema';
import {validateWorkflow} from '../lib/os/workflow-validation';
import './WorkflowCodeEditor.css';

const serialize=(nodes:Node[],edges:Edge[])=>JSON.stringify({version:1,nodes:nodes.map(({id,position,data})=>({id,type:'agent',position,data})),edges:edges.map(({id,source,target,label,sourceHandle,targetHandle})=>({id,source,target,label,sourceHandle,targetHandle}))},null,2);
export default function WorkflowCodeEditor({nodes,edges,stages,canEdit,canCreate,canRemove,apply,close}:{nodes:Node[];edges:Edge[];stages:string[];canEdit:boolean;canCreate:boolean;canRemove:boolean;apply:(nodes:Node[],edges:Edge[])=>void;close:()=>void}){
 const [code,setCode]=useState(()=>serialize(nodes,edges));
 const [message,setMessage]=useState('');
 const [valid,setValid]=useState(false);
 function parse(){const graph=parseWorkflowImport(JSON.parse(code));const errors=validateWorkflow(graph.nodes,graph.edges,stages);if(errors.length)throw new Error(errors.join('\n'));if(!canCreate&&(graph.nodes.some(n=>!nodes.some(old=>old.id===n.id))||graph.edges.some(e=>!edges.some(old=>old.id===e.id))))throw new Error('Роль не разрешает добавлять блоки или связи');if(!canRemove&&(nodes.some(n=>!graph.nodes.some(next=>next.id===n.id))||edges.some(e=>!graph.edges.some(next=>next.id===e.id))))throw new Error('Роль не разрешает удалять блоки или связи');return graph}
 function check(save=false){try{const graph=parse();setValid(true);setMessage(`Проверено: ${graph.nodes.length} блоков, ${graph.edges.length} связей`);if(save&&canEdit){apply(graph.nodes,graph.edges);close()}}catch(error){setValid(false);setMessage(error instanceof SyntaxError?'Ошибка JSON: '+error.message:error instanceof Error?error.message:'Ошибка конфигурации')}}
 return <Modal title="Настройка сценария кодом" wide close={close}><div className="workflow-code-heading"><span className="badge">JSON · версия 1</span><p>Это та же схема, что на холсте. Меняйте инструкции, инструменты, условия, этапы и связи. Изменения применятся после проверки; текущая версия сохранится.</p></div><details className="workflow-code-help"><summary>Как устроен код</summary><p><code>nodes</code> — блоки: <code>id</code>, координаты <code>position</code> и настройки <code>data</code>. В <code>data</code>: <code>kind</code> — тип, <code>label</code> — название, <code>description</code> — инструкции. Для CRM: <code>action: &quot;move&quot;</code> и <code>stage</code>; для сообщения: <code>template</code>; для агента: <code>tool</code> и <code>model</code>.</p><p><code>edges</code> связывают блоки через <code>source</code> и <code>target</code>. Ветки условия используют <code>sourceHandle: &quot;yes&quot;</code> или <code>&quot;no&quot;</code>. JavaScript узлов Code хранится как текст; выполнение требует backend.</p></details><label className="workflow-code-label">Конфигурация<textarea spellCheck={false} aria-label="Код конфигурации сценария" readOnly={!canEdit} value={code} onChange={e=>{setCode(e.target.value);setMessage('');setValid(false)}} onKeyDown={e=>{if(e.key==='Tab'&&canEdit){e.preventDefault();const input=e.currentTarget;const start=input.selectionStart,end=input.selectionEnd;setCode(code.slice(0,start)+'  '+code.slice(end));setMessage('');setValid(false);requestAnimationFrame(()=>input.setSelectionRange(start+2,start+2))}}}/></label>{message&&<pre role={valid?'status':'alert'} className={valid?'workflow-code-success':'form-error'}>{message}</pre>}<div className="row"><button onClick={()=>check()}>Проверить код</button><button disabled={!canEdit} onClick={()=>{try{setCode(JSON.stringify(JSON.parse(code),null,2));setMessage('');setValid(false)}catch{setValid(false);setMessage('Сначала исправьте синтаксис JSON')}}}>Форматировать</button><button onClick={()=>{setCode(serialize(nodes,edges));setMessage('');setValid(false)}}>Вернуть текущую схему</button><button className="primary" data-permission="edit" disabled={!canEdit} onClick={()=>check(true)}>Применить к холсту</button></div></Modal>
}
