'use client';
import {useState} from 'react';
import type {Node,Edge} from '@xyflow/react';
import {Sparkles,Check,ArrowRight} from 'lucide-react';
import {parseWorkflowImport} from '../lib/os/workflow-schema';
import {proposeWorkflowChange,workflowCode} from '../lib/os/workflow-assistant';
import './WorkflowAssistant.css';
type Proposal=ReturnType<typeof proposeWorkflowChange>&{baseline:string};
export default function WorkflowAssistant({nodes,edges,stages,canEdit,canAI,canCreate,canRemove,apply}:{nodes:Node[];edges:Edge[];stages:string[];canEdit:boolean;canAI:boolean;canCreate:boolean;canRemove:boolean;apply:(nodes:Node[],edges:Edge[])=>void}){
 const [request,setRequest]=useState(''),[proposal,setProposal]=useState<Proposal|null>(null),[error,setError]=useState('');
 const baseline=JSON.stringify({nodes,edges,stages});
 function prepare(){if(!canAI||!canEdit)return;setError('');setProposal(null);try{const graph=parseWorkflowImport({nodes,edges});const result=proposeWorkflowChange(graph,request,stages,()=>crypto.randomUUID());if(!canCreate&&(result.graph.nodes.some(n=>!nodes.some(old=>old.id===n.id))||result.graph.edges.some(e=>!edges.some(old=>old.id===e.id))))throw new Error('Добавление блоков запрещено ролью');if(!canRemove&&(nodes.some(n=>!result.graph.nodes.some(next=>next.id===n.id))||edges.some(e=>!result.graph.edges.some(next=>next.id===e.id))))throw new Error('Удаление блоков запрещено ролью');setProposal({...result,baseline})}catch(e){setError(e instanceof Error?e.message:'Не удалось подготовить изменения')}}
 return <section className="workflow-assistant"><div className="workflow-assistant-title"><Sparkles size={20}/><div><b>Измени сценарий словами</b><small>Локальный помощник · модель не подключена</small></div></div><form onSubmit={e=>{e.preventDefault();prepare()}} data-permission="ai"><textarea aria-label="Что изменить в сценарии" placeholder="Например: проверь остатки и добавь подтверждение сотрудника" value={request} onChange={e=>{setRequest(e.target.value);setProposal(null);setError('')}}/><button className="primary" disabled={!canEdit||!canAI||!request.trim()}>Предложить изменения <ArrowRight size={16}/></button></form><div className="workflow-suggestions">{['Проверь остатки','Добавь подтверждение сотрудника','Задержка 10 минут','Выровняй блоки'].map(text=><button key={text} disabled={!canEdit||!canAI} onClick={()=>{setRequest(text);setProposal(null);setError('')}}>{text}</button>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}{proposal&&<div className="workflow-proposal"><h3>Проверь перед применением</h3><ul>{proposal.changes.map((change,i)=><li key={i}><Check size={14}/>{change}</li>)}</ul><p>Холст пока не изменён. После подтверждения предыдущая версия сохранится.</p><details><summary>Сравнить код до и после</summary><div className="workflow-code-comparison"><section><b>Текущий код</b><pre>{workflowCode(parseWorkflowImport({nodes,edges}))}</pre></section><section><b>Предложенный код</b><pre>{workflowCode(proposal.graph)}</pre></section></div></details>{proposal.baseline!==baseline&&<p role="alert">Схема изменилась. Подготовь предложение заново.</p>}<div className="row"><button onClick={()=>setProposal(null)}>Отклонить</button><button className="primary" data-permission="edit" disabled={!canEdit||!canAI||proposal.baseline!==baseline} onClick={()=>{if(!canEdit||!canAI||proposal.baseline!==JSON.stringify({nodes,edges,stages}))return;if(!canCreate&&(proposal.graph.nodes.some(n=>!nodes.some(old=>old.id===n.id))||proposal.graph.edges.some(e=>!edges.some(old=>old.id===e.id)))){setError('Добавление блоков запрещено ролью');return}if(!canRemove&&(nodes.some(n=>!proposal.graph.nodes.some(next=>next.id===n.id))||edges.some(e=>!proposal.graph.edges.some(next=>next.id===e.id)))){setError('Удаление блоков запрещено ролью');return}apply(proposal.graph.nodes,proposal.graph.edges);setProposal(null);setRequest('')}}>Подтвердить изменения</button></div></div>}</section>
}
