# Generated by Django 5.2.16 on 2026-10-10 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Сумма')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='core.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='шт.', max_length=24)),
                ('product_type', models.CharField(choices=[('goods', 'Товар'), ('service', 'Услуга')], default='goods', max_length=16)),
                ('weighted', models.BooleanField(default=False)),
                ('is_free_price', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('coupon_code', models.CharField(blank=True, max_length=80)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='completed', max_length=24)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coupon')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR')], default='cash', max_length=8)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('tracks_stock', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('returned', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('refunded', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.refund')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.register')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.shift'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.shift'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reference_id', models.UUIDField()),
                ('request_id', models.UUIDField(null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.membership')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='register',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='coupon_workspace_code'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0), models.Q(('kind', 'fixed'), models.Q(('kind', 'percent'), ('value__lte', 100)), _connector='OR')), name='coupon_valid_value'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('workspace', 'sku'), name='product_workspace_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('minimum__gte', 0), ('price__gte', 0)), name='product_nonnegative_values'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_id'), name='refund_workspace_request'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id__isnull', False)), fields=('workspace', 'request_id'), name='stock_movement_workspace_request'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='stock_product_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at', None)), fields=('cashier',), name='one_open_cashier_shift'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at', None)), fields=('register',), name='one_open_register_shift'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='shift_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_id'), name='sale_workspace_request'),
        ),
    ]
