# Generated by Django 5.2.16 on 2026-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coupon_product_register_sale_refund_payment_saleitem_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', models.F('subtotal')), ('refunded__gte', 0), ('refunded__lte', models.F('total')), ('subtotal__gte', 0), ('total__gte', 0)), name='sale_valid_totals'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('discount__gte', 0), ('price__gte', 0), ('quantity__gt', 0), ('refunded__gte', 0), ('refunded__lte', models.F('total')), ('returned__gte', 0), ('returned__lte', models.F('quantity')), ('total__gte', 0)), name='sale_item_valid_values'),
        ),
    ]
